### ISSUE TITLE
Job name validation from a workflow 

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/Lightning#1021]
**Describe the bug** 
When adding a job from a workflow diagram, the job name input does not validate 

The version of Lightning you have seen the bug on.**v0.7.2**  

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to Workflows
2. Click on Create new workflow
3. Add a new job with invalid characters 'M-Pesa(ETL)'
4. Try to save the job

See the bug here ⬇️ 
https://github.com/OpenFn/Lightning/assets/6592749/5bd85e8c-b718-48d0-a01c-d264c4582ac4

**Comment by NickOpenFn** [comment]
Moving to backlog to have more capacity for RTM

**Comment by stuartc** [comment]
The validation on the name for a job on the ecto model is:

```
    |> validate_length(:name, max: 100)
    |> validate_format(:name, ~r/^[a-zA-Z0-9_\- ]*$/)
```

**Comment by elias-ba** [comment]
@mtuchi currently even tho the job is placed in the canvas with a invalid name (which is debatable from a UX point of view), one can't save the workflow with a job that has invalid properties (name for this case). In the attached video we can clearly see that the save button is grayed out and the job name has the 'Invalid name' error message.

For a better UX we might need:
- a way to outline in red nodes that are invalid in the workflow canvas
- or pre-validated the input in the placeholder node (as @josephjclark said above)
- or even do both ?

**Comment by elias-ba** [comment]
After chatting to @josephjclark and @stuartc the most reasonable thing to do for now is handle validation when user is typing job's name in the canvas. Here is the plan:
1. Add job name validation rules to the job name input in the canvas
2. When name is not valid do not render the save / valid thick icon and prevent saving
3. Add a red color or error message ??
