### ISSUE TITLE
Wrong name for workflow card timestamp

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/Lightning#1022]
**Describe the bug** 
Currently the workflow card has a timestamp that says `Created .....` But when you edit the workflow, the timestamp gets updated as well. 

**v0.7.2** The version of Lightning you have seen the bug on.

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to Workflows
2. Click on an existing workflow and edit something in that workflow
3. Go back to the workflow dashboard'
4. See the updated timestamp

**Expected behavior** The card should say `Last edited or Last updated`

![Screenshot 2023-08-14 at 11 49 40 AM](https://github.com/OpenFn/Lightning/assets/6592749/b1ca7265-cd50-4622-a05e-f70661d9a883)

**Comment by taylordowns2000** [comment]
Let's go with "Updated"
