### ISSUE TITLE
Collapsible panels for Job Editor interface

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1025]
⚠️ **_Note that this work has been partially completed on the `collapsible-panels-redesign` branch. PLEASE READ ALL COMMENTS IN THIS ISSUE TO GET UP TO SPEED_** ⚠️

Right now the three panels in the Job Editor modal are locked. They cannot be collapsed or expanded. Please make it so that at any point in time, 2 of the three panels _can_ be collapsed if the user wishes.

See the basic functionality (only demoing 3/3 expanded and 2/3 expanded) [here](https://www.figma.com/proto/WeBnCPnDepC1oJXG7X1clb/Design-Sprint?page-id=182%3A17117&type=design&node-id=182-26660&viewport=577%2C544%2C0.11&t=oJLdnKE5QSWSq4X8-1&scaling=min-zoom&starting-point-node-id=182%3A28215&mode=design).

<img width="1550" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/0986f7ce-25e9-481f-b45a-49e5dab90e46">

<img width="1518" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/e4373d6e-8888-43c8-8994-4c7fa5d4a11c">

Notes:
1. If 1/3 panels is open, it takes 100% by default.
2. If 2/3 are open, they take 50% by default.
3. If 3/3 are open, they take 33% by default.
4. Being able to manually resize would be nice, but we need to determine the additional cost/LOE. If we manually resize, they must SNAP to full open and fully closed when they reach 5% of a boundary. (See the behaviour of OpenFn.org—v1—and of https://codepen.io/pen/)
5. Another nice to have is double click to maximize a panel.

**Comment by taylordowns2000** [comment]
recap from our call @midigofrank and @parlgy :

1. it's OK to drop resizing/using some sort of library for now, though I'd imagine that in the future we will want to do this.
2. the "button to hide a div, button show a div" approach works. please get this as polished as you can. (i'm worried that the transitions will feel very clunky/look ugly or unnatural, but I also don't know much about tailwind so it's possible this can almost seem like "collapse".)
3.  please try to fix the tailwind for the _contents_ of these three panels. right now the contents are spilling out the bottom. each panel should be independently scrollable.

thank you!

**Comment by taylordowns2000** [comment]
note: going to try one more hour on the CSS here and then shift to RTM.

**Comment by taylordowns2000** [comment]
@sigu , more on how this all should work
<img width="1399" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/a0bb6090-aee6-4839-9bd3-b3c98e9131d0">

**Comment by babakfp** [comment]
Hey there,

It looks like my skills could be a great fit here! 😊

I specialize in front-end development (CSS, TailwindCSS, JavaScript), and while I'm not an Elixir expert, I'm always eager for new and exciting challenges.

I've already forked the project, and you can expect to hear from me soon! ✌️

**Comment by babakfp** [comment]
If there's anyone available, please join me in setting up this project. I've been at it for three hours, and I'm encountering one error after another!

**Comment by taylordowns2000** [comment]
Hi @babakfp , thanks for your interest and willingness to help out! I'm afraid that sometimes Elixir/Erlang projects can be a little tricky if you're not accustomed to them. Did you follow the guide here: https://openfn.github.io/Lightning/readme.html#getting-started ?

Might be best to take the convo to https://community.openfn.org/ if you're having trouble getting the app set up! I'd love to hear about the errors you're having and see if we can make setup easier for non-Elixir folks.

**Comment by babakfp** [comment]
So, I recorded a video, trying to set it up, please download it from here: https://drive.google.com/file/d/12z8A7efotLBMuZYPbk4xLvLduafakNh1/view?usp=sharing

**Comment by babakfp** [comment]
I'm happy to jump on a call and try to set it up.

**Comment by babakfp** [comment]
😐

**Comment by NickOpenFn** [comment]
@sigu / @midigofrank 
Just did a quick test here:
https://www.loom.com/share/8b588bc686f642209c87cb36069926dd?sid=0ab9cbc1-a69a-4c5b-a00b-fd855bb938ae

Issues:
1. Spacing on the panel collapse button to code editor is off
2. validation wording for under input editor is off
3. Panels auto-expand when hitting "Enter" in code editor when one is collapsed
4. Panels break completely when 2 are collapsed and user hits "Enter" in code editor.
