### ISSUE TITLE
Workflow diagram breaks if a workflow contains an invalid adaptor name

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/Lightning#1034]
There is a util function in `assets/js/workflow-diagram/util/get-adaptor-name` which expects a string specifier of the form `@openfn/language-comon`.

It's a bit too rigid about this and if an adaptor name does not match that pattern, it'll throw and the workflow diagram will blow up.

**Comment by josephjclark** [comment]
I think this is the fix:
```
export default specifier => {
  if (specifier) {
    const  result = specifier.match(/@openfn.language-(.+)@/);
   if (result && result.length === 2) {
      const [prefix, name] = result;
      return name || 'unknown';
   }
  }
  return '';
};
```

**Comment by mtuchi** [comment]
Closing since we can not reproduce this bug
