### ISSUE TITLE
App crashes when trying to "run" after clicking "save"

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1047]
On the expanded job editor, after clicking "save" if the user tries to "run" the job with a selected input the application crashes.

I'm suspecting that we've reached the limit of this "manual run component" and the bug we see here (in addition to the UX we will introduce [here](https://github.com/OpenFn/Lightning/issues/1026)) will be more work to fix than implementing this component to handle the medium-to-long-term design.

<img width="1943" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/3c218c5c-abd3-4257-a3b6-4cb151985143">

**Comment by stuartc** [comment]
@taylor, I believe this is fixed in #1066
