### ISSUE TITLE
UI broken for credential creation from within the canvas

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1064]
Figma: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=349-6393&mode=design

- [x] Update the credential creation to use a modal instead of the plain pages (see Figma)
- [x] Fix incorrect spelling of "Associate" (see Figma, incorrect spelling displayed with red text)
- [x] Add in button to create a credential on the settings credential overview page (see Figma)

## Old spec
html and css messed up when creating a credential from inside the job editor. (note that it works OK when _not_ inside a the job editor "new credential" modal.)

1. there's an extra box inside the box
2. the contents of that inner box spill over outside into the outer box

<img width="747" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/89735eb5-e833-4624-affb-57b8b7052fbf">

**Comment by taylordowns2000** [comment]
After spending a few hours on the CSS here, @elias-ba recommends that the appropriate way to deliver this UI fix is to write a new Credential picker for the Job Inspector instead of loading the `credential_edit.ex` page as a modal.

The "load the entire page as a modal" approach has limitations that will never be addressable via CSS.

We still need to fix the UI here, but as he's estimating a "3 pointer" at the time of writing, we're shifting this down the backlog to address other more pressing issues.

**Comment by elias-ba** [comment]
Moving this blocked until we create a better design for the page. cc @NickOpenFn

**Comment by NickOpenFn** [comment]
@elias-ba As discussed, let's go ahead and use a modal window for creation of credentials, this way we can really reuse it within both the settings and canvas. I've updated the Issue description with the Figma links and to do list.

**Comment by NickOpenFn** [comment]
Noting: This is still not a great implementation in terms of UX - just fixing the most immediate concerns

**Comment by NickOpenFn** [comment]
Would like to keep this with Elias since we have had discussions and context in the past regarding it.

**Comment by elias-ba** [comment]
- [ ] Focus input for workflow name
- [ ] Load the edition of credential in a modal
