### ISSUE TITLE
Cannot delete some credentials via web UI

### ISSUE THREAD

**Issue by bensonmiller** [OpenFn/Lightning#1072]
I am unable to delete some credentials via the Lightning web UI. The behavior is consistent insofar as credentials that fail to delete are consistently undelete-able. Other credentials can be deleted. The issue doesn't seem to be isolated to specific credential types. I have two MongoDB credentials that refuse to delete, but I can create a new MongoDB credential and delete it successfully.   It's not clear what distinguishes credentials that can be deleted from those that can't.

Lightning version: v0.8.2

I have reproduced this locally on main:

- [ ] Yes
- [X] No

**Steps to reproduce**
Cannot be reliable reproduced, but the credentials in my account (benson.miller_at_gmail.com) that fail to be deleted are the following:  ['mongodb_atlas_test', 'DHIS2 play', 'bmiller_westaspect_gsheets']

**Expected behavior**
1. Click the credential "Delete" link 
2. Credential is removed from UI

**Other details**
Issue is present in both Chrome `Version 114.0.5735.198 (Official Build) (arm64)` and Safari `v15.3`.

**Comment by taylordowns2000** [comment]
hey @bensonmiller , sorry for the delay here! @elias-ba is looking into this today.

(my guess is that there are some foreign key issues, but the feedback is definitely missing)

**Comment by taylordowns2000** [comment]
@elias-ba , see my comment on #802  - maybe related?

**Comment by elias-ba** [comment]
> @elias-ba , see my comment on #802 - maybe related?

yes @taylordowns2000 these two are related. I am currently implementing #802 and it will ship a fix for this bug.
