### ISSUE TITLE
Page auto-refreshes and does not allow me to save my credential

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Lightning#1089]
**Describe the bug** 
I'm encountering weird bug when I try to create a `Kobotoolbox` credential on [app.openfn.org](http://app.openfn.org/). Whenever I enter in a value for API version on the credential form, the app page refreshes and/or redirects me to another page. Plus my credential does not save. (But this credential creation step worked fine when trying to create a `Raw JSON` credential.)

See this video: https://www.loom.com/share/0c547a2037ab45d7b43a2a4b5abac4de?sid=5f7a6bd0-acb1-4362-983b-dc25ea476932

**Version number** The version of Lightning you have seen the bug on.
app.openfn.org @  `v0.8.3`

I have reproduced this locally on main:

- [ ] Yes
- [x ] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to Credentials
2. Create a credential using the KoboToolbox credential form
3. Fill out all of the fields, including API Version

**Expected behavior** 
I should be able to save this credential without the app page refreshing and redirecting me to another screen.

**Comment by taylordowns2000** [comment]
@elias-ba , this one just came in from Aleksa and might be good to take on if your head is in the credential creation space

**Comment by taylordowns2000** [comment]
(for after #1064)

**Comment by taylordowns2000** [comment]
Reopen because this fix did not work. @elias-ba to test locally

**Comment by elias-ba** [comment]
Bug fixed, see [this loom video](https://www.loom.com/share/fd7a655a578f4d6aba3d4c7716ba8cf7?sid=7fb2c3cb-c1c9-44d6-bfc0-01f40eaf3891) for demo. @NickOpenFn @aleksa-krolls feel free to close this issue or request more.

**Comment by taylordowns2000** [comment]
Thanks, @elias-ba !
