### ISSUE TITLE
Part of previous edge remains highlighted when selecting new edge

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1090]
@NickOpenFn , can you help flesh this out with loom?

<img width="711" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/173ca3af-7a2b-46d7-87bd-9a7cc128b89c">

**Comment by NickOpenFn** [comment]
@taylordowns2000 closing this one and replacing with this badboy over here: https://app.zenhub.com/workspaces/product-engineering-6305f22ada44914905485ab1/issues/gh/openfn/lightning/1099
