### ISSUE TITLE
Border radius is missing on "New Credential" page

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1091]
- Fix border radius on "New Credential" page.
- Should be 8px (0.5rem) to match the other containers

<img width="496" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/0283fedc-5c9b-429e-89b3-d8d9c7c63cec">

**Comment by NickOpenFn** [comment]
Will be fixed with #1064
