### ISSUE TITLE
Warning displaying on demo login "You must log in to access this page"

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1092]
When opening up the link to login on the demo, the log in page displays a warning "You must log in to access this page" (see attached below).

I believe this is displayed when trying to auto-log you in but the credentials have expired. 

**For the main app:**
- If this is the case, then we should change the message to "Your session has expired. Please log in to access this page."
- If this is *not* the case, let me know so we can improve the wording.
- This message should not display if the user has logged themselves out.

**For the demo site:**
- This message should not exist on the demo log in at all, so let's remove it here.

To do:
- [ ] Update wording
- [ ] Remove the warning from showing on the demo page.
- [ ] Don't display the successfully logged out message with the "Your session has expired" warning
- [ ] If the user logs out, only display "You have logged out" message

_Noting_
Just noting here, I imagine that the session variable has a timestamp that determines whether the user should have access or not, so I am assuming the logic could be:
- If the login cookie does not exist, then don't display the message on login page
- If the login cookie does exist and is valid, login immediately
- If the login cookie does exist and is invalid, login page with Session expired warning

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWVOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55605759c732ace80eaed810e4efcf018f371bfa/image.png)

**Comment by stuartc** [comment]
Yeah, we could do with some cleanup and certainty on this. I think the UX (and arguably from an engineering pov) this is better than just redirecting.

Just a point on telling the difference between 'your session has expired' and 'you need to be logged in', I think there is a state we can workout where the token doesn't exist in the database (was cleaned out) _but_ you have a session cookie that was provided to the routes/plugs.

If we take a look at #1318 we can see there are lots of places in the app where we need more robust handling of moving from route to route and regular phx routes to liveviews.

Let's not underestimate this, and take stock (and list out) of all the places were we would want this functionality.

As for priority, and given my point above - I would say this is lower priority than some of the bugs we've recorded in Sentry.

**Comment by stuartc** [comment]
Sorry my above comment isn't entirely grounded in Nick's proposal. It is pretty tricky because both conditions are true, and the way it works we have no way of telling how they got there - the logged out message comes from a previous controller and the you must be authorized comes from another.
