### ISSUE TITLE
Jobs Panel not appearing when clicking on a job on the canvas

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1096]
- Loom: https://www.loom.com/share/5e5bb60c6ce44fdea6bb3a729c16ee29?sid=6e3d03cf-a0eb-4ed0-9230-c991d686df13
- Loom with an update: https://www.loom.com/share/7aba43a07279406cbe48b9ea6d1f0dcd

**Overview:**

Sometimes the jobs panel doesn't display on the canvas when clicking on the job or trigger. 
There is no certain sequence or action that happens prior, and is seemingly random.

_Noting that this has happened around 10+ times to me today._

**Comment by elias-ba** [comment]
I couldn't recreate this one locally. Has anyone else ever encountered it ?

**Comment by NickOpenFn** [comment]
@elias-ba Did you try in the demo environment too?

**Comment by NickOpenFn** [comment]
Closed as we fixed the initial issue - creating an additional issue to try recreate the issue TD was running into of it not opening again.
