### ISSUE TITLE
Canvas breaking and giving 500 error when removing and adding the first Job

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1097]
https://www.loom.com/share/50c026d1e6d64b028d377dcdecfa8f0c?sid=4f6f2fba-9935-491b-be61-c9f18e68bf6d

To recreate:
- Create a new workflow
- Delete the first Job that is precreated with the workflow
- Add a new Job after the Trigger

Now, the Job panel and Trigger panel won't open
There will be console errors
Refreshing the page will give a Internal Server Error (500)

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1097?planning-poker) with Zenhub @midigofrank @elias-ba @taylordowns2000

**Comment by taylordowns2000** [comment]
@elias-ba , @NickOpenFn , the fix here needs to take into consideration #1121 .

If we allow users to delete the first job at all (will we?) then we need to allow them to create a _new_ job (with an edge) from the trigger.

Don't know what your current thinking is here, but we could also block them from deleting the first job in the flow.
