### ISSUE TITLE
Log lines fail after 2.5k rows

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1101]
When running a job with this code:
```js
fn(state => {

  for (let step = 0; step < 10000; step++) {
    console.log(`Watch my ${step}th log go off the screen!`);
  }
  
  return state;
});
```
the log lines stop after around 2.5K rows on both the instant inspector log panel and on the history/run-view page.

<img width="2515" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/33e51446-2aec-4236-b4b2-332fd3263389">

<img width="2315" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/65df14bc-4643-4cb7-a925-5ebd1fa3f585">

**Comment by stuartc** [comment]
Fixed in 7b2559ccd9ca535fe1adf3c4b0c4903cf2233dcc, and to be addressed further in the Run/Attempt viewer in #1243
