### ISSUE TITLE
Job editor view: run log/output never appears after clicking "Save & Run"

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Lightning#1107]
**Describe the bug** 
I made an edit to my job, selected an input, and then clicked the `Save & Run` button... the run log and output (in the right panel) never updates. 
![image](https://github.com/OpenFn/Lightning/assets/16758106/b9470306-0a88-4f01-99b6-ec6d09ecda5d)
However, if I click over to the History view in another tab, I _do_ see the run (as expected). 

See video: https://www.loom.com/share/9d0c746f878e4ddcb1f680dacf8192ab?sid=df985818-3848-4a2f-892a-e29018450712

**Version number** 

If you're running on a tagged version, include the number: `v0.8.3`

I have reproduced this locally on main:

- [ ] Yes
- [x] No

**To Reproduce** Steps to reproduce the behavior:

1. On app.openfn.org, edit a job in this workflow: https://app.openfn.org/projects/c5a73b4d-5270-4c59-bba1-597c1fae3b7a/w/5e7f30c6-b847-43df-9bcd-fc454da35198?s=54c6eafb-3eeb-443a-bafc-7dd2a7a89a0b
2. Select an input
3. Click `Save & Run`

**Expected behavior**  
I should see the run output and log dynamically appear in the right side panel.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , closing this as it's tracked and will be delivered when we get #1025 into main
