### ISSUE TITLE
Creation of KoboToolbox credentials doesn't work

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1108]
Loom: https://www.loom.com/share/026cf8d2e999460e8c85896c1b4e9591?sid=df9035b2-f601-4119-940b-75f51991a2d7

When tabbing into and typing in the API field of the KoboToolbox credential creation, the page refreshes and nothing is saved.

**Comment by taylordowns2000** [comment]
closing as duplicate of #1089
