### ISSUE TITLE
Google credential creation not working 

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1109]
Note that this should be done alongside #688

- Via Slack: https://openfn.slack.com/archives/C0394D0GBUN/p1694628971132659
- Video clip of issue: https://openfn.slack.com/files/U05HRFNHPFG/F05S4JEGTE1/screenshare_-_2023-09-13_7_29_13_pm.webm

Creation of the Google credential via oAuth leads you to a page "you can close this" and doesn't create the credential within OpenFn.

1. oAuth should open up in a new window, not tab.
2. oAuth window should automatically close on success (refresh OpenFn if necessary).
3. We should display a toast that the credential has been created.

_Noting:_ This whole workflow for Credential creation needs to be rethought in terms of better UX

**Comment by stuartc** [comment]
We should check if we can move _some_ of the credential creation into the callback controller.

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1109?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc

**Comment by NickOpenFn** [comment]
@benedictus-dev 
Great on getting the oAuth working! 
Based on the conversation, let's extend this to:
1. FIX: Fix the "Re-auth" process that has that `refresh token` issue
2. QUESTION: There is a scenario that the user can remove OpenFn from their apps on Google account. If that is the case and a linked credential has a job that is run, what is returned.

Noting here for myself:
- We should have the ability to remove the oAuth connection from OpenFn's side and the ability to re-auth. This is the case when someone accidentally links their incorrect account (I'm guilty of this far too often). I also think there may be a requirement on Google's oAuth usage that states that you may need to offer this to the users.
- IIRC there is a way to pragmatically know if the connection breaks (which we had at Groove). Going to ask the team there how we did that in the past.
