### ISSUE TITLE
Favicon for OpenFn missing on Chrome 

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1110]
The Favicon is not displaying for Justin (sales / implementation team here at OpenFn). See here (number 9 on his list, but can be seen on his videos that it's clearly not displaying): https://openfn.slack.com/archives/C0394D0GBUN/p1694628971132659

_Note: This isn't occurring for me on Chrome (Version 114.0.5735.198 (Official Build) (arm64)
) nor Safari_

**Comment by taylordowns2000** [comment]
Favicons weren't added until `v0.9.0` and that loom from Justin shows `v0.8.3`.

Thank goodness for that version chip in the corner :-)

https://github.com/OpenFn/Lightning/blob/b10383eb2451c7e8991a01bb0823d75383e6fed3/CHANGELOG.md?plain=1#L45-L49
