### ISSUE TITLE
Crash and wrong error message when setting up version control

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1112]
https://www.loom.com/share/7add73420ff448ebb4a7d65af3869d66?sid=199cf13e-be48-4f88-b647-0c457e14ea21

1. When trying to set up Github version control from an "admin" project_user the Github page doesn't redirect them back to the right page.
2. When going back to the workflow page, no repo or branch is available.
3. The app displays a "bad github cert" message, but the cert is not bad because we know it works properly for the superuser.
4. No error message is sent to Sentry.
5. No error is visible in the logs.
6. It appears that a project_repo_connection has been built

Github version control works perfectly for the `superuser` on app.openfn.org

here is the link the loading stops on: `http://app.openfn.org/setup_vcs?installation_id=41428355&setup_action=update`

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1112?planning-poker) with Zenhub @midigofrank @taylordowns2000

**Comment by taylordowns2000** [comment]
Things to consider:
1. first try to get some errors to appear.
1. seems to work where `user.role == superuser` and `project_user.role == owner`
2. seems to fail all other times... consider that `user.role` should never come into play here. you can create a github connection or click "sync" if your `project_user.role` is either `admin` or `owner`.
3. If it's not `admin or owner` you should see a message saying that you can't manage github for this project.
