### ISSUE TITLE
Initial credential creation `changes` show after as `null` rather a value

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1118]
When a credential is created, an `audit_event` is generated. It should display a hash of the credential body and include the initial label as you can see in the `updated` event below and after the `created` event in this image.

<img width="913" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/73dbb929-360e-4f21-bbc1-cf401f0cb35f">

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1118?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc

**Comment by jyeshe** [comment]
From what we've discussed it shouldn't display the hash but the credential with `body` or `name` field for example.
