### ISSUE TITLE
RTM: Unexplained run timeout

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1128]
This is a bit of a placeholder for now, and we may get resolution through https://github.com/OpenFn/Lightning/issues/973 , but I want to track stuff related to run timeouts here.

@bensonmiller was using the `mongodb` adaptor locally (docker install on apple m1) and executing a load-to-mongodb job succesfully in milliseconds. He let me take a look at a run that timed out on his app.openfn.org account and not only was it strange that it took more than a few hundred ms (loading no more than 1MB json to mongo) but the recorded runtime was `17104 ms`. That's way shorter than the current timeout limit, even with our fairly aggressive beta configuration. (We're timing runs out at 60 seconds.)

My guess is that this wasn't a timeout, but an error in communication between the node VM and the elixir app.

If that's the case, #973 will take care of it but we should pay special attention to the exit codes (and unresponsive worker cleanup) that Elixir uses when receiving (or not receiving) results from the javascript workers.

We should also make sure that the UI on the history page is aligned with any new exit codes (@NickOpenFn ) that come back and update the exit code documentation for lightning: https://docs.openfn.org/documentation/jobs/errors

This may need to change with RTM, but parity with v1 would look like this:
```ex
          <%= case @run.exit_code do %>
            <% nil -> %>
              <.pending_pill class="font-mono font-bold">?</.pending_pill> # grey
            <% val when val == 0 -> %>
              <.success_pill class="font-mono font-bold">0</.success_pill> # green
            <% val when val == 1 -> %>
              <.failure_pill class="font-mono font-bold"><%= val %></.failure_pill> # red
            <% val when val == 2 -> %>
              <.timeout_pill class="font-mono font-bold"><%= val %></.timeout_pill> # yellow
            <% val when val > 2 -> %>
              <.crash_pill class="font-mono font-bold"><%= val %></.crash_pill> # black
          <% end %>
```

cc @stuartc , @josephjclark

**Comment by bensonmiller** [comment]
Thank you @taylordowns2000. Please let me know if I can add any additional details to this.

**Comment by josephjclark** [comment]
I think this will go away soon (or perhaps evolve into a different issue entirely).

We're currently in the process of creating a new job runner/worker/engine #973 which uses a different process to Lightning. Same underlying runtime, but it lives in a different process and is designed as long-running worker.

Right now Lightning uses the CLI, which takes time to spin up for each run and isn't really designed in any way for efficiency. The time it takes to spin up the process is part of the runtime and will affect timings.

We've just been talking about error codes for the new worker and we'll ensure they match the old setup (or, if they diverge, they do so for a very good reason).

Let's see - I think first step is to switch to the new engine (in a couple of weeks) and then run some tests against mongo, see what happens.

**Comment by stuartc** [comment]
@taylordowns2000 is this still valid?

**Comment by taylordowns2000** [comment]
I don't think so as I haven't seen it pop up again since `v0.10.0`, but i'd like to leave the ticket open for a few more days just in case.
