### ISSUE TITLE
RTM: Manual runs need to work with the new Attempts queue

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#1135]
Currently Manual Runs use the Pipeline module - this is now deprecated and to be replaced by: the `WorkOrders` module.

See the `release-0.10.0` branch and the new [`WorkOrders`](https://github.com/OpenFn/Lightning/blob/release-0.10.0/lib/lightning/work_orders.ex) module.

There currently is no function to create a manual work order here, we need to add it.

A manual work order must have provide a `:created_by` key in order to know who created it.

Since the release branch is under active development so some reading is required, please ask any questions.

**Comment by taylordowns2000** [comment]
@stuartc , can you flesh this out a bit?
