### ISSUE TITLE
Improve Icon loading on Canvas so the icons load in gracefully

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1140]
**Overview:**
1. The icons on the canvas look great, however they are loading in and rendering very abruptly.
2. If there is any delay on the icons loading the text displays - which creates a strange experience of it loading "twice"

Possible Solutions:
- Add in a animation & wording to display on the nodes (this is good regardless of issue 2 above)
- Preload & cache the images to be ready to display when user logs in on the workflow overview page
- If preloading is not possible, then perhaps we improve the perceived display of these with animations. We delay the text by showing and then image from showing by .250ms, and then _hopefully_ the images will be ready and display before the text. 
- Another potential solution would be only to render the canvas once the images are ready.

**Comment by josephjclark** [comment]
I noticed this yesterday.

This is a fairly easy fix - what's happening is the app is downloading the icon manifest every time it renders an icon. For some reason it seems to be doing it serially too. Basically move the `fetchAdaptorIconsData` function in  `Job.tsx` elsewhere and call it on mount.
