### ISSUE TITLE
Changing user role in user management section in projects for superuser view is broken

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1145]
Figma: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=958-376&mode=design&t=namlM3lEok52ZDMh-11

URL (superuser): https://demo.openfn.org/settings/projects

While testing, there seems to be multiple bugs when adding/removing/updating users to a project and the UX is extremely confusing (may be more so due to the bugs). 

In addition to fixing the bugs, I'd like to simplify the user management process buy simply using a table. This isn't a perfect solution, but would be a fast solution that is highly functional and easy to understand.

----

**Loom:** https://www.loom.com/share/0e4b679037f34938bbfe557b1af9d8d8?sid=28b75946-a4ef-44b5-b9e6-231a6240bbc8

**Sentry log:** https://openfn.sentry.io/issues/4496460827/?alert_rule_id=11218001&alert_type=issue&notification_uuid=d13289d5-0450-4942-92f3-1095c71781b5&project=6446500&referrer=slack

**Comment by NickOpenFn** [comment]
Should tackle at the same time with: https://app.zenhub.com/workspaces/thunderbolt--lightning-6305f22ada44914905485ab1/issues/gh/openfn/lightning/1239

**Comment by NickOpenFn** [comment]
Noting, spec here is short term fix. Better user management will come in future.

**Comment by stuartc** [comment]
Can't recreate this as of ae010c117881c9093cebe6f46f3dba6465dbf45f.

**Comment by taylordowns2000** [comment]
hey @stuartc , check out this screenshot from `136552f` . The two bugs here are:
1. you can't see the names or email addresses of any users in the project in the rows
2. if you try to remove one of these invisible project users with the remove button, when you press save no error is displayed and yet the project user is _not_ removed. (Go back to the project edit screen and you'll still see them there.)

You can repro this by resetting demo or logging in as `super@openfn.org` on demo.openfn.org and navigating to the superuser section and editing a project

<img width="1126" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/2f931939-41d9-4959-84cb-6b0c16f0db97">

**Comment by stuartc** [comment]
@midigofrank for the table ux, can you make sure that becomes a component please?

**Comment by NickOpenFn** [comment]
@midigofrank Hold off on this again till we chat in the morning. Might be worth actually just going with the table if it's easiest and you haven't refactored the screen yet
