### ISSUE TITLE
UI/UX: Ensure that the whole edge when selected is highlighted

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1160]
Please see attached (below).
The edge is selected but the first part of it is not displayed in purple, which it should.

_Note:_
- Considering doing the curved lines as a better solution :: Decision made in comments

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFhoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1c8695542694300d725150657fb6454ac677d326/image.png)

**Comment by NickOpenFn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1160?planning-poker) with Zenhub @elias-ba

**Comment by NickOpenFn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1160?planning-poker) with Zenhub @midigofrank

**Comment by NickOpenFn** [comment]
Either smooth or bezier, Nick to align with TD on it. 
https://reactflow.dev/docs/examples/edges/custom-edge/

**Comment by NickOpenFn** [comment]
Decision made on using "Bezier" style for edges to resolve the overlap issue.

**Comment by taylordowns2000** [comment]
will close #949 (duplicate?)
