### ISSUE TITLE
Zero-persistence: History Page 

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1210]
When the user has Zero-persistence enabled, we need to disable certain functionality on the history page since the data won't exist.
- Figma: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=331-5765&mode=design&t=6IdtumAfCQZ8SEMe-11

Items:
- [x] Disable the "Rerun" button (grey it out) and display a tooltip
- [x] Disable the click for the Dataclip and display a tooltip
- [x] Disable the checkbox for the Workorder and display a tooltip that you cannot rerun the workorder
- [x] Tooltip to link to settings page
- [x] If non-admin, then the tooltip needs to be slightly tweaked: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=706-4166&mode=design&t=6IdtumAfCQZ8SEMe-11

**Comment by taylordowns2000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1210?planning-poker) with Zenhub @elias-ba @jyeshe @midigofrank @stuartc
