### ISSUE TITLE
Zero-persistence: Attempt and Run detail page

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1211]
From the History page, you can access the run detail page for each job that was attempted within a run workflow.
If someone has zero-persistence enabled, then they cannot view the details of the input and the output data on these pages.

When someone tries to access these pages, there needs to be content indicating that there is no data and the reason why. 

If the user has the correct admin access to edit the settings, they can link off directly.

If they don't have the admin access, the wording will change and inform them to speak to one of their account administrators. On hover, we can display the list of admins for simplicity for the user.

- Input data: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=1497-466&mode=design&t=0k7X53XaId2o3C67-11
- Output data: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=1497-482&mode=design&t=0k7X53XaId2o3C67-11
- No admin access: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=1497-493&mode=design&t=0k7X53XaId2o3C67-11
- 

Acceptance Criteria:

- [x] Whether looking at the "Inspector" or the "Run Viewer", if the project has zero-retention enabled you cannot see `run_result` dataclips in accordance with the figma.
- [x] When you look at the `http_request` dataclip for such a proejct, you should see the redacted dataclip.
- [x] When you look at the "Inspector" or the "Run Viewer" for a project _WITHOUT_ zero-persistence and there is no dataclip, it tells you that there isn't a dataclip (either `YET` or `EVER`) but does not inaccurately tell you that you probably have zero-persistence set.

**Comment by taylordowns2000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1211?planning-poker) with Zenhub @elias-ba @jyeshe @midigofrank @stuartc
