### ISSUE TITLE
Zero-persistence: Build Backend functionality for Zero-persistence 

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1212]
Once users enable zero-persistence from the settings section(#1209), we need to ensure that the data is not persisted (duh!).

**Worker:**
Extend worker to support Zero-persistence:
- https://app.zenhub.com/workspaces/kit-64d36072fcd9fb4aa00a3db9/issues/gh/openfn/kit/562

**Lightning:**
- Admin settings, need to save retention period and one of `n` (3 right now) options for zero-persistence
- In the websocket handler, decide to save or not save `dataclips`.
- When we send a plan to the worker, add an attribute to request that the workers _NOT_ send back `run_results` 
- We are still broadcasting logs as they arrive. (NO CHANGE TO LOGS!)
- "tidy" dataclip _after_ either the dataclip has been 'used':
    - either after 'fetch:dataclip'
    - or after job is finished/orphaned/missing
 - relax dependency on `input_dataclip_id`
    
Still tbd:
- Define what "tidy" means:
    - i.e. we are keeping the dataclip records, but not the body?
    - 

Acceptance criteria:

- [ ] See new attribute in `plan` that instructs worker to send/not-send `run_results`
- [ ] After a `http_request` dataclip is used in a workorder, if I view that dataclip I can see that the `body` of the webhook request is no longer visible. (redacted, tidied, something)
- [ ] After a workorder is executed, if i view the workorders in a proejct where this setting is enabled (via the DB, there's no frontend yet!) there are no `run_results` created for that work order.
- [ ] When running with an old version of the worker which doesn't yet know about "zero persistence" we will receive `run_results` over the wire, but we will NOT persist them.

**Comment by stuartc** [comment]
- Rerun is disabled if the input dataclip is deleted
- Does Platform actually truly delete the records afterwards?
    - Would we ever need to use the 'empty' records for stats?

- We need to tell the worker, to send back dataclips back or not.
    - Lightning then decides whether to persist things or not.

**Worker**

- Options to control log and dataclip emission on 'plan'

**Lightning**

- Admin settings, need to save retention period and one of `n` (3 right now) options for zero-persistence
- In the websocket handler, decide to save or not save logs or dataclips.
- We are still broadcasting logs as they arrive.
- "tidy" dataclip _after_ either the dataclip has been 'used':
    - either after 'fetch:dataclip'
    - or after job is finished/orphaned/missing
- Define what "tidy" means
    - i.e. we are keeping the dataclip records, but not the body.

**Comment by taylordowns2000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1212?planning-poker) with Zenhub @elias-ba @jyeshe @midigofrank @stuartc

**Comment by midigofrank** [comment]
blocked by #1209
