### ISSUE TITLE
Allow users to view details of an attempt (attempt detail page)

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1243]
## Overview:

Currently users can view the details of a run on a job (on the Run page), and have an overview of the workorder run (on the history page) - but do not have an overview of the attempt.

**To do:** 
1. Creation of the Attempt overview screen.
2. Update History table to access the attempt detail page. 

### 1. Attempt overview screen

Figma: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=858-4291&mode=design&t=FAlI1MQiRCLpdd9N-11

Accessible via the History page (details below), the page needs to contain:

- Overview section at the top, with the following fields:
  - Workflow name
  - Attempt ID (styled correctly)
  - XXX (Chat to Nick to see what we should pop in here)
  - Exit Reason (styled correctly)
  
- Associated runs:
  - This is the Runs of the jobs that executed for the attempt
    - **We will have the following columns:**
      - Job name (including status of success/failure indicated by icon)
      - Job Run start time `Run started`
      - Job Run completion time `Run ended`
      - Job total runtime `Duration`
  -  If the user chooses to rerun a job, a new attempt page will open with the new attempt

If an attempt is busy _running_ we will have the associated run table fill with the exact same behaviour we have on the History Page currently.

**Log section:**
- This will display the full log of the attempt.

 
**Minor UX improvements:**
- Wherever we have a overview table with the details, let's add the dashed line below so people can scan it easily.
- On the Run table (same on the history page) let's have a hover state to indicate which row they hovering on

### 2. History page changes

Figma:  https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=901-4531&mode=design&t=FAlI1MQiRCLpdd9N-4

We need to make the attempt detail page accessible on the History page, to do that:
- When a Work order is expanded, if only a single attempt has run it still needs to display the attempt banner (with no "Show more attempts" hyperlink.
- Attempts now need to display ID's, which are hyperlinked (like the data input ID's):

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1243?planning-poker) with Zenhub @stuartc @elias-ba @midigofrank @benedictus-dev @jyeshe

**Comment by taylordowns2000** [comment]
@stuartc there is one more thing that I don’t want to loose from the old run detail view… it’s the little indicator of the dataclip type. Super important to help users understand the major differences between how we handle http_request and run_result or saved_input . Here it is: https://github.com/OpenFn/Lightning/blob/main/lib/lightning_web/live/run_live/components.ex#L505-L507

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a94dbc74a7d868a70950f9cfdc37b14423e6d356/image.png)

**Comment by stuartc** [comment]
@taylordowns2000 my merge may have closed this prematurely, I haven't been super thorough on the criteria here - the dataclip type can come into the next one (updating the manual run viewer), as for the others please let me know if I should reopen this or make another issue.
