### ISSUE TITLE
Update UI to reflect new product naming

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1248]
- [ ] Settings: "MFA" => "Two-factor authentication"
- [x] History: "attempt 1 of 2" => "run 1 of 2"
- [x] History: "Run Started At" => "Step Started At"
- [x] History: "Run Finished At" => "Step Finished At"
- [x] Attempt Live: "Attempt" => "Run"
- [x] Attempt Live: "Attempt ID" => "Run ID"
- [x] Canvas: "Delete Job" => "Delete Step"
- [x] Ensure work order isn't shown as a single word. On the FE, it's "work order", not "workorder".
- [x] Inspector: "Dataclip" => "Input" 
- [x] Inspector: On the dataclip drop down, update label to say input
- [x] Inspector: "Save & Run" to "Save & Run from step"

**Comment by taylordowns2000** [comment]
@NickOpenFn , @elias-ba , i see that this got marked as draft and moved back to "Sprint To Do" but I can't see the actual review anywhere. All the checkboxes on the issue are done. Is there something that needs to be done here?
