### ISSUE TITLE
Handle `attempt:complete` events from worker to set state

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1251]
@stuartc , @josephjclark , @jyeshe , some decision making and implementation is needed around `attempt:complete` handling.

### What's happening now?

When `ws-worker` sends an `attempt:complete` message to the attempts channel, it looks like this:
```ex
Last message: %Phoenix.Socket.Message{
  topic: "attempt:29e73c3f-fb74-4441-b04e-293a9de5b445",
  event: "attempt:complete",
  payload: %{
    "final_dataclip_id" => "62a5f87e-5686-4a0d-bf95-88655ddee625",
    "message" => "fn is not defined",
    "reason" => "fail"
  },
  ref: "35",
  join_ref: "29"
}
```

This results in a GenServer error:

```
[error] GenServer #PID<0.1675.0> terminating
** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "state" of relation "attempts" violates not-null constraint

    table: attempts
    column: state
```

## How to approach it

We need to look carefully at:

1. [lib/lightning/attempts/handlers.ex:184: complete_run](https://github.com/OpenFn/Lightning/blob/release-0.10.0/lib/lightning/attempts.ex#L184-L188)
2. [lib/lightning/attempts/handlers.ex:88: complete_attempt](https://github.com/OpenFn/Lightning/blob/release-0.10.0/lib/lightning/attempts.ex#L88-L97)
3. and the [handlers](https://github.com/OpenFn/Lightning/blob/release-0.10.0/lib/lightning/attempts/handlers.ex)

To decide how and where we map `attempt:complete` messages coming from the worker back to `:state` for attempts.

## User acceptance criteria

I'll test this by running an end-to-end test...
1. `openfn/lightning`: `iex -S mix phx.server` (with worker secret in `.env.dev`)
2. `openfn/kit/packages/ws-worker`: `WORKER_SECRET="shhhhhhh" pnpm start`
3. Start an attempt on Lightning
4. Ensure it's executed and all data gets sent back to Lightning.

**Comment by josephjclark** [comment]
I think the payloads of `run:complete` and `attempt:complete`  still need a little finessing. It looks like this issue is all lightning-side but this is a good time to make sure we're on the same page.

I've written up the `run:complete` payload here: https://github.com/OpenFn/kit/issues/396#issuecomment-1788705705

I'll save you a click:
```
reason: 'ok' | 'cancelled' | 'failed' | 'killed' | 'crashed' (I don't send 'lost', lightning must infer it)
dataclip: Object,
message?: string // human readable, user-friendly, english language string
error_type?: string // a finite (but growing) list of known errors, ie, ReferenceError, AdaptorError, OOMError
source?: what component (runtime, worker, engine, compiler) reported the error
```

Questions / comments
* Are reasons past tense (cancelled) or present (cancel) ?
* `ok` or `success`?
* I don't like `error_type`, but `type` is too vague. Maybe `error: ReferenceError` is ok?

**Comment by josephjclark** [comment]
I think we're settling on present  tense reasons - I'm editing the comment now
