### ISSUE TITLE
Ensure path conditions match the worker's expectations

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1268]
- Currently, Lightning allows users to set path conditions with a select list and restricts their options to one of `[:on_job_success, :on_job_failure, :always]`
- The worker, however, expects `["!state.errors", "state.errors", "true"]`.
- In the future, users will be able to enter any valid javascript expression for their path condition.
- For now, however, we need to modify the UI (and write a migration for the existin data in the DB) that changes path conditions as follows:

| Select Option | Old Select Value (and value in DB) | New Select Value (and value in DB) |
|--------|--------|--------|
| On Success | "on_job_success" | `Boolean(!state?.errors?.${upstreamId} ?? true)` |
| On Failure | "on_job_failure" | `Boolean(state?.errors && state.errors.${upstreamId} && true)` |
| Always | "always" | "true" | 

In the PR that closes this issue, we'll expect:

- [ ] changes to the UI for these new value mappings
- [ ] changes to the edge model (no longer restricting to a set of three atoms)
- [ ] a DB migration that changes existing values to new values, per the table above

**Comment by josephjclark** [comment]
Hi @taylordowns2000 - this is already fixed in the worker! `on_job_success` is accepted and mapped workerside.

Edge conditions do need to change in Lightning, but not today

**Comment by taylordowns2000** [comment]
@josephjclark , when we merge https://github.com/OpenFn/kit/pull/508 we should update the spec here accordingly! (because soon we won't rely on you to convert path conditions, we'll provide them as is)

**Comment by josephjclark** [comment]
I've updated the conditions. They could be a bit more terse but I wanted them to explicitly return true or false. I don't think the boolean wrapper is strictly necessary tbh.

Also, another consideration for this work - I want the runtime to pass a bunch of helper functions into the condition, like `jobFailed()` or `jobSuccess()` or something. That would handle the heavy logic and allow lightning to pass simpler expressions.

it's probably a good idea for me to implement those in the runtime before we do the mapping. I'm gonna raise an issue now.
