### ISSUE TITLE
Close ws-worker port when shutting down the app

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1272]
- If the app is started in dev mode, we run `npm exec @openfn/ws-worker` via a port.
- Later, this will be replaced with a binary and we'll bring in some esbuild-style goodness, but that's for later.
- For now, when a developer shuts down the app with `control-c`, the NodeJs worker app is left running... we're not sending the proper `Port.close` command, or SIGTERM, or whatever is required to stop the NodeJs worker app.
- It's a pain in the butt because the dev then has to do something like `kill $(lsof -n -i :2222 | grep LISTEN | awk '{print $2}')` to kill that old NodeJs process before they can reboot their app... or else they'll get an `Error: listen EADDRINUSE: address already in use :::2222`
- After a quick chat with @jyeshe and @josephjclark , it sounds like #1266 might take a while, but that handling the exit for this current implementation and shutting down the app we start with `npm exec` will be significantly easier.
- And it will make the DX _much_ better!

This issue is to do just that: if the app is started with `mix phx.server` in dev mode and we open a port for `npm exec @openfn/ws-worker`, make sure that we close that port when we stop the app.

**Comment by jyeshe** [comment]
When exiting/stopping the app, killing the worker port process doesn't terminate the socket process (nodejs).

This socket process is the last child process on the tree:
```
$ pstree -p 132174
bash(132174)─┬─bash(132176)───bash(132177)
             └─npm exec @openf(132175)─┬─sh(132368)───node(132369)
```

Which can also be obtained with:
```
$ ps -s 132174 -o pid=
 132174
 132175
 132176
 132177
 132368
 132369
```

**Comment by josephjclark** [comment]
That sounds like an issue for me @jyeshe

**Comment by josephjclark** [comment]
@jyeshe how are we killing the worker process right now?

**Comment by jyeshe** [comment]
> That sounds like an issue for me @jyeshe 

Sure thing. It is an issue of lacking tear-down port cleanup.

**Comment by jyeshe** [comment]
> @jyeshe how are we killing the worker process right now?

It was letting the OS to do the whole cleanup.

**Comment by josephjclark** [comment]
I've been investigating a bit and I'm really not sure the worker is at fault here. I don't think it gets a kill signal when Lightning is closed.

When the worker process is killed, the server stops listening to the port. This is easily proven by starting the server `npm exec @openfn/worker` and hitting CTRL+C to kill it. I also have a whole suite of unit tests which teardown the server and then recreate it.

I've added a listener for SIGINT and SIGTERM to the server and run it locally: when Lightning is terminated, node sees neither signal.

If I `kill` the server process directly, I DO trigger the SIGTERM signal.

I can use `lsof -n -i 2222 | grep LISTEN` to get the process id of the server (neat trick, thanks!), and then do `pstree -ps <server-pid>` to get its _parent_ process (another neat trick, thanks again!). And that doesn't seem to be connected to lightning at all, I think it's a standalone process.
