### ISSUE TITLE
add seed data for demo site and testing

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#131]
### User story
When I set up a new implementation of Lightning using docker, I would like to pre-populate my instance with some existing data (jobs, credentials, and users) so that I can start trying it immediately. 
Start with MOH Ghana jobs as an example.

### Details
Project: OpenHIE demo project
Workflow: OpenHIE demo workflow
- On patient registration
- Transform data to FHIR standard
- Send to OpenHIM to route to SHR
- (on success) Notify CHW upload successful
- (on failure) Notify CHW upload failed

Project: DHIS2 demo project
Workflow: Load DHIS2 data to sheets
- Every hour ?
- Get DHIS2 data
- Upload to google sheet

users:  
first_name: openhie_admin lastname: admin
email: openhie_admin@gmail.com
pw: openhie_admin123
has access to: openhiedemo project
does not have access to: DHIS2 demo project

first_name: openhie_editor lastname: editor
email: openhie_editor@gmail.com
pw: openhie_editor123
has access to: openhiedemo project
does not have access to: DHIS2 demo project

first_name: openhie_viewer lastname: viewer
email: openhie_viewer@gmail.com
pw: openhie_viewer123
has access to: openhiedemo project
does not have access to: DHIS2 demo project

### Implementation notes
There should be no superuser in the seed data as we should make sure the person who sets up Lightning locally creates their own superuser account.

### Release notes 
- [ ] Generate test users and projects on startup

### Tests 
N/A

### QA
- [ ] This has been QA’d by Amber, branch can be merged after review

**Comment by taylordowns2000** [comment]
@stuartc , interesting question here: this is how we will set up our nightly-refreshed (dropdb/creatdb, run seeds) "demo" site for Lightning (think play.dhis2.org) . For that reason, it's important that these seeds are tested but off the top of my head I'm not sure how you'd test an `.exs` file!

Could we write these seeds in a module, then call that module both in the exs file _and_ in a "seeds test" file which checks to ensure that the example project can be built and that everything is where it's supposed to be?

**Comment by elias-ba** [comment]
@taylordowns2000 @stuartc for the question above, I did some researches yesterday on how to organize seeds and maybe be able to write tests for them. The most promising thing I found was in the Ecto doc [here](https://hexdocs.pm/phoenix/1.3.0-rc.1/seeding_data.html)

```
We can also create a module to seed our data. The reason this is sometimes advantageous is it allows us to quickly seed from IEx, and also keeps things modular. For example:

defmodule <%= application_name %>.DatabaseSeeder do
  alias <%= application_name %>.Repo
  alias <%= application_name %>.Link

  @titles_list ["Erlang", "Elixir", "Phoenix Framework"] // list of titles
  @urls_list ["http://www.erlang.org", "http://www.elixir-lang.org", "http://www.phoenixframework.org"] // list of urls

  def insert_link do
    Repo.insert! %Link{
      title: (@titles_list |> Enum.take_random),
      url: (@urls_list |> Enum.take_random)
    }
  end

  def clear do
    Repo.delete_all
  end
end

(1..100) |> Enum.each(fn _ -> <%= application_name %>.DatabaseSeeder.insert_link end)
Now, we could add links trivially to our database in IEx like so:

$ iex -S mix
iex(1)> <%= application_name %>.DatabaseSeeder.add_link
iex(2)> <%= application_name %>.Link |> <%= application_name %>.Repo.all
#=> [%<%= application_name %>.Link{...}]
This is nice for experimenting in IEx during development in many cases.
```

I think the idea of having a Seeder module is excellent for this case and we could be writing unit tests for that module and then a mix task for it. I haven't implemented it yet, but I am happy to do so if you think it's the way we should go.

**Comment by elias-ba** [comment]
But then an interesting question is, how relevant it is to write test for seed data ? I mean seed data in itself is a kind of setup for tests (most of the time)
