### ISSUE TITLE
Improve behaviour of "Save" button becoming active on forms when all fields are valid

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1310]
Loom: https://www.loom.com/share/a926e245724643d294ee3a9c5e731a19?sid=91443d2b-9af3-4959-adf0-f79f1fad6420

Currently we have onBlur validation to see if the field is valid, which is correct in most cases (eg: email validation where you don't want t afield telling you that your email is invalid until you done typing).

However, we are using onBlur to do validation to enable the "Save" (which are disabled till all fields are valid). 
The issue here, is that it's very common for a user to hit the save button without unfocusing the field they were in (ie, typing in their password and using the mouse to immediately go to press the button).

We need to change the behaviour to check if the required fields have values for the button to be enabled.
Since some validation will be on blur, we will need to check onClick if the fields are valid before submitting the form.

**Areas to update:**
- [ ] Webhook auth method API creation
- [ ] Webhook auth username/password creation
- [ ] Editing both above ^^

**Comment by taylordowns2000** [comment]
hey @NickOpenFn and @benedictus-dev , i see that this was dependent on #1103 but that has now been done. should it be moved out of blocked?

**Comment by benedictus-dev** [comment]
Hi @taylordowns2000 , I believe this issue is now resolved.
Thank you.

**Comment by taylordowns2000** [comment]
@NickOpenFn , just chatted with @benedictus-dev and we can close this one!
