### ISSUE TITLE
Add Webhook auth. method button is disabled on newly created workflows

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1319]
When creating a new workflow, selecting the trigger and hovering over the "Add authentication method" hyperlink is disabled (even once the workflow is saved).
Fixed on refresh.

**Comment by NickOpenFn** [comment]
Can't recreate this...

**Comment by jyeshe** [comment]
hey @NickOpenFn, this seems to be resolved by the fix of #1280.
It is only disabled before saving with the hint to the user.
