### ISSUE TITLE
Docs can't be expanded when viewed in left to right view

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1329]
Scrolling is not working on the following areas in the job editor:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmtCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01cbf3b52b527c98bcd0b748e0a74d7a02c774b0/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1BQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2aaf21700288892b9ac14fc70c79843e1e51168/image.png)

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1329?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc

**Comment by jyeshe** [comment]
Collapse continues to work only on part of the signature even using `react-collapsed` 5c48a7741 or a plain html button (cursor is not a pointer for the width of the signature).
