### ISSUE TITLE
Can't see flashing cursor in login text input

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1366]
The normal flashing cursor doesn't appear in the username or password field on login. This happens on `v0.10.0-pre5` and Chrome Version 119.0.6045.105 (Official Build) (arm64)

**Comment by stuartc** [comment]
@taylordowns2000 could you verify this again? I can't recreate this either Brave (Chrome 119.0.6045.163) or on Firefox 119.0.1. I'm on Arch Linux (amd64).

**Comment by taylordowns2000** [comment]
awesome. can't repro here either. thanks guys :-)
