### ISSUE TITLE
Don't make inspector modal close when monaco editor is focused

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1367]
Sometimes developer users will try to close a tooltip in monaco with the `esc` key and accidentally close the whole modal. When monaco is focused, it should own the keybindings _except_ for `save` and `save & run`.

Desired UX:
1. If you're typing in the manual dataclip json editor or monaco expression editor and you press esc...
2. the first time it should defocus the input field
3. the second time it should close the modal

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1367?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc
