### ISSUE TITLE
Resolve adaptor version on lightning, before sending attempt to worker

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1369]
Use the AdaptorRegistry tooling to resolve the adaptor version on Lightning before sending it to the worker.

This will let us use a cron job to look for new adaptors periodically. Otherwise the worker might keep the same "latest" for weeks without checking NPM.

@stuartc , is this right?

@josephjclark , are you cool with this being handled by lightning, not the worker?

To be clear, this is only important for cases where we've got `@openfn/language-http@latest` stored in the lightning db.

**Comment by josephjclark** [comment]
I'm pretty sure Lightning is already doing this - the original issue merged because the end-to-end tests happened to not include an adaptor version. That's been resolved now. So I suspect there's no action from Lightning here.
