### ISSUE TITLE
Text color of button contents is incorrect on Auth method screen

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1443]
This seems to only be the case when in the settings section, not via the canvas

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVgrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7749820acc8a788b2bb1ed4090b282a28d1c9d02/image.png)

**Comment by NickOpenFn** [comment]
@taylordowns2000 I am guessing you fixed this on the fly?

**Comment by taylordowns2000** [comment]
Not that recall!

Taylor Downs
CEO, OpenFn
