### ISSUE TITLE
Review Audit Events For Credential And User Deletion

### ISSUE THREAD

**Issue by elias-ba** [OpenFn/Lightning#1457]
The Audit Event for credential deletion is happening in the `Credentials.perform(%Oban.Job{args: %{"type" => "purge_deleted"}})` function. This is wrong because at that moment we do not know who the actor is. The event actually should happen when the credential is being scheduled for deletion. This issue is for fixing that behavior. I believe we should have two type of Audit Events. Credential deleted is the event for when a credential is scheduled for deletion. And Credential Restored is the event foe when the credential schedule for deletion is canceled.

I also haven't seen any Audit Event being logged when we delete a user. Is this a wanted scenario or something we are missing ? cc @NickOpenFn @taylordowns2000 @stuartc

**Comment by NickOpenFn** [comment]
@elias-ba / @taylordowns2000 
I am closing this task in consideration of #1469 - I think any work we do here now is trivial and we should rather commit the energy to fixing audit trails completely and having it as part of the development workflow to ensure they always included in (as required) when shipping features. Doing this now really just feels like wasted effort for a bigger, better solution in the _near-ish_ future.

Let me know if you disagree!
