### ISSUE TITLE
Render a plus icon below the last job in a workflow

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#146]
### User story
As a user that's building out a new integration, I would like a plus icon below the last job in a workflow, so that I can intuitively know I can add another step.

### Details
This could be a block with a + icon. This issue blocks https://github.com/OpenFn/Lightning/issues/145.

![Screenshot 2022-08-26 at 18 58 10](https://user-images.githubusercontent.com/36554605/186964340-fae54f08-a1d3-4b0c-94de-586c485b994a.png)

### Release notes 
n/a

### Tests 
When I load the builder, I can see a block with a + icon below the last step in the workflow. 
Given a workflow that ends with job A with two downstream jobs (job B on success, and job C on failure), I should see a + block below both job B and job C. 

### QA
- [ ] This has been QA’d by Amber, branch can be merged after review

**Comment by taylordowns2000** [comment]
@stuartc , if you pick this up can you work from `add_plus` to get some of the new styling changes that I've added?
