### ISSUE TITLE
Deselecting edge fails to remove highlighting

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1471]
1. When a node in the canvas is selected, it gets outlined in purple and the right-hand-side form opens.
2. When you click "X" on that form, or when you click on a blank area of the canvas, the form closes and the purple outline disappears.
3. If you click an edge, it also gets a purple outline.
4. If you click away from that edge to _another_ edge or node, the purple outline dissappears.
5. But if you deselect that edge by closing the form (with the "X" button) or by clicking on a blank area of the canvas, the purple outline remains.
6. It will stay there until you select another edge or node.

See image here for a selected edge - it's purple and the form is open. That's good ✅ .
<img width="751" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/bb628a64-1758-4b07-b7a4-36d815dc184c">

And see this image for the deselected edge that comes when you click on an empty spot or close the form. The edge should not be purple.

<img width="739" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/dcdb61ef-33c5-424b-b178-6d1b69233b67">

I think this is unrelated, but I've also noticed that clicking on the blank canvas adds a `?placeholder=true` query param to the URL. This smells a little funny to me, as I think that param should only appear when adding a placeholder node.

**Comment by NickOpenFn** [comment]
Fixed via improvements to the selection control by @stuartc
