### ISSUE TITLE
Turn user settings page into a liveview component

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#149]
Currently, the user settings (at /profile) page is a controller (you can see the files for it in lightning/lightning_web/controllers). We'd like this to be converted to a liveview component, following the same pattern as the other pages in the lightning_web/live folder.

Don't forget to add tests, and please make sure that the 'confirm email' flow will still be possible.

**Comment by taylordowns2000** [comment]
this was closed by https://github.com/OpenFn/Lightning/pull/218
