### ISSUE TITLE
Allow Javascript expressions as conditions for edges

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1498]
**Figma:** https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=1086-3945&mode=design&t=9AetCDKXOYdq9T4m-11

We will now include a conditional match where the user can compare the output of the previous job against a Javascript expressions. 

**Edge panel:**
- Include new dropdown item "Matches a Javascript Expression" in the drop down list for conditions
- When selected, new input for "Condition label" (more on that below)
- Include lightweight code input (not sure which existing code input we should use here or just style a normal input) for the JS expression
- Add a link to a Javascript Expression checker under the input (open to whatever online tool seems best!)

**Canvas:**
- When the "Matches a Javascript Expression" is selected, we will display a label on the path which takes the text from the "Condition label" instead of an icon.
- There needs to be a max width, followed by ellipsis (I feel 16 char is probably the right length)
- If ellipsis are displayed, a tooltip should be shown on hover of the element.

**Acceptance criteria:**
- [ ] Option displayed in drop down list for conditions is correct
- [ ] The edges following job always runs when matching the regular expression
- [ ] The label is displayed
- [ ] New features included in documentation 

Noting:
- Will use same input as the input dataclip
- Will do basic validation that the query is valid, and no typeahead.
- In future will move to Monaco

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1498?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc

**Comment by jyeshe** [comment]
> @stuartc pairing up with @jyeshe here to do the frontend UI

Magically I could manage the form yesterday. Missing the label on the workflow...
