### ISSUE TITLE
New workorder arriving on history page clears previous orders

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1517]
All other work orders disappear when a new work order arrives. This isn't the behaviour we want. Rather, we want to check to see if the "inbound" work order matches the filters and apply it if it does.

I think this [refactor](https://github.com/OpenFn/Lightning/commit/b8b2464ab80dddeb6129bb4d15d2bc480951e010?diff=split&w=0#diff-505fd6e66663185ea709cefb203e65dca8da3b7d0e1613b1dc1a778b82ca87ddL207) is what caused the bug and [this commit](https://github.com/OpenFn/Lightning/pull/1516/commits/0bdc0f1582a65725b5cdc2d3fd3d0e748ea51b69#diff-505fd6e66663185ea709cefb203e65dca8da3b7d0e1613b1dc1a778b82ca87ddL230) should fix it.

**Comment by taylordowns2000** [comment]
FYI @jyeshe , this is a very strange `handle_info` and I can see why you wanted to clean it up. Any suggestions are welcome for a better way to do it and to preserve the behavior in a unit test to prevent future regressions are welcome!

**Comment by jyeshe** [comment]
> FYI @jyeshe , this is a very strange `handle_info` and I can see why you wanted to clean it up. Any suggestions are welcome for a better way to do it and to preserve the behavior in a unit test to prevent future regressions are welcome!

Thanks for sharing @taylordowns2000 . The change was motivated by the async search but your implementation is more appropriate since by the time the work order is created the query is a very light one and it makes less confusing the inclusion of the new work order in the entries.

**Comment by taylordowns2000** [comment]
@jyeshe , is there a way to prevent the page from removing all the other work orders when a new one arrives but still using your async approach? (I'm entirely agnostic to the implementation here—i.e., I have no idea what I'm doing 😄—and only merged this to fix the bug!
