### ISSUE TITLE
Close the loop between History and Inspector

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1524]
**⭐️ Work on the `ux-for-admins` branch!**

When I'm debugging a work order in a failed state, I'd like to be able to click a button next to a run that failed and navigate instantly to the inspector with that work order, attempt, and run preloaded on the inspector.

Then, when I click Save & Run after editing my job code, I'd like a new attempt to be created for the existing work order, rather than creating a new work order.

To make this second bit possible, the inspector will need to be modified so that if an attempt is loaded, the user will have the option to either create a new work order or create a new attempt for the existing work order.

This will close out the basic debugging UX.

@midigofrank , note that I've built the UI for this in all cases except the history page expanded list link, but the buttons on the inspector view need _wiring up_. (And if there is a better way to do that select list, please feel free to improve my shoddy implementation.)

ToDo:
- [x] Link from history page expanded list to inspector with proper url params (add "inspect" text link next to "rerun" text link)
- [x] Link from attempt viewer to inspector (only when not already mounted inside inspector) to inspector with proper url params
- [x] Ensure that if no attempt is loaded OR if the dataclip differs from the inferred previous run, a new work order will be created. (See image 1.)
- [x] Add a new option for "Retry from here" on inspector that is available when an attempt is loaded and the selected dataclip matches the input_dataclip for the `run` that can be inferred by the combination of the current `attempt` and the `job`. Note that this allows the user to create a new attempt on existing work order rather than a new work order. (See image 2)
- [x] Ensure that the default run behavior is "Retry from here" when the conditions above are met.
- [x] Make the `control-enter` behaviour bind to the _main button action_.
- [x] Make a new `control-shift-enter` behaviour bind to the secondary action _if there is a secondary action_.

### Image 1 - When no attempt is loaded _OR_ `selected_dataclip_id != run.input_dataclip.id` for the `run` inferred by the combination of the current attempt and the current job.
<img width="1280" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/6511bac7-2935-4248-a848-8f2c8bb80457">

### Image 2 - When attempt is loaded _AND_ `selected_dataclip_id == run.input_dataclip.id` for the `run` inferred by the combination of the current attempt and the current job.
<img width="1678" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/fdd58ac7-737e-4df3-820d-22e5c75ef496">

Note that in this second image, the default behavior is to "retry from here" but the user can optionally still create a new work order via the menu.

**Comment by taylordowns2000** [comment]
@NickOpenFn , concepts:

This is when my mouse hovers over the inspect step icon:
<img width="1205" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/c060c5f8-34e2-45f4-9f16-095b0548148e">

This is the split button with a default behaviour:
<img width="1220" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/ee8d37b5-ac98-42c3-8cfe-1910bdd3a9f8">

**Comment by NickOpenFn** [comment]
@elias-ba 
As discussed for the "right for right now" logic: 
- If the Input changes or is being created, the button will reflect "New Work Order"
- If the Input is preloaded with an associated attempt, then the button will reflect "Retry from here"

**Comment by taylordowns2000** [comment]
there are two button/keybinding states:

(A) simple button: "Create New Work Order" (Cntrl+Enter)
(B) split button w/ dropdown: "Retry from here" (Cntrl+Enter) || "Create New Work Order" (Cntrl+Shift+Enter)

for testing:
- [ ] (1) goto canvas > step > enter a new dataclip: **A**
- [ ] (2) after clicking "Create New Work Order": **B**
- [ ] (3) after changing the input so the "left panel" dataclip `!=` the run.input_dataclip_id: **A**
- [ ] (4) after changing the input back so that the "left panel" dataclip == the run.input_dataclip_id: **B**
- [ ] (5) goto history > expand work order > click "inspect": **B**
- [ ] (6) change "left panel" input dataclip to "new dataclip": **A**
