### ISSUE TITLE
New credential doesn't appear in inspector until refresh

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1531]
Maybe related to https://github.com/OpenFn/Lightning/issues/791

Repro/explanation:
1. Navigate to a job panel for a job without an existing credential
2. Add a new credential for that job
3. Note that the credential has been created and it now appears in the select list on that job panel ✅ 
4. Click into the inspector view
5. Note that the  inspector says "No Credential" in the top left

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1531?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc
