### ISSUE TITLE
New Credential form shouldn't auto-complete

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/Lightning#1534]
When creating a new credential, the browser (I'm in Chrome) may auto-complete some values. These are almost certainly never going to be the right values.

In postgres for example, it asks for a user and password, and chrome is helpfully inputting those values from my local login. Which is never something I want.

![image](https://github.com/OpenFn/Lightning/assets/7052509/674f2932-f92f-45d7-afa1-ceaffbd65201)

While this is harmless it's a bit annoying, and perhaps a bit scary for users? Like we should be showing 100% confidence with our credential handling and the idea that Lightning is somehow magically filling in a password for me is a bit creepy. EVen if it's a) wrong and b) the browser's fault.

**To Reproduce** Steps to reproduce the behavior:

1. Open the new credential dialog (ie from the user profile menu in the rop right)
2. Select postgressql
3. If you have a username and password saved for localhost or demo.openfn.org or whatever, these values will autofill

**Expected behavior** 

Credential values should not be autocompleted.

**Additional context**

[MDN: Turning_off_form_autocompletion](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion)

**Comment by NickOpenFn** [comment]
Closing issue in lieu of the bigger fix: #1553
