### ISSUE TITLE
Critical: Creating a new job doesn't open the job panel

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1538]

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1538?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc

**Comment by elias-ba** [comment]
@NickOpenFn I am moving this to blocked, I couldn't reproduce the bug locally. Can you please add clear steps on how to reproduce it or help me do so ?
