### ISSUE TITLE
Workflows only support one version per adaptor

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/lightning#1563]
**_Note: this comes from a known issue in the runtime that will be fixed in https://github.com/OpenFn/kit/issues/268_**

### Bug Description

When running a workflow that contains two or more jobs utilizing the same adaptor but with different versions specified for each job, the workflow inconsistently uses only one version of the adaptor. This behavior contradicts the expected functionality, where each job within the workflow should independently use the specified version of the adaptor.

### Steps to Reproduce

1. Create a workflow with multiple jobs.
2. Set job 1's adaptor to `language-common@1.11.1`
3. Set job 2's adaptor to`language-common@1.10.2` 
4. Run the workflow and note the adaptor versions in each step.

### Expected Behavior

Each job in the workflow should independently use the specified version of the adaptor.

### Actual Behavior:

The workflow uses only one version of the adaptor, and all jobs within the workflow are affected by the version specified in the first job.

### Environment
This bug was discovered on [app.openfn.org](app.openfn.org)  **`v0.11.0`**. 

### Additional Information

Sometimes if you select a new adaptor for a job and almost immediately run the workflow, you will get an `Exception` error. And If your seeing a `Crashed` error, Most likely the job is failing because the adaptor version does not have the function that is used in that particular job 

### Attachments 
This is a screen-record of the bug using the `http` adaptor.

https://github.com/OpenFn/Lightning/assets/6592749/00431267-8751-4e4b-a165-cd6142b22cd7

**Comment by taylordowns2000** [comment]
Note that this will remain open until openfn/kit
