### ISSUE TITLE
Renaming in codebase to match new name "step" on UI

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1571]
Rename `Runs` to `Steps`
Rename `AttemptRuns` to `AttemptSteps`

Do _not_ rename `Attempts` to `Runs` as this is non-blocking and can only happen after this issue is closed. We'll track that second issue elsewhere, and it's lower priority than this one.

Next issue: https://github.com/OpenFn/Lightning/issues/1657

**Comment by NickOpenFn** [comment]
Placeholder for now - related to #1248
Want to ensure that the internal system reflects the UI so we don't have complications in terms of different names floating about.

**Comment by taylordowns2000** [comment]
needs some discussion:

## running stuff
```
v0.10: work order > attempt > attempt_run <> run
v2:    work order > run     > run_step    <> step
```

## building stuff

```
v0.10: project > workflow > job
v2: project > workflow > job (but we also refer to it as a 'step' in the UI)
```

note that “step” as used in the _UI_ is super contextual: if you’re looking at a workflow, step means the little boxes/jobs.
if you’re looking at a run, step means the instances of execution of those little boxes/jobs during this run.

**Comment by taylordowns2000** [comment]
given how expensive engineering work will get while this _isn't_ finished, i'd vote we put this at the top of the backlog as soon as @stuartc is back and we're 100% aligned on the names. as expected, we've already had a number of costly back-and-forth conversations and bugs related this one.

sheet with naming proposal: https://docs.google.com/spreadsheets/d/1CtFq5fwZ_UtZ7r7Kam96Ja_3ixVNpT0dal3_EClPyiM/edit#gid=0

**Comment by taylordowns2000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1571?planning-poker) with Zenhub @elias-ba @jyeshe @midigofrank @stuartc

**Comment by stuartc** [comment]
My advice here is to start with `Run -> Step`, break it via renaming/changing the module name.

Change the relationship names (while perhaps overriding the foreign keys value), and delaying the migrations as much as possible.
