### ISSUE TITLE
Consider how Sentry filtering works for errors that may contain credentials

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1600]
If a superuser enables Sentry error reporting they could report credential secrets via the error objects.

An example of this can be found here: https://openfn.sentry.io/issues/4463772292/?alert_rule_id=11218001&alert_type=issue&environment=prod&notification_uuid=e2fb2c20-6e7a-4064-89bc-7a8a51378641&project=6446500

While we can't omit given arguments for all `CaseClauseError` errors, we should still potentially expand protocol-level obfuscation... @midigofrank suggests rules for `inpsect()` around the `Credential` struct.

**Comment by taylordowns2000** [comment]
@NickOpenFn , just spoke with Joe here and he's re-opening this here: https://github.com/OpenFn/kit/issues/530

At the same time, this issue should be kept so that we implement a safe sentry module like in `v1` for lightning super users who set up instances and use Sentry.

**Comment by taylordowns2000** [comment]
ehhhh update, this is an elixir error, not the CLI. won't reopen https://github.com/OpenFn/kit/issues/530
