### ISSUE TITLE
Dashboard should display the total number of runs (old attempts)

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1610]
Runs count on dashboard displaying the total number of steps that have been executed, rather than runs.

It should be showing runs. If you "reset demo" on your local machine, you should see `1, 1, 1, 0` instead of `1, 3, 3, 0`:
<img width="1377" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/c7026309-1fee-42e4-984f-6f72cdd375d1">

**Comment by jyeshe** [comment]
For the time the feature was requested the Runs were a different entity.
