### ISSUE TITLE
Review Github sync process to include permission to add repo

### ISSUE THREAD

**Issue by jyeshe** [OpenFn/lightning#1649]
After clicking on `Install Github` when users don't have permission to add a repo to the list of repos for the Github App, they gonna be presented with this screen:

![Screenshot from 2024-01-19 10-52-04](https://github.com/OpenFn/Lightning/assets/44991200/b1c57947-7b5e-4a40-813a-4162969c1154)

However the selected repo won't appear on the select input immediately when redirect back to Lightning (permission should be given and maybe install done again):
![Screenshot from 2024-01-19 10-54-35](https://github.com/OpenFn/Lightning/assets/44991200/4a32b625-9c0c-4387-aed4-d6ce9943ed41)

So the process/documentation should be reviewed to consider this permission clearly in advance.

**Version number** 
v2.0.0-rc3

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** 

0. Setup GITHUB_APP_ID=379244, GITHUB_APP_NAME=openfn-dev and appropriate GITHUB_CERT.
1. Go to Settings->Sync to Github
2. Click on Remove connection and refresh if `Install Github` does not appear
3. Click on `Install Github` and select OpenFn. It should show the screen above to select the repos.
4. Choose a repo different from `demo-openhie` and click on `Update access`

**Expected behavior** 

It won't show the `demo-openhie` instead.

**Additional context** 

This was identified in the context of #1046

**Comment by christad92** [comment]
@midigofrank please can you confirm that this bug has been fixed in your work on #1046.

**Comment by taylordowns2000** [comment]
@christad92 , if this _hasn't_ been fixed, I'd recommend that we handle it after/during the GitHub stuff that's going in S3. (So if @midigofrank says it's not fixed and you agree, please move from S2 to S3.)

**Comment by taylordowns2000** [comment]
This will be resolved in #1895
