### ISSUE TITLE
Add and remove collaborators for project

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1701]
Note that we use the term "collaborator" for the model `project_user` which is a junction table (many to many) between `project` and `user`.

This feature will enable project collaborators with roles [`:admins` and `:owners`] to be able to add ore remove collaborators in a project and assign roles to them. 

There are two scenarios for adding a user to a project – new users and existing users. 

### Todos

- [x] #1836
- [x] #1837
- [x] #1835

Related to this: 

- [x] #753

**Comment by christad92** [comment]
Moved this back backlog as #1835 is not currently a priority for the short term goal - April 30.
