### ISSUE TITLE
Display scopes when viewing an Oauth2 credential

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1706]
Whether scopes are hard coded (`offline_access` and `refresh_token`) or optional (anything...) we should display which scopes have been granted when viewing a credential.

Test this by checking the Salesforce and Google Sheets credentials.

Note that Google Sheets only has hard-coded scopes and that Salesforce has a large set of optional scopes.

**Comment by christad92** [comment]
Hi @elias-ba as discussed, please see [attached](https://docs.google.com/spreadsheets/d/10pN-PsmcMFUbm0zZyu55ceU5lqkmS3oK1c608Z6_1UQ/edit#gid=0) for the list of scopes and much more readable names.
