### ISSUE TITLE
Editor: Update Adaptor documentation to show functions exported from `common`

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/lightning#1733]
### Description 
Currently the inspector editor only shows the docs for adaptor specific function, but it does not show the functions that are exported from common in that adaptor. For example `@openfn/language-http` exports the following functions from `@openfn/language-common`.
```
alterState, arrayToString, combine, dataPath, dataValue, dateFns, each, field, fields, fn, chunk, humanProper, lastReferenceValue, merge, scrubEmojis, sourceValue, splitKeys, toArray,parseCsv,`. But these functions are not displayed on the inspector editor
```

### Screenshot
![Screenshot 2024-02-09 at 7 18 06 PM](https://github.com/OpenFn/lightning/assets/6592749/e8080c8c-64a1-4aa2-a1dc-5cd161eb348e)

### Request in few words
Display the functions that are exported from `language-common` in all adaptors

**Comment by josephjclark** [comment]
I'm pretty sure we need to fix `describe-package` in kit before we can do anything about this. The flagship issue is https://github.com/OpenFn/kit/issues/197
