### ISSUE TITLE
Edits to an existing Credential do not save

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lightning#1740]
**Describe the bug** 
Edits made to existing Credentials do not save after clicking `Save` button.

**Version number** The version of Lightning you have seen the bug on.
I've replicated this on `v2.0.0` on both demo.openfn.org and app.openfn.org
**To Reproduce** Steps to reproduce the behavior:

1. Go to an existing Credential
2. Edit some of the details (e.g., change loginURL or password)
3. Click `Save`
4. Go back to the credential to see that the edits were not saving

**Expected behavior** 
Credential edits should save. 

**Screenshots**
See video: https://www.loom.com/share/d672d86172264ed09a2f7cf8ca60645d?sid=4c10d454-fdf3-4787-8f9e-348878388c0f
(Note that since the video I have also replicated this on app.openfn.org)

**Comment by taylordowns2000** [comment]
tracking in #1743
