### ISSUE TITLE
Unauthorized error when trying to log in with OAuth2 (Sign in with Google) on Lightning

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#1749]
This occurred on the production instance of lightning ([app.openfn.org](http://app.openfn.org/)) when trying to log in. I chose the External provider option instead of using username/password.  

The error in the network tab is a `401 Unauthorized error`.

**How to replicate:**

- From https://app.openfn.org/, try to login via an external provider and select a Google account. 
(Side note: it might be helpful to just rename the action button to Sign in with Google since that is the only provider we accept today)

Loom recording: https://www.loom.com/share/24efd8e40cb74f3383adceb5f6dd8be1

**Expected behaviour:**
User should be automatically signed in or led through an account creation process.

**Comment by taylordowns2000** [comment]
Noting that this was a problem with the client_secret in the superuser only setup section for a particular instance of lightning
