### ISSUE TITLE
Non-responsive workflow canvas after web socket disconnection

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#1750]
When the web socket connection on the workflow page reconnects (initial loss of connection is due to timeout/inactivity), the modal for editing the workflow paths and adapters becomes inactive. 

Phoenix triggers mount and update events when workflow steps/nodes is clicked. (see image) 
 

**To Reproduce** :

1. Go to 'https://demo.openfn.org'
2. Open any workflow or create a new one 
3. Open devtools and activate WebSocket debugging (type `liveSocket.enableDebug(true)` in the console) 
4. Click the adapters/steps to the see everything works normally
5. Leave the workflow and do nothing on it for 30 seconds
6. Repeat 5 and you'd see that the modals to edit the step or node is not being triggered.

**Expected behavior** 
After the web socket reconnects, I should be able to edit/configure the workflow. 

See video here: 
https://www.loom.com/share/693b660899694c328a952b7478a49f78?sid=d5839499-0276-40a4-a7ae-79c3f9058983

**Screenshots** 

Network tab showing how the web socket disconnects and reconnects every 30 seconds ![Image](https://github.com/OpenFn/lightning/assets/5230530/0b22e48a-f488-4972-9847-ae119745ffe2)

Screenshot of the workflow page and console tab where the mount/update events are triggered after reconnection. 
![Image](https://github.com/OpenFn/lightning/assets/5230530/ddc0be3c-06ee-4d59-bbfd-9e87af1450ae)

cc: @stuartc

**Comment by christad92** [comment]
[TODO] add loom video

**Comment by taylordowns2000** [comment]
Not taking this on now, but we've set up a design spike to make a way forward. All contributions are welcome.
