### ISSUE TITLE
Exports/Archives Model

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1763]
This is related to the #1698. 
Implement the model that supports export functionality on Lightning with a reference URL to a bucket that is configured.
- [ ] Ensure to add path to store the URL of the bucket (gcs://{{our_bucket}}/{{project_id}}/{{uuid of export}}.zip)
- [ ] `date_created`, `_id`, `status (:completed, :failed, :in_progress, :expired)`, `expiry_date`, `download_url`, `requested_by -> user_id`

In previous implementations the `retry` library is used to help with failures.

**Comment by christad92** [comment]
Delivered in #1698
