### ISSUE TITLE
Add support for MsGraph Oauth2

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1770]
Following the GSheets and Salesforce pattern, add support for an MsGraph Oauth adaptor.

This is a fairly standard Oauth flow: https://learn.microsoft.com/en-us/graph/auth-v2-user?tabs=http

**Comment by christad92** [comment]
A generic oauth pathway will not work for the Msgraph as the url requires a path param of {tenant} which is not required by most others.

**Comment by christad92** [comment]
The implementation of generic oauth (#1900) automatically makes this available.

**Comment by christad92** [comment]
Being delivered as part of #1900

**Comment by aleksa-krolls** [comment]
@christad92 flagging this does _not_ look delivered on app.openfn.org, but would be helpful for an upcoming migration project @daissatou2 is working on. 

I don't see Oauth enabled on the msgraph credential form
<img width="484" alt="Screenshot 2024-05-23 at 5 36 36 PM" src="https://github.com/OpenFn/lightning/assets/16758106/639a072a-8110-4dcd-b35f-0da13616c858">
