### ISSUE TITLE
Github Sync: handle case when no changes are made to app config

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1807]
What do we do when no changes are made to the github app config? Currently, if the user doesn't add or remove repo access from the GitHub app, it seems as though we're stuck. No possibility to go back to OpenFn or finish setup.

Figma Design: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=0-1&mode=design&t=eobMYaqLsuXYrOyB-0

**Comment by christad92** [comment]
I had a chat and session with Frank, please see notes below:

The two possible scenarios that result in this bug are:
- If there is an existing connection in lightning and you want to use it in another project. trying to connect two different projects to the same Github repo. 
- If the user accidentally remove the repo connection from lightning but it the installation is not removed from Github. leading us back to point 1. 

Proposed solution : 
- Giving users the permission to reuse the their github installations in different projects by creating a new model `user_github_installations` which can be connected to a multiple projects. With this approach, updating a project's project_repo_connections record does not is affect existing user installations.
- When a user removes a github installation  in `user_github_installation`, we will also uninstall the app from the Github account.
- We will only uninstall the app on Github when there is only one user connected to it on the `user_github_installations` model and is requesting an uninstall. 


@taylordowns2000 @stuartc It's be great to have your  thoughts on this.

**Comment by taylordowns2000** [comment]
This will be resolved in #1895
