### ISSUE TITLE
GitHub Sync should allow multiple projects per repo

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1811]
## Context

1. Right now, the "Install/Reconfigure Github Sync" adds a single set of workflows that use the openfn Github action to a target repository+branch.
2. To allow multiple repo<>project connections to be made in the _same_ repo (allowing for a common "`staging` to test" and "`main` to prod" pattern) we should modify the Lightning installation code, the workflows, and the Github actions.

### Modify PRC:
- [x] #1892 

### Modify OpenFn Github "actions"
- [x] Update the [gtihub deploy action here](https://github.com/OpenFn/cli-deploy-action/blob/main/action.yml) so that it can take a _variable_ `config.json`—the file that points to a `project.yaml` and to a `projectState.json`
- [x] Update the [github pull action here](https://github.com/OpenFn/cli-pull-action/blob/main/action.yml) so that it can take a _variable_ `config.json` also.

### Modify auto-generated workflows
- [x] Update the auto-generated [`pull.yml`](https://github.com/OpenFn/demo-openhie/blob/main/.github/workflows/pull.yml) so that it handles a specific BRANCH and allows the user to _either_ specify a path to an existing `config.json` or generates a `config.json` for the user which is named `project-name.json` and points to a `./project.yaml` and a `project-name-state.json`
- [x] Update the auto-generated [`deploy.yml`](https://github.com/OpenFn/demo-openhie/blob/main/.github/workflows/deploy.yml) so that it handles a specific BRANCH and allows the user to _either_ specify a path to an existing `config.json` or generates a `config.json` for the user which is named `project-name.json` and points to a `./project.yaml` and a `project-name-state.json`

<img width="1151" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/a7c36597-5269-4dd8-9fa0-d1997377025c">

## For validation
- You should be able to set up two different OpenFn projects "my-test" and "my-prod" and have them connected to the same github repository.
- You should see 4 workflows (two for "my-test" and two for "my-prod").
- You will add two different config files to your repo: `test-config.json` and `prod-config.json`. These config files will be referenced in the `pathToConfig` attribute of the `project_repo_connection`.
- When you initiate sync, you should see one `project.yaml` and two project state files: `my-prod-state.json` and `my-test-state.json`.
- On commit to the `staging` branch, you should see an update to the "my-test" OpenFn project.
- On commit to the `main` branch, you should see an update to the "my-prod" OpenFn project.
- When staging is _merged_ to the `main` branch, you should see that both OpenFn projects now have identical configuration.

![Image](https://github.com/OpenFn/lightning/assets/8732845/86d2dcd9-5f62-4d87-af86-e9606bdf2dad)

**Comment by christad92** [comment]
This is dependent on the solution to #1807 so we are moving it to blocked. 


discussion here: https://openfn.slack.com/archives/C021K98C273/p1709571111263229?thread_ts=1709551929.616269&cid=C021K98C273
