### ISSUE TITLE
Capture Changes on Workflows

### ISSUE THREAD

**Issue by stuartc** [OpenFn/lightning#1821]
- [x] Add the [carbonite](https://github.com/bitcrowd/carbonite) library to the application

**Create triggers for**

- [x] Workflows
- [x] Jobs
- [x] Edges
- [x] Triggers

- [ ] Ensure there is a carbonite transaction call for _all_ places where any of the above models are changed.

E.g.

```elixir
Carbonite.Multi.insert_transaction(%{meta: %{type: "workflow_created"}})
```

## Notes

Attempt to introduce Carbonite (and snapshots) in a way that doesn't require downtime, this may mean a deployment strategy that has the migrations ahead of the application changes.

Take note of superfluous records, we don't want change records lying around or getting into a snapshot that we aren't sure how (or when) they got there.

**Comment by stuartc** [comment]
Pausing this for now, moving onto #1822 to get a jump on how snapshots are created and shaped.

The use of Carbonite _might_ not entirely be necessary. There is a PR that is in a fair shape, but not 100% to my liking (#1944).

**Comment by taylordowns2000** [comment]
Closing as "wont fix" or "changed direction"
