### ISSUE TITLE
Additional fields on the salesforce oauth credential

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/lightning#1838]
### Description
Add support additional fields on the salesforce oauth credential. Eg `apiVersion`

### Additional context
In salesforce configuration schema, you have an option of setting `apiVersion`. This enable the salesforce client to use the specified `apiVersion` instead of the default one. [See salesforce configuration schema](https://docs.openfn.org/adaptors/packages/salesforce-configuration-schema#sample-configuration)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 need this to unblock wateraid testing next week
