### ISSUE TITLE
[DMP 2024] UX Redesign for Inspector

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#1840]
---
name: OpenFn
about: C4GT Issue: UX Redesign for Inspector 
title: "UX Redesign for Inspector"
labels: `UX`, `OpenFn`, `Inspector`
assignees: ''

---

## Description
The OpenFn platform is an open source tool for data and workflow automation which provides users with the two different types of interface: The CLI and Lightning -- a web based platform that provides a GUI/Canvas for users to design their workflows, write job expressions and run [work orders](https://docs.openfn.org/documentation/get-started/terminology#work-order). In OpenFn, users build high-level workflows visually, using a canvas interface seen in the image below.

![Image](https://github.com/OpenFn/lightning/assets/5230530/8bd85b5c-341b-4050-9bdd-022c40b79242)

Once the structure of their workflow is in place, they click into the “Inspector” (a “code editor”, or “IDE”) which allows them to access sample Inputs, use Adaptor Documentation, write Job Code, and Run their job code to view the Logs and various Inputs/Outputs of different steps in their workflow. Right now this interface uses a 3 panel view (Input, Editor, Output & Logs) and is suboptimal for a number of reasons: 
(a) it's unresponsive and displays poorly on small screens
(b) panel expansion/collapse is not natural, you’re always battling to get things where you want on the screen, 
(c) it’s hard to access and use the adaptor documentation, and 
(d) the output and logs interface is too cluttered.

**Current interface of the inspector**
<img width="1680" alt="Screenshot 2024-04-15 at 13 12 04" src="https://github.com/OpenFn/lightning/assets/5230530/1012cc40-c617-45c5-8e1e-81acb9f08e6d">

## Expected Outcome

A high fidelity design of a streamlined IDE, that makes use of panel-based design principles more common in tools like VS Code, allowing the user to fold out, pin, and resize panels more simply in a similar manner to interfaces like https://jsfiddle.net/ , https://codepen.io/pen/ , and https://code.visualstudio.com/ .

### Product Name
Product Name: OpenFn

### Project Name
Project Name: UX Redesign for Inspector

### Organization Name:
Open Function Group

### Domain
Other

### Tech Skills Needed:
Figma, User Experience Design 

### Complexity
High

### Category
UI/UX/Design

**Comment by KDwevedi** [comment]
comment
