### ISSUE TITLE
Github sync fails when trying to add specific repo and branch

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lightning#1845]
**Describe the bug** A clear and concise description of what the bug is.
[See video](https://www.loom.com/share/5c429a06612e4a32a45fcb563a6925cd?sid=910b0300-afae-41f2-b7e4-fed24c7ca301) of the issue. 
1. I've created a Github connection and authorized openfn to access this [water-aid repo](https://github.com/OPenFn/water-aid) (which is a private repo btw)
2. Now when in `Project Settings`> `Sync to Github` page, the repository and branch I pick never save: https://app.openfn.org/projects/477af5c0-cd79-4fa9-a0f5-34fb28a20b3c/settings#vcs

**Version number** The version of Lightning you have seen the bug on.
`v2.0.6` on app.openfn.org

I have reproduced this locally on main:
- [ ] Yes
- [ x] No

**To Reproduce** Steps to reproduce the behavior:
In [water aid australia project(https://app.openfn.org/projects/477af5c0-cd79-4fa9-a0f5-34fb28a20b3c/settings#vcs)...
1. Go to Project Settings and create Github connection
2. Authorize access to `water-aid` repo
3. Try to then pick the `water-aid` repository and `staging` branch on this page --> watch it not save

**Expected behavior** 
Github sync configuration should save :) 

**Additional context** 
This is a private repo... does that affect anything?

**Comment by taylordowns2000** [comment]
@christad92 , @midigofrank , check out sentry here. looks like the files aren't available on app? (docker image/build issue maybe?)

**Comment by taylordowns2000** [comment]
Reopening. Still not working. Something to do with `@github_assets_dir Application.app_dir(:lightning, "priv/github")` maybe?
