### ISSUE TITLE
Update UsageTracker submissions

### ISSUE THREAD

**Issue by rorymckinley** [OpenFn/lightning#1853]
Changes required:
- Track start of usage tracking being enabled (defaults to the date of the first run with tracking enabled) - clear the date when tracking is disabled.
- Grab data in buckets that correspond to days as measured in UTC - allow multiple buckets to be picked at a time, if clearing a backlog.
- Submit each day's worth of data using the V2 submission format.

**Comment by taylordowns2000** [comment]
@rorymckinley , can we close this?

**Comment by rorymckinley** [comment]
> @rorymckinley , can we close this?

@taylordowns2000 I still have one branch that I need to merge in related to this issue. It is a big cleanup of the usage tracking code to make it more idiomatic. The code is already done (except for dealing with the inevitable merge/rebase conflicts) so I have been holding off until the last functional usage tracking PR is merged in.

That last functional PR is the resubmission code for limited-connectivity scenarios and Roger is looking at it currently.

**Comment by rorymckinley** [comment]
Code passes muster, so closing this issue.
