### ISSUE TITLE
Error: "Credential was updated by another session. Please try again" when updating a project credential

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#1861]
How to replicate 
- Add a credential
- Attempt to update the credential e.g. version on Salesforce or token for facebook 
- You'll receive a toast notification with `Credential was updated by another session. Please try again` (See loom video)

 https://www.loom.com/share/f7389a405d014c57b2f8ecfcd1bdbf56?sid=953723dc-0f66-442c-9a2a-86130d20a319

Very related to #1795 

cc: @jyeshe

**Comment by christad92** [comment]
This issue seems to be reoccurring or could we have missed this the last time we fixed this? 

https://www.loom.com/share/01b95a8fa3214d11b8ebf65119acca51?sid=7dc571ee-fe9f-4854-a210-3261e1c25878

cc: @stuartc @jyeshe

**Comment by jyeshe** [comment]
> This issue seems to be reoccurring or could we have missed this the last time we fixed this? 
> 
> https://www.loom.com/share/01b95a8fa3214d11b8ebf65119acca51?sid=7dc571ee-fe9f-4854-a210-3261e1c25878
> 
> cc: @stuartc @jyeshe 

Added a quick fix here: #2017

If Sentry report continues we need a better fix that includes oauth tokens.
