### ISSUE TITLE
Crash loop: performance issues when loading large logs and (input and output) data clips

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#1872]
When inspecting jobs with the large logs and input/output data, there is a tendency for the system to become slow, laggy and in some cases, the **browser breaks** because of the volume of data being rendered. 

https://www.loom.com/share/eaf9474757bd49aa9225a68c8a2e9ae5?sid=d15555cb-5a2a-4a6c-906e-0b5b3304decc

**Comment by christad92** [comment]
https://www.loom.com/share/f40ed77eb2db4d4e99d0479d701a7024?sid=ba0facce-6afb-4139-9bcd-d167272948cf

This is a more recent example of this.

**Comment by christad92** [comment]
When inspecting a step with a large input/output data clip, the page takes a moment to load  and could possibly crash. See image below.

![Image](https://github.com/OpenFn/lightning/assets/5230530/eb242441-d855-4a1a-9779-9727e793689b)

**Comment by christad92** [comment]
How to replicate the latest issue : 
when I click back and forth between Input and Output, the page either is really slow to load or even crashes.
when I click into Output it says No output state could be saved for this run. what does that mean? when/why does that happen?
Then I try clicking the step E0 Get Donors CSVs from SFTP and it takes so long for the inputs/outputs for this step to load

**Comment by taylordowns2000** [comment]
@midigofrank , @stuartc , great to hear progress on this one.

I'd like to note that a key bit of UX should be preserved in this solution and it may be hard to accomplish if I understand your current thinking:
- When users go to look at a run with 40,000 lines of text, they'd like to be able to find a specific line using `control-f` in the browser or `control-f` in monaco.
- How can we ensure that if only 1,000 lines are loaded at a time, they're still able to find the line that contains the string `logging client id: aMidigoInAHaystack`

**Comment by taylordowns2000** [comment]
@midigofrank , standardizing all of our code interfaces (expression-editor, log-viewer, input/output-viewer, and input-creator) around Monaco feels like a win, anyway. Excited to hear how the spike here goes.
