### ISSUE TITLE
Cancelling a credential on a new node removes the whole node

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/lightning#1875]
In the workflow editor, cancelling a new credential will remove a newly created node.

Repro steps:

* Open the Workflow Editor
* Add a new node
* Click `new Credential`
* Cancel the new credential dialog
* The new node should vanish entirely

This is particularly annoying if you've carefully named your node and picked an adaptor etc.

**Version number** v2.0.6

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**Expected behavior** The new credential dialog should close, but my new node should still be visible with the input dialog open.

**Comment by christad92** [comment]
Quite related: https://github.com/OpenFn/lightning/issues/1882

**Comment by christad92** [comment]
Should be fixed by #2132
