### ISSUE TITLE
Canvas allows users to add steps while blue-loader bar is in progress, then deletes new steps once loading is done

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1881]
- Navigate to canvas on a slow connection
- Add step to workflow, click save.
- Add second step to workflow while the blue loader is in progress.
- Once the loader finishes, it will delete your second step.

https://www.loom.com/share/c8ea707d85b1494fbc19ca1d2cd4f365?sid=fc71964a-544e-4aed-b3dc-7b88890b68b7

**Comment by taylordowns2000** [comment]
@stuartc , another good one to illustrate canvas/connectivity issues

**Comment by christad92** [comment]
Might be fixed by #2007

**Comment by christad92** [comment]
To replicate, simulate poor connection by throttling your network to a slow 3G. Then add steps to your workflow with the canvas reloading (with the blue loader). You'll notice two things: 
- clicking on steps will not open the configuration modal
- saves doesn't work 
- error printed in console

**Comment by taylordowns2000** [comment]
@stuartc , is this possible fixed by/blocked by #2007 ?

**Comment by taylordowns2000** [comment]
closed for non-activity
