### ISSUE TITLE
Scrub secrets from run logs (2.2)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#190]
As a user concerned about security, 
I would like secrets to be scrubbed from run logs
So that users who are viewing the logs cannot see them and use them elsewhere

**This should be based heavily on secret scrubbing in `platform-app` - read that full implementation before beginning.** The departure from the platform-app implementation should be that we need a way for log lines to be emitted from enging with scrubbed secrets... otherwise it's easy to scrub them before loading a run log to the db and _hard_ to scrub them as they're streamed to the front end. (We don't have log streaming _yet_ on lightning, but we will.)

Create a CredentialService that can be called in the runner.ex to scrub secrets in (on_finish?) before a run is logged.

- [ ] Given a credential body, it should return a list of strings - the secrets found in that body.
- [ ] Given a string, replace secrets in that strings with ***
- [ ] when we've got a `safe_log` with the secrets scrubbed, display the run log

**Comment by taylordowns2000** [comment]
@stuartc , should this issue be updated/the approach changed because of #197 ?

**Comment by stuartc** [comment]
@taylordowns2000 Ummm, I'm not entirely sure it's necessary to do #197 first - technically the thing that persists logs should receive scrubbed values; so it may not be a blocker having to implement that before the scrubbing story.

I do need to have a think about scrubbing multiple lines (and also in a 'distributed' context), the design we're going for eventually is that _any_ instance can ingest log lines/emitted data from a worker. 

So I need to pay a little bit of attention to the structure of the genserver (no red flag here yet to be clear), however something to note is that if a given instance only sees say one line and a malicious job logs a credential splitting it with with say new line characters, I don't see how we can catch that mid flight. But I suppose this is an edge case I'm not convinced others have built solutions around either.

**Comment by amberrignell** [comment]
All elixir and based around the pattern that engine has. We need to figure out how to scrub log lines as they are emitted from engine. As we stream log lines to the front end we don't know how to scrub them - separate issue.
