### ISSUE TITLE
Generating project.yaml fails on certain projects

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1902]
We have at least two edge cases that are creating failures on the exporter/cli `openfn pull`:

## Duplicate Keys

This one was a known issue before, and we should likely solve it in the short term by enforcing unique names for all jobs in a project. I thought that this was done (maybe @elias-ba ?) a while ago, but apparently not.

![image](https://github.com/OpenFn/lightning/assets/8732845/05c6a4ac-8b5d-4822-b5d6-213efd43ce96)

## Not a map when no workflows exist.

<img width="1809" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/fda4d9bb-d260-453e-9b29-12bc82fbcd94">

When a user first sets up github sync (or runs `openfn pull`) on a newly created project (which is a part of the migration path) this error will occur because there are **no workflows** in the project.

```
Checking https://app.openfn.org/api/provision/*** for existing project.
Project found.
[CLI] ♦ Downloading the project spec (as YAML) from the server.
[CLI] ✘ ERROR: invalid spec
[CLI] ✘ [
  {
    "message": "workflows: must be a map",
    "path": [
      "workflows"
    ]
  }
]
```

<img width="678" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/79899a01-6f25-4838-a3eb-27c05687db94">

**Comment by taylordowns2000** [comment]
update here @stuartc , looks like this is _not_ a bug with the exporter. (see test below)
@josephjclark , we will need to update the CLI to accept cases where we try to import a project that does not yet contain any workflows. i'll investigate that side and open an issue

<img width="1440" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/c30bf7fe-3745-47e5-877e-287ed62fd0c4">

**Comment by christad92** [comment]
Closing this and opening #2494 to track the pending issue here.
