### ISSUE TITLE
Create credentials through a form (2.3)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#191]
As a user that is not familiar with json, 
I would like to create credentials via a form
So that I know exactly what I need to input

- [ ] Create a bodyschemas constant that has the body schema for all of our adaptors OR find a way to dynamically get the expected credentials for each adaptor (I think depending on our timelines it would be ok to hardcode for now)
- [ ] Create a credential form component that takes in the body schema for an adaptor credential and generates a form with the required inputs.
- [ ] On submit, the form should pass in the inputs to create a credential for the user. 

Edge case: 
if the body schema is a function (ex Google Sheets), use that.

How can we redesign this ? Can we dynamically get the expected inputs for each language package ?

**Comment by taylordowns2000** [comment]
The big question here is whether there is a way to allow users to _either_ create
1. a raw credential where they define keys and values via a simple interface. (this would be RE-USED for dataclips... in this sense, the only differences between credential body and dataclip body is that creds are encrypted and only visible for a single user)
2. a credential that is "linked" to a particular adaptor_version and displays all the necessary keys for that adaptor_version

This would save us having to maintain a list of credential types with bodySchemas.

If we go down the `#2` path, I'd want to consider how we extend existing adaptors with a `validate()` function which _both_ type-checks the provided `state.configuration` and attempts to login to a system with that config. This validate function (or the two functions that comprise it) would be used to define credential body schemas and to click a "test connection" button on a job step.

**Comment by stuartc** [comment]
@taylordowns2000 why not both? These seem mutually exclusive in their feature contribution..

**Comment by stuartc** [comment]
The 'holy grail' solution would be that the adaptors inform the app what schemas are available and the rules to apply, I'm not sure how we would go around that - not without building a fairly sophisticated runtime based form module. It would however completely decouple our FE from individual and custom deployments.

Re: 2. "adaptor or version bound credentials"

I like this, just based on the sense of comfort it may bring. I'm not sure how disconnected we can (reasonably) make our form system from our adaptors. Again keeping "data" like version and adaptor names in our codebase will require ongoing maintenance and redeploys for updates and changes for something that isn't directly related to the main functioning of Lightning.

**Comment by taylordowns2000** [comment]
closed in #223
