### ISSUE TITLE
Consider adding a GET route to webhook URL for testing (Dimagi)

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1929]
The Dimagi folks would like us to add a GET route for webhook URL "testing". When you click "test" on CommCare, it does not test by making a POST request (as the actual data forwarding feature does) it instead sends a GET request, and we reply with a 404.

![Image](https://github.com/OpenFn/lightning/assets/8732845/329d5528-1409-4f8b-a20b-c00e6507dfbc)

**Comment by christad92** [comment]
Closed in PR1959
