### ISSUE TITLE
Transfer credential ownership (2.5)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#193]
As an owner of credentials that are in use in several projects, 
I would like to transfer ownership to another user
So that they can access and edit credentials themselves if I leave the organisation 

- [ ] add a `transfer_ownership` function to the `credentials.ex` context which takes in a user and updates the `belongs_to` field to that user 
- [ ] add a 'transfer ownership' action to the credential_live next to show/edit/delete which redirects to transfer_credential_ownership.ex
- [ ] add transfer_credential_ownership.ex which displays a tooltip, a dropdown of users to select from (ids ? emails ?). When the user clicks 'transfer ownership' there should be a confirmation popup which says ("Are you sure? If you transfer ownership of this credential you will no longer be able to view or edit it yourself. "]

How do we handle share failures, for example if a user no longer exists (this technically shouldn't happen because the user is selecting from a dropdown of existing users)

**Comment by amberrignell** [comment]
If a user is in one project, and wants to transfer credentials to someone in another project, what happens ? We stop them and the error message says 'this credential is shared with projects that the recipient cannot access - please update settings accordingly'. 
credentials are the only thing in an instance that we are even hiding from the 'admin' who has deployed that database. The user of the credential can pass around or shift to any other user in that system. An error will be thrown.

**Comment by elias-ba** [comment]
@taylordowns2000 @stuartc @amberrignell are you guys sure the function `transfer_ownership` should go in the `credential.ex` module ? Why not in the `credentials.ex` module instead ?

Why do we need to have that function instead of just using the `update` function ?

**Comment by taylordowns2000** [comment]
@elias-ba , great catch:

1. `credential.ex` was a typo, i've modified it in the issue to display `credentials.ex`
2. your new function `transfer_ownership` will _use_ `update` under the hood, but the logic to check if we _can_ transfer a cred to a new recipient based on their might also live in there. (or it might live in the changeset validation.)

**Comment by elias-ba** [comment]
Very clear @taylordowns2000. Thanks

**Comment by elias-ba** [comment]
@stuartc have you seen 

> As an owner of credentials that are in use in several projects, I would like to transfer ownership to another user So that they can access and edit credentials themselves if I leave the organisation
> 
> * [ ]  add a `transfer_ownership` function to the `credentials.ex` context which takes in a user and updates the `belongs_to` field to that user
> * [ ]  add a 'transfer ownership' action to the credential_live next to show/edit/delete which redirects to transfer_credential_ownership.ex
> * [ ]  add transfer_credential_ownership.ex which displays a tooltip, a dropdown of users to select from (ids ? emails ?). When the user clicks 'transfer ownership' there should be a confirmation popup which says ("Are you sure? If you transfer ownership of this credential you will no longer be able to view or edit it yourself. "]
> 
> How do we handle share failures, for example if a user no longer exists (this technically shouldn't happen because the user is selecting from a dropdown of existing users)

@stuartc have you seen this discussion ? I wanna make sure it aligns to our discussion of this morning. What are your thoughts about the last two checkboxes of this comment.

**Comment by taylordowns2000** [comment]
closed in #223
