### ISSUE TITLE
Generate an audit trail for credential configuration (2.6)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#194]
As a Lightning administrator, 
I would like credential creation and edits to be tracked 
So that I can audit these in the event a credential change breaks a workflow

- [ ] set up papertrail? on the credentials table to know when a credential has been changed and by whom
- [ ] add a tab in admin settings that displays a list of these changes

Note:
1. we should be able to see _that_ the body of a credential was changed and by whom, but not the credential body itself as this is encrypted at rest

**Comment by amberrignell** [comment]
This is complementary to projects as code. Users want to be able to find out what was changed when in all aspects of a project. 

As we implement papertrail, we create a table called somehting like 'changes' and in that table we track 
- what changed (who)
- which user made the change (action)
- timestamp of the change (context/metadata)

We're not married to papertrail because we're nervous of modules that get between your database and your ORM... TBD.

**Comment by taylordowns2000** [comment]
I'm seeing a single table called `changes` with at least 4 columns

1. who changed it
2. when they changed it
3. what the resource is they changed
4. the changes

@stuartc is seeing a table _per_ resource (e.g., "credential changes") with similar columns

**Comment by amberrignell** [comment]
note - we may want to split this into 2 issues

**Comment by stuartc** [comment]
https://luizdamim.com/blog/tracking-changes-with-context-using-phoenix-and-ecto/
