### ISSUE TITLE
Enable users to sign up via the marketing website

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#1969]
Blocked by  OpenFn/thunderbolt#125 

We want users to be able to sign up and access the platform directly through the landing page by providing their email, password, first & last names as well as other relevant details required for marketing. 

To do this, we are exposing a REST endpoint that allows us to create a new user account from the landing page. 

- [x] OpenFn/thunderbolt#125 
- [x] OpenFn/lightning#2041
- [x] OpenFn/lightning#2023

**Comment by jyeshe** [comment]
@christad92 could you create the corresponding task on the umbrella app? 
Details needed: 
- parameters
- authentication

**Comment by taylordowns2000** [comment]
done
