### ISSUE TITLE
Store log lines in a separate table

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#197]
In order to deal with the future design of process based workers, and the asynchronous nature they have. It will be beneficial to store log lines as rows in a table.

A job/worker will be able to emit a log line (\n terminated or EOL) along with it's us (microsecond) integer timestamp.

This way, no matter which instance receives the log line, they can be queried in order.

**Comment by josephjclark** [comment]
Closing as duplicate of #514
