### ISSUE TITLE
Inconsistent loading issues on the settings page

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#1971]
The settings page should load and open with the setup tab active but currently that does not happen. The current behavior is inconsistent where in some cases it loads and in other situations it does not load and the user would need to manually click tabs to a section.

When this happens, there is a `tab selector tab_bar component missing data-panel-hash={tag}` error as seen in the image below. 
Console error:  

![Image](https://github.com/OpenFn/lightning/assets/5230530/e2acf81d-d224-46dd-bd88-ed63f16df98f)

See loom video below
Loom: https://www.loom.com/share/98222f8632f14eb8a974ed54976c7a34

**Comment by jyeshe** [comment]
Regression: It always takes you to to settings#project , even though your hyperlink has settings#collaboration
