### ISSUE TITLE
Add plumbing to fetch messages from a Kafka cluster

### ISSUE THREAD

**Issue by rorymckinley** [OpenFn/lightning#1978]

**Comment by christad92** [comment]
- [x] Restart the consumer group if the config changes (e.g. username/password) 
- [x] Generate consumer group IDs and make them immutable
- [ ] Handle failures in the Pipeline by logging errors with payload and sending errors to Sentry
- [ ] Clean up the message log used for deduplication by configuring the purge period in the ENV
- [ ] Allow users to be able to configure time-outs via the trigger setup
- [ ] Look at Ayodele's bug
