### ISSUE TITLE
Group jobs/steps by workflow

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#198]
As a user that is building out or viewing an integration, 
I would like to group my jobs by workflow AND give it a name
So that I can easily distinguish different workflows

(to discuss with Stu)

**Comment by stuartc** [comment]
I'll address some of the questions you posted on Slack here:

- We will need to add a `workflows` table, that has a label (intentionally different to a name, leaving room for a url safe string if needed).
- All jobs will need to belong to a workflow, so a `workflow_id` fk on jobs.
- I personally like the UI of a dashed or dotted border around a workflow, I believe other products use the same UI.
- I see there is some stuff around this in Figma, but I think we need to lock down the UX before further design - from a backend/model pov this is straight-forward. But _how_ a user goes around creating and editing a workflow is definitely the majority of the work here.
- We perhaps need to get the "Create Job" off of a Job/Node UX down, before we do this right?

**Comment by amberrignell** [comment]
closing as there is already an issue for this - https://github.com/OpenFn/Lightning/issues/239 
Have ported over Stu's comments
