### ISSUE TITLE
cli deploy from github actions fails with 403 when committing changes

### ISSUE THREAD

**Issue by midigofrank** [OpenFn/lightning#1995]
- The lightning endpoint returns 201. Changes from github are saved successfully
- The final step, to commit the saved changes from lightining fails with 403

Here's a github action job failing with the same reason: https://github.com/midigofrank/openfn/actions/runs/8732560780/job/23959899762

**Comment by christad92** [comment]
@midigofrank this might be related. I am getting an "internal server erorr" when openfn deploy is initiated from github to lightning. 

see logs here: https://github.com/christad92/github_sync/actions/runs/8740999048/job/23986702923

**Comment by christad92** [comment]
There's chance.. will investigate and let you know.
