### ISSUE TITLE
Jump to steps on a different branches (i.e., merge)

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2008]
When building a workflow, user want to be able to reuse a step that has been created in a different branch. For example when a workflow has a series of steps to manage an error can be designed so that it can be reused instead of being duplicated or when a user wants to skip some steps in a workflow.

 - [x] Implement the UI for connecting two steps by dragging outputs to inputs with validations (see rules)
 - [x] Allow downstream jobs to handle throughput of input state from other steps

Rules: 
- Disable cyclical flows/branches i.e. A branch should not go upstream on its path thereby causing loops

Designs: https://www.figma.com/file/4hGWdO4sajnjcOwE81j8BK/App-(new)?type=design&node-id=4253-739&mode=design&t=dtwY2FmzuHXrL4hY-0

How users currently manage this: 
- duplicating the step
- creating a step that calls a different workflow via webhook (see below)

![Image](https://github.com/OpenFn/lightning/assets/5230530/24c25db7-dc24-43f8-825e-86c5b1ca19f2)

https://www.loom.com/share/45396a36dc4345c9bce3b41b896eaffa

**Comment by stuartc** [comment]
https://reactflow.dev/examples/nodes/add-node-on-edge-drop

**Comment by stuartc** [comment]
![Image](https://github.com/OpenFn/lightning/assets/144796/676a690c-d411-4a31-9b76-a23e0d291cef)

**Comment by josephjclark** [comment]
implementation notes:

* don't autolayout on edge creation
* add a toolbar on the chart with zoom and layout controls
* cross fingers on dagre
