### ISSUE TITLE
Update default comment in job editor to help users get started

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2014]
Currently new users get lost on the editor page when they as they don't know which language to code in or how to organize their code. Templates is an expensive way of solving this so we are adopting a much simple approach of adding multiline comments to  users know what to do. 

```
// Use pure JavaScript to add operations to your
// step. Click Docs to see list of operations or visit
// https://bit.ly/OFNJWG for adaptor documentation
// and example job codes.
```

**Comment by jyeshe** [comment]
would add also this snippet:
```
fn(state => {
  return state
})
```
It's elegant but it's exactly the same as js arrow functions:
`const greetings = (a) => {return console.log("Hello " + a)};`
