### ISSUE TITLE
OpenID Connect compliance (5.1)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#204]
As a systems administrator for a government
I want to manage user access to OpenFn via an OpenID Connect compliant provider, such as Google, Github, KeyCloak, etc
So that users don't need to create a new username/password for OpenFn

- [x] look at open source implementation of OIDC
- [x] create keycloak provider for testing
- [x] build authentication via openid connect module in lightning that allows an administrator to _configure_ different openID connect providers when deploying lightning.

The admin who's setting up Lightning should be able to add various IAM options: (1) native user/pass; (2) Google Auth, (3) KeyCloak, (4) Github, (5) etc.

We'll implement keycloak for testing, but may implement Google Auth and GitHub for demo.openfn.org

**Comment by amberrignell** [comment]
Our safe goal is that we put in place the structure that would allow another developer to implement their own OIDC. 
Stu has already done an implementation with Keycloak. 
We'll have a system settings table, then when you go into the admin section you choose the provider (OIDC keycloak). On save, it saves it to the database so that the login screen behaviour changes.

**Comment by taylordowns2000** [comment]
concept art based on metabase!

![Image](https://user-images.githubusercontent.com/8732845/180212601-191facb8-e31a-4b29-8e85-c32461891a27.png)

**Comment by stuartc** [comment]
- [x] Backend modules/functions to query a well-known.
- [x] Authenticate and callback endpoint can log you in.
- [ ] Error feedback on login failure
- [x] Can test and validate a new provider
- [ ] Persist the provider
- [ ] Add 'Oauth' button on login page
- [ ] Code cleanup

**Comment by taylordowns2000** [comment]
@amberrignell , this will be on `main` for your reivew at demo.openfn.org. please close or request changes as needed!
