### ISSUE TITLE
Make signup feature configurable

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2049]
We should enable OpenFn deployment to enable/disable new user sign up on their platform. Currently this is set to happen by default and anyone can sign up from app.openfn.org. A fix to consider here will be making this configurable via the ENV so that when disabled, the signup text/link and route will be disabled on Lightning.

**Comment by taylordowns2000** [comment]
100% agree here. Please ensure to add the ENV to the deployment guide and the example ENV. It should go near the `INIT_PROJECT_FOR_NEW_USER` variable.

**Comment by christad92** [comment]
@elias-ba please note Taylor's comment ☝🏻
