### ISSUE TITLE
tabselector error in editor page

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2051]
1. we are getting all sorts of weird stuff happening with tab selectors.
2. it may be related to the `mutator`?
3. we've removed the mutator entirely from the "settings" page [since it broke that interface](https://github.com/OpenFn/lightning/issues/1971) and was not in use there. (get the snake out of the house first, then figure out how it got in and what makes a snake a snake in the first place 🤔 )
4. in addressing this issue, we might consider refactoring the tab selector and/or mutator stuff so it's a better fit for where and how we want to use it.

https://www.loom.com/share/d896838fb5e742f2bf17e503d9153a9e?sid=ea353e7d-2309-4657-bef7-b9b3a11c6826

**Comment by taylordowns2000** [comment]
maybe related to #1971

**Comment by taylordowns2000** [comment]
we now have 3 bugs that all seem related:
https://github.com/OpenFn/lightning/issues/1971 - project settings wont load
https://github.com/OpenFn/lightning/issues/2051 - tab selector bugs
https://github.com/OpenFn/lightning/issues/2064 - input/output tabs get duplicated (which Elias now also sees on the project settings page)

**Comment by taylordowns2000** [comment]
please talk to @jyeshe before picking this up, as he may be addressing it on #2064
