### ISSUE TITLE
Reset demo failing

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2063]
On `v2.4.5` the demo server nightly reset is failing. Looks related to `Lightning.Projects.create_project` or `Lightning.SetupUtils.create_openhie_project`.

Logs from `Lightning.Demo.reset_demo` below:

```
2024-05-08 00:01:53.327 GMT
Unable to use a TTY - input is not a terminal or the right kind of file
2024-05-08 00:02:00.227 GMT
** (ArgumentError) unknown registry: Oban.Registry
2024-05-08 00:02:00.227 GMT
    (elixir 1.16.2) lib/registry.ex:1400: Registry.key_info!/1
2024-05-08 00:02:00.227 GMT
    (elixir 1.16.2) lib/registry.ex:590: Registry.lookup/2
2024-05-08 00:02:00.227 GMT
    (oban 2.16.2) lib/oban/registry.ex:59: Oban.Registry.lookup/2
2024-05-08 00:02:00.227 GMT
    (oban 2.16.2) lib/oban/registry.ex:32: Oban.Registry.config/1
2024-05-08 00:02:00.227 GMT
    (oban 2.16.2) lib/oban.ex:614: Oban.insert_all/3
2024-05-08 00:02:00.227 GMT
    (lightning 2.4.5) lib/lightning/projects.ex:188: Lightning.Projects.create_project/1
2024-05-08 00:02:00.227 GMT
    (lightning 2.4.5) lib/lightning/setup_utils.ex:285: Lightning.SetupUtils.create_openhie_project/1
2024-05-08 00:02:00.227 GMT
    nofile:1: (file)
2024-05-08 00:02:00.312 GMT
command terminated with exit code 1
```

<img width="1597" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/e3c41994-bbef-4b8f-84bf-36ad2620b87d">

**Comment by jyeshe** [comment]
There is no module calling `Lightning.Demo.reset_demo` on the App so the call comes from a shell/pod process.
Cannot reproduce calling iex remote shell, `reset_demo` can be called multiple times. 

There is this strange error `nofile:1: (file)` so it's worth to update the `runtime.exs` of the umbrella app with proper Oban and remaining config to reflect Lightning one.

Besides that, running the `Lightning.Demo.reset_demo` on staging would be helpful.
