### ISSUE TITLE
Internal server error when clicking "cancel" on User Profile page

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2067]
**Describe the bug**

Internal server error when clicking "cancel" on User Profile page

**Version number**

`v2.4.6`

I have reproduced this locally on main:

- [ ] Yes
- [x] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to your user profile
2. Click on the top "cancel" button under the change password form.
3. See error

**Expected behavior** A clear and concise description of what you expected to
happen.

Go back to dashboard

**Comment by christad92** [comment]
Sentry Log: 

#### UndefinedFunctionError
function LightningWeb.SettingsLive.Index.__live__/0 is undefined (module LightningWeb.SettingsLive.Index is not available)
