### ISSUE TITLE
Issue with the database URL when deploying with docker

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#208]
Current: 
- Run docker command (`docker compose run --rm web mix ecto.migrate`)
- Get error: "Invalid hostPort: 4000}"
- Change url in [docker-compose file](https://github.com/OpenFn/Lightning/blob/main/docker-compose.yml#L47) to hardcode the PORT value
- Run docker command again
- Get error: "invalid url "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}", host is not present"
- Hardcode those values and run command again
- Still getting an error: invalid url "postgresql://hello:password@postgres:5432/lightning_dev", host is not present

Expected: 
Run the docker command, navigate to localhost/4000 and see lightning up and running

I think it might be an issue with parsing environment variables and templating, but I'm confused as to why I still get an error when the values are hardcoded ...

**Comment by NickGowdy** [comment]
Hey @amberrignell 

I had similar issues yesterday following your steps. I then went to the contributing section of the readme and that worked straight away. It's unclear to me which steps should be followed for someone cloning the project for the first time.

**Comment by taylordowns2000** [comment]
@NickGowdy , thanks for posting! I know that @elias-ba is working on fixing the `docker-compose.yaml` and the `README.md` right now. Will ping you when this is sorted out :-)

**Comment by taylordowns2000** [comment]
@NickGowdy , quick question: are you running on an Apple M1? We've got a build [issue](https://github.com/OpenFn/Lightning/issues/119) there related to https://github.com/jayjun/rambo/pull/13 - if so, let me know and I can provide a workaround.

**Comment by NickGowdy** [comment]
> @NickGowdy , quick question: are you running on an Apple M1? We've got a build [issue](https://github.com/OpenFn/Lightning/issues/119) there related to [jayjun/rambo#13](https://github.com/jayjun/rambo/pull/13) - if so, let me know and I can provide a workaround.

No, I'm using one of the older MacBook Pros with an Intel CPU.

**Comment by taylordowns2000** [comment]
OK, so we're caught in two minds and maybe you could let us know your preference @NickGowdy ! 🙏 

Context:
1. Right now, the `Dockerfile` builds an image that's optimized for [Dockerhub](https://hub.docker.com/repository/docker/openfn/lightning) and our Kubernetes deployments.
2. The way that our day-to-day developers work with the app is by creating their own postgres DB however they like (as most already have postgres on their machines) and then following the `asdf install` steps to set up Elixir and Erlang on their local machines as outlined in [Contributing](https://github.com/OpenFn/lightning/#contributing).
3. I really like the idea of having an example `docker-compose.yaml` file and a single-shot command (`docker compose run --rm web mix ecto.migrate`) that sets up postgres and lightning for a new developer... but I'm also realizing that having a single-shot docker command isn't necessarily the greatest development experience. (I'm not a docker dev guy, but how would you watch/automatically-reload changes to the files you're working on in the browser? Would you need to rebuild that image each time you made a modification?)

So, given the above and your level of familiarity with Elixir/Erlang, would you rather:

1. Do your development inside Docker?
2. Do your development on your host machine with Elixir and Erlang installed via `asdf install`?

I think we should strive to make _both_ pathways clear and easy for developers, but right now it seems we've broken pathway `#1` for the sake of optimizing the _running_ of these automatically built-and-shipped-to-Dockerhub images and all we're left with is `#2`.

@elias-ba is spiking this right now, seeing if he can get a develop-inside-docker pathway working that doesn't impact our production `Dockerfile` builds, but I'd also love to hear your thoughts on how you'd most like to work with the software locally if you'll be contributing.

Thanks in advance for your input! Super exciting to have you checking out the repo. ❤️ 

cc @amberrignell

**Comment by NickGowdy** [comment]
Hey @taylordowns2000, 

> 2. The way that our day-to-day developers work with the app is by creating their own postgres DB however they like (as most already have postgres on their machines) and then following the asdf install steps to set up Elixir and Erlang on their local machines as outlined in [Contributing](https://github.com/OpenFn/lightning/#contributing).

This is how I worked on my last Elixir project. I used docker to host the database (which was also postgres) and then use `iex -S mix phx.server` so I could make changes and recompile.

I think with some tweaking we could make it easier to host lightning locally via docker. I'm also not a docker dev. I spent some of my afternoon playing around with our setup and reading the docs. I did some steps that helped me progress a bit.

- I upgraded Docker desktop and upgraded docker-compose to a newer version. I wasn't sure if the errors I were seeing was because of my local machine or something else.
- ` tty: ${TTY:-false}` isn't valid yaml so I hard-coded it to `false` for now.
- I was then getting the error: `failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: target stage dev could not be found`. In our dockerfile:
```
ARG ELIXIR_VERSION=1.13.4
ARG OTP_VERSION=24.2.1
ARG DEBIAN_VERSION=bullseye-20210902-slim
ARG NODE_VERSION=16.15.1

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} as builder
ARG NODE_VERSION
```
It's expecting the name `builder` but we pass in the mix environment like so with `target: "${MIX_ENV:-dev}"`

```
build:
    context: "."
    target: "${MIX_ENV:-dev}"
    args:
      - "MIX_ENV=${MIX_ENV:-dev}"
      - "NODE_ENV=${NODE_ENV:-development}"
  depends_on:
    - "postgres"
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: ${TTY:-false}
  volumes:
    - "${LIGHTNING_VOLUME:-./priv/static:/app/priv/static}"
```
I hard-coded our dockerfile to use dev which built the image, but when running `docker compose up` I was getting another error.

Anyway, it's really exciting to be contributing to your project.

**Comment by taylordowns2000** [comment]
This is great, @NickGowdy , and thanks for the work you're putting in. I've got a proposal going over on #213 , but for the time being I think we should at least update the README to point external contributors to the mix/IEX up & running section... if they're looking to help out they'll probably already have some sort of Elixir/Erlang (and hopefully Postgres) experience.

**Comment by taylordowns2000** [comment]
@amberrignell , is this still an issue for you?

**Comment by taylordowns2000** [comment]
closing as this doesn't seem to be a problem anymore
