### ISSUE TITLE
Ironing out Generic Oauth before full release

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2102]
- [ ] ~#2100~ (edit, moved to new issue)
- [x] put the "create credential" option ON TOP of the "create client" option in the dropdown. (it is what 99% of people will do.)
- [x] mark the "create client" option as `(advanced)` in the dropdown
- [ ] #2114
- [x] #2104
- [x] remove the "not working?" prompt. it's really confusing. i'd recommend only showing it once you come _back_ to a previously saved credential, if that's possible, and then say, "All good, but if your credential stops working, you may need to re-authorize **here**."

- [x] #2105
- [x] Refresh token before sending to worker
- [ ] #2113
- [ ] ~Adaptor /Step  configuration form dies after 10 seconds and the page refreshes. you lose your work (likely NOT introduced here, already on main? if so, please track this in a NEW issue @christad92 )~ edit, tracked on: #1882 and #2007

<img width="747" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/272e15c4-a57d-4baa-b8f4-16f264d16564">

**Comment by christad92** [comment]
@taylordowns2000 I am not seeing the duplication of clients on my end and I've been able create credentials on my end. 

On docs, we will have a draft ready for clients and creating credentials from clients. 

Not clear about others.

**Comment by taylordowns2000** [comment]
all tracked individually, closing
