### ISSUE TITLE
Users don't know why credentials are broken

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2135]
Right now, it's super hard for users to figure out _why_ their shiny new OAuth2 credential isn't working. The runtime/logger have already been extended to provide an interface through which we can report errors. Now we need to handle, sanitize, and send the errors we get when trying to refresh a token to the logger.

Use the `credential-error-for-worker` branch and this [draft PR](https://github.com/OpenFn/lightning/pull/2086)

**Comment by christad92** [comment]
@stuartc and @elias-ba to meet with @josephjclark  to discuss this further.

**Comment by taylordowns2000** [comment]
Hey @stuartc and @elias-ba , what's the additional context you need here? The interface on the worker is defined in `@openfn/ws-worker@1.1.9-pre`

https://github.com/OpenFn/lightning/issues/1842#issuecomment-2110272907

**Comment by taylordowns2000** [comment]
@stuartc , @elias-ba , what additional detail do you need here?
