### ISSUE TITLE
Credentials page doesn't show the side menu

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#214]
There's no side menu when the user navigates to "Credentials". There should be!

![image](https://user-images.githubusercontent.com/144796/180768371-c8823966-2540-48b2-99bf-01908334804e.png)

**Comment by taylordowns2000** [comment]
Tricky. We don't have a non-project-scoped, non-admin-user side menu yet. Presumably this would contain "profile" and "credentials", yeah?
