### ISSUE TITLE
Improve error messaging on CLI by specifying job names/edges  in error messages

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2140]
When using openfn deploy  in the CLI to migrate projects, users sometimes get back error messages on incorrect job names and edge condition labels, etc .

 **It would be super valuable to be able to see which job name and edge condition the error is related to** without having to manually go through have 200+ jobs. 

This is NOT a priority but would be important to have at some point.

It would be great if we can format error messages like `workflow-1/job-3: invalid character in job name`

example incorrect job name: `Fetch & upsert` 
(containing special character except for `-`)

**Comment by midigofrank** [comment]
@josephjclark will the cli still make a request to the server if the workflow and job names are missing from the yaml?
Without the names in the params, the backend won't be quite helpful either 😬

**Comment by josephjclark** [comment]
@midigofrank This isn't so much about missing names

Lightning is already running a bunch of validation in `lib/lightning/workflows/job.ex :: validate()`. Stuff like checking what characters are in the name string, ensuring an adaptor is set.

We just need to append some kind of pathing information into the message.

Maybe check this slack thread for a bit more [context](https://openfn.slack.com/archives/C0394D0GBUN/p1715879917307829)

**Comment by midigofrank** [comment]
@christad92 I haven't been able to format the error messages as in the description. What I have been able to do is group the error messages based on the `workflow/job/trigger/edge` name. For example:
**Previous**
```json
{
  "errors": {
    "workflows": [
      {
        "jobs": [
          {
            "body": ["Code editor cannot be empty."]
          }
        ]
      }
    ]
  }
}
```
----------------
**NOW:**

```json
{
  "errors": {
    "workflows": {
      "default": {
        "jobs": {
          "first-job": {
            "body": ["Code editor cannot be empty."]
          }
        }
      }
    }
  }
}
```

Can this suffice?

**Comment by midigofrank** [comment]
As for edges, the key will be `source_job->target_job` as it is in the yaml file

**Comment by josephjclark** [comment]
@midigofrank I think this will be fine. I'll try and test against this against your branch and comment in the PR
