### ISSUE TITLE
Improve error handling and messaging for GitHub Integrations

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/lightning#2156]
**Describe the bug** 
When setting up a GH connection for a project for the first time with an installed repo, and selecting the org, repo and branch on OpenFn, I get the error `Oops! Could not connect to Github`. OpenFn doesn't tell me what the error is, so I can't troubleshoot it and have to reach out to the product team to investigate.

After troubleshooting with Ayodele and Taylor we've found that admin privileges would have been need to the GH repo which I didn't have. After being granted admin privileges, I could connect the repo. 

**Version number** The version of Lightning you have seen the bug on.
 `v2.5.2` 

I have reproduced this locally on main:

- [ ] Yes
- [ ] No

**Screenshots** If applicable, add screenshots to help explain your [problem.]
![gh connection error](https://github.com/OpenFn/lightning/assets/7283134/1d9034c6-76ae-4019-9a8f-8f1df7729d19)

https://www.loom.com/share/1770f6c80aa247ad9e3c3e39cbe4db96?sid=0221fc08-e2b1-4ffa-83de-c07ac610c94c

**Comment by christad92** [comment]
The original issue was related to branch protection rules in the repository which prevents commits without PRs. GitHub allows admins to bypass the rule for specific users/apps. 

We should update the GitHub docs to guide bypassing branch protection rules. @ritazagoni. 

https://github.blog/changelog/2022-05-17-consistently-allow-github-apps-as-exceptions-to-branch-protection-rules/
