### ISSUE TITLE
Unable to disconnect/reinstall github app from lightning after uninstalling directly from Github

### ISSUE THREAD

**Issue by midigofrank** [OpenFn/lightning#2168]
**Describe the bug** If you uninstall openfn github app directly from github, you get stuck in lightning. You can't disconnect and you get no installations listed in the project settings page

**Version number** v2.5.3 (1.0.11)

I have reproduced this locally on main:

- [ ] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:
1. Go to one your project's settings and connect to github. Ensure you install it to an Org. Don't save the github connection(branch ..), just leave it after installing successfully. Check that you have installations listed
3. Go to Github on another tab and uninstall the OpenFn app from your account
4. Go back to lightning on your project settings and refresh the installation list. You'll notice that it's empty.
5. If you visit your profile and try disconnecting from github, nothing happens

**Expected behavior** We should provide a way to have the user re-install the github app

**Screenshots** If applicable, add screenshots to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by taylordowns2000** [comment]
maybe fixed by #2390
