### ISSUE TITLE
Branching edges(paths) should not connect to workflow triggers

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2188]
We need to block users from connecting orphaned steps to the workflow trigger. When this happens, the workflow rejects every change to that step 
What a workflow looks like when a job is attached to a trigger.
![Image](https://github.com/OpenFn/lightning/assets/5230530/ea0806a8-6f16-4240-89c1-fe891cf8325f)

After connecting the step to the workflow trigger, if I try to save changes, it returns an error "Workflow could not be saved" but I am not sure why I can't save the workflow.  See images below

![Image](https://github.com/OpenFn/lightning/assets/5230530/3f729400-d36a-4f62-8f79-bfc1af453758)

![Image](https://github.com/OpenFn/lightning/assets/5230530/0642b82b-8024-4d75-8970-98ff02290ba1)

**Comment by josephjclark** [comment]
Ah that's a really easy fix!

In `useConnect.ts`, just add an extra test in `getDropTargetError`. Something like if the target is of type trigger
