### ISSUE TITLE
Data stores, Collections, and Buffers

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2190]
We want to add the ability for Job code to be able to access a common datastore during execution.

The current proposal is that we leverage our existing postgres database, but must remain eagle eyed on performance implications as most of this data will _not_ be indexable.

This will require work on both Lightning and the worker code.

## Worker

- Needs to be provide an interface for all execution environments for:
    - building queries
    - handing over queries to parent/other process for invocation
    - sends the Runs token to Lightning
    - receiving streaming responses from Lighting
- *TBD* Write a spec for the query interface
- *Needed* links and plans for the worker

## Lightning

- Will have an HTTP API/Controller for handling requests for collections that:
    - Is authenticated via a run token
    - Calls functions to execute queries
    - Streams them back out
- A Collections context that:
    - Parses and validates queries from the worker
    - Has a query handler that can execute queries using Ecto dynamic.
    - Returns a stream of records
- An interface for creating collections
    - Collections will be project scoped
    - *TBD* Where would this interface be and who can use it?
    - *TBD* Will users be able to view, query or manage the data from the get go?

## Grouped Deliverables

This is a rough bounding of features we can take on individually:

### Job

1. Provide a JS interface that is available during runtime for all Jobs.
2. Figure out how to make an async iterator over a cross process message
### Worker

1. Make an authenticated query to Lightning
2. Expect a streaming response so results can be dispatched to the Job before all of them arrive.
### Controller

1. Phoenix controller that can authenticate using a Run token
2. Enforces the scope of the query using the token.
3. Calls out to the Collections context for execution of the query
4. Returns a stream of items.
5. Ensures that the streams are batched and limited.
### Collections

1. Design a datastructure
2. Add said tables
3. Add the Collections context module
4. Define the shape of query parameters that the worker will use
5. Decide what clauses we want to support
6. Cast the params, validate them and execute a query that returns a stream.

### Still TBD

1. Limitations, we don't want massive JSONB items being stored in the DB, rather lots of smaller items.
2. Consider expiration of records
3. How can we build guardrails into the delete functionality?
4. Mutation/push/insert/update
5. Who gets to create collections
6. What is the appetite for a UI that does one or more of:
    1. Creating and deleting Collections
    2. Creating or deleting records
    3. Viewing records
    4. Deleting records

```mermaid


flowchart TD

  

subgraph Collections

H([Collections<br/>Cast query into Ecto query]):::yellow

I([Collections<br/>Execute query]):::yellow

end

subgraph API

D([Controller<br/>Authenticates using Run token]):::blue

E([Controller<br/>Passes query to Collections]):::blue

F([Controller<br/>Serialize stream into JSON]):::blue

G([Controller<br/>Send streaming response<br/>back to Worker]):::blue

end

  

subgraph Worker

J([Job<br/>Makes a call to collections]):::green

A([Worker<br/>Receives query call]):::red

B([Worker<br/>Makes call to Lightning]):::red

C([Worker<br/>Marshal records back to Job]):::red

K([Job<br/>Receive records and present<br/>async iterator]):::green
end

  

J --> A

A --> B

B --> D

D --> E

E --> H

H --> I

I --> F

F --> G

G --> C

C --> K
  

%% Define color styles

classDef blue fill:#1E90FF,stroke:#000,stroke-width:2px;

classDef red fill:#FF6347,stroke:#000,stroke-width:2px;

classDef yellow fill:#FFD700,stroke:#000,stroke-width:2px,color:#000;

classDef green fill:#15803d,stroke:#000,stroke-width:2px;
```

**Comment by stuartc** [comment]
@jyeshe @josephjclark I've updated the issue description for you guys to take a look and think before we chat next.

**Comment by josephjclark** [comment]
@stuartc any thoughts on expiration of records? Data retention stuff? A burn after reading option?

**Comment by josephjclark** [comment]
We can close this right?
