### ISSUE TITLE
 No such directory: ./priv/openfn

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/Lightning#225]
## Description 
When running `env $(cat .env | grep -v "#" | xargs ) iex -S mix phx.server` i am getting the error below

 ```
(Mix) Could not start application lightning: Lightning.Application.start(:normal, [:timex]) returned an error: shutdown: failed to start child: Engine.Adaptor.Service
    ** (EXIT) an exception was raised:
        ** (RuntimeError) No such directory: ./priv/openfn
            (engine 0.7.2) lib/engine/adaptor/repo.ex:22: Engine.Adaptor.Repo.list_local/2
            (engine 0.7.2) lib/engine/adaptor/service.ex:79: Engine.Adaptor.Service.State.refresh_list/1
            (engine 0.7.2) lib/engine/adaptor/service.ex:92: Engine.Adaptor.Service.start_link/1
            (stdlib 3.17) supervisor.erl:414: :supervisor.do_start_child_i/3
            (stdlib 3.17) supervisor.erl:400: :supervisor.do_start_child/2
            (stdlib 3.17) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 3.17) supervisor.erl:1250: :supervisor.children_map/4
            (stdlib 3.17) supervisor.erl:350: :supervisor.init_children/2
            (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Environment
Os: Ubuntu 22.04.1 LTS
NodeJS: 16.15.1
Erlang: 24.2.1
Elixir: 1.13.4 (compiled with Erlang/OTP 24)

**Comment by taylordowns2000** [comment]
Ah! Sorry to hear this. Re: our call, that _sounds_ like maybe the runtime install is missing.

That's the second to last one in the Elixir & Ecto setup steps [here](https://openfn.github.io/Lightning/readme.html#set-up-your-environment).

```
asdf install  # Install language versions
mix local.hex
mix deps.get
mix local.rebar --force
mix ecto.create # Create a development database in Postgres
mix ecto.migrate
mix openfn.install.runtime
npm install --prefix assets
```

**Comment by mtuchi** [comment]
> Ah! Sorry to hear this. Re: our call, that _sounds_ like maybe the runtime install is missing.
> 
> That's the second to last one in the Elixir & Ecto setup steps [here](https://openfn.github.io/Lightning/readme.html#set-up-your-environment).
> 
> ```
> asdf install  # Install language versions
> mix local.hex
> mix deps.get
> mix local.rebar --force
> mix ecto.create # Create a development database in Postgres
> mix ecto.migrate
> mix openfn.install.runtime
> npm install --prefix assets
> ```

`mix openfn.install.runtime`
Fixed my issue
