### ISSUE TITLE
Internal Server Error when switching between inspected jobs

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/lightning#2254]
v2.7.2

Navigating from history, when I switch between inspecting different jobs, I sometimes get an Internal Server Error. So far could only reproduce it on this workflow: https://app.staging.openfn.org/projects/20ccfd7b-bea5-4d2a-85c2-9b9db235bb2b/w/241ed495-b09a-47a9-8931-c0a764b32085?v=10&a=9a5ef44a-c463-4e49-941d-3310b3c79761&m=expand&s=9e5bcc74-4733-4b29-8753-b400a7c98a11#log

https://www.loom.com/share/6a9eb6e7dfad44d78d9b1cb2d7d38927?sid=9cdaa9ea-e78f-44c7-b931-1359bdd865a6

**Comment by ritazagoni** [comment]
@christad92

**Comment by christad92** [comment]
This is fixed b this: https://github.com/OpenFn/lightning/pull/2252

**Comment by taylordowns2000** [comment]
@christad92 , i'm closing this based on https://github.com/OpenFn/lightning/issues/2254#issuecomment-2209081807

please reopen if it shows up again!
