### ISSUE TITLE
state.configuration is null when using dhis2 adaptor

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#226]
Current: 
- Create a credential with a dhis2 credential object (ex: {
    "username": "admin",
    "password": "district",
    "hostUrl": "https://play.dhis2.org/2.36.6"
  })
- Create a workflow with a step that uses the language-dhis2 language pack
- Run workflow and get an error "TypeError: Cannot destructure property 'hostUrl' of 'state.configuration' as it is null."

Expected: 
Workflow to run successfully, and configuration to not be null.

**Comment by taylordowns2000** [comment]
Closing, this is because the previous job didn't return state.
