### ISSUE TITLE
Collapsed panel not spaced properly for AI assistant

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2287]
When collapsing the left panel with the `Input` and `AI Assistant` tabs, they're not pushed down properly and overlap with the expand button, as shown below.

<img width="88" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/55576069-add7-4541-94ee-3dd76ee67c03">

See the behaviour of the right panel (with `Run`, `Logs`, `Input`, and `Output`) for the expected look and feel.

**Comment by christad92** [comment]
This has been resolved in #2537
