### ISSUE TITLE
40mb dataclips can crash the web app

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2339]
In version `v2.7.11`, when large dataclips (~38MB) are sent back to Lightning from the `ws-worker` between steps, the app can crash.

Still investigating this, but below are a few timestamps where it seems that a crash was caused by a large dataclip:

### Log Timestamps around app crashes
- 13:22 to 13:23 UTC
- 13:59 to 14:02 UTC

```js
fn(state => {
  const targetSizeMB = 40;

  // Calculate the number of characters needed (1 char = 2 bytes in UTF-16)
  const targetSizeChars = (targetSizeMB * 1024 * 1024) / 2;

  // Create a base string to use
  const baseString = "A".repeat(100); // 100 characters long

  // Calculate the number of times the base string needs to be repeated
  const repeatCount = Math.ceil(targetSizeChars / baseString.length);

  // Create the large array
  const largeArray = [];
  for (let i = 0; i < repeatCount; i++) {
    largeArray.push(baseString);
  }

  // Create the final JSON object
  const largeJsonObject = {
    data: largeArray
  };

  return { largeJsonObject };
})
```

**Comment by taylordowns2000** [comment]
@josephjclark , in the past we'd discussed two sides to this (and @stuartc will ping you now to discuss)

1. ws-worker, if the `max_dataclip_size` is 10mb, dont send stuff that's > 10mb (refuse to send.)
2. lightning, if we receive a websocket message that's > 10mb, drop it/dont touch it/don't try to decode.

**Comment by josephjclark** [comment]
Raised in kit https://github.com/OpenFn/kit/issues/654

I don't think this is just dataclips, it affects logs too. So it's more like MAX_MESSAGE_SIZE_MB or something.

For now I'm gonna put a hard limit in the worker, but we'll also need to talk about how we can enable very large messages for cases where it's really really needed. Some sort of streaming/batching API. Mañana.
