### ISSUE TITLE
Update banners to user the common component across board

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2353]
We have recently created a component for banners that can be used across the application -- lightning and Thunderbolt. We have some banners that have not been updated to conform to the new design and need to be fixed. 

This issue is to ensure that we have them fixed across board - finding all banners and ensuring they use `common.alert` as specified [here](https://github.com/OpenFn/lightning/blob/c220c3ceafd0d5a29349e0447005cf6d94c8818c/lib/lightning_web/live/components/common.ex#L24).

**Comment by taylordowns2000** [comment]
1. confirm email
2. simultaneous editors
