### ISSUE TITLE
Allow deploy to manage credential associations for jobs in lightning

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2367]
Allow `cli deploy` to control the credentials that are associated with a given job in a workflow in a project.

- How should we uniquely identify credentials?
- First assume that all credentials are already available within the project (`project_credential` records exist) - can you associate jobs with those credentials?
- Then assume that the credentials belong to the deploying user but are _not yet_ available within the project (`project_credential` records don't exist) - can you prompt the user to see if they want to add `project_credential` associations to that project.

**Comment by midigofrank** [comment]
@taylordowns2000 we should definitely extend the credential uniqueness to projects.

**Comment by midigofrank** [comment]
Or maybe we can add the user email to the credential name to make it unique. Something like:

`"user@email.com:DHIS2 Prod"`

**Comment by taylordowns2000** [comment]
I think user (not project) is the way to go. In v1 we show the user email alongside the cred for selection—that's a better UX anyway—so the concern is just deployment.
