### ISSUE TITLE
Users can run a job with a dataclip ID

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#238]
### User story
As a user writing or updating a job, I would like to be able to run it manually with an existing dataclip, so that I can easily test and debug.

### Details

1. Create an "input" widget that is held inside the "inspector component" #381.
2. Give that widget a single text input field which takes a `dataclip_id`.
3. Add a 'run' button next to the `dataclip_id` text input.
4. When a user enters an id and clicks run, check if the dataclip is of type `:run_result` or `:http_request` and then execute that job with the given dataclip.

### Implementation notes

_**After this issue is done, two more issues will move us towards the UI we want.**_ That UI is described in #378 

_LATER_: Replace the dataclip_id input with a dropdown of
  - dataclip from latest run
  - saved inputs

Set the latest run dataclip id as the default

_EVEN LATER_: Display the selected dataclip in a JSON blob box.

Note that dataclips of type `:run_result` and `:http_request` can be used as input state for a job, but type `:global` cannot. (Maybe a quick call between @stuartc and @taylordowns2000 required here to discuss `assemble_state`?)

Setup
![Screenshot 2022-09-22 at 11 11 21](https://user-images.githubusercontent.com/36554605/191693798-ead56b12-6bdb-493f-8874-8cd0bf39cf3d.png)

Input state
![Screenshot 2022-09-22 at 10 56 18](https://user-images.githubusercontent.com/36554605/191692291-bc7367d4-1679-4c2a-86ae-51d79c1a1925.png)

### Release notes 
Run a job in the job editor and see the logs

### Tests 
- I can call xx-function passing in a dataclip_id and a job_id
- if the dataclip_id is not valid, it returns an error
- if no error is returned, i expect to see a new 'run' - that run's invocation event should have the correct dataclip_id and job_id

**Comment by taylordowns2000** [comment]
@stuartc , can we chat about this and the order of operations for a few upcoming issues?
![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/169866e4-4a76-4ac9-9f01-6c440a778c72)

**Comment by stuartc** [comment]
Currently the logic for deciding on what to do with the state (i.e. how to assemble it) is determined by the trigger on the job.

This means that 'adhoc' jobs are incompatible with our current implementation.

I have thought about an idea before that an event is associated with a trigger (and perhaps not directly with a job). This would allow us to maintain a history about how a given event entered the system. It does not account (at first) for the changes to how jobs create triggers, we would need to create a new trigger for every change.
This feels like there is _some_ value in this approach but shouldn't be taken lightly - as a lot of assumptions would be tested here.

**Comment by amberrignell** [comment]
@stuartc please see screenshots added to the issue above
