### ISSUE TITLE
Credential association with `openfn deploy` doesn't update credential in project

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/lightning#2412]
v2.7.19

When I `openfn pull`, the credentials associated with the jobs are represented correctly in the resulting `project.yaml`. However, changing the credential to another one or to `null` doesn't result any change on the platform. The version number in the project URL doesn't get updated either. 

See video: https://www.loom.com/share/ad0dab31e8f5472a8dde9a412fde21f0?sid=e65d536c-f56a-468e-a22e-65762b268d02

**Comment by taylordowns2000** [comment]
noting that this was solved by `openfn/cli@v1.8.1`
