### ISSUE TITLE
Run shows as `failed` while step shows as `running`, in truth already failed

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/lightning#2416]
On both the [history page](https://app.openfn.org/projects/2fedca61-bb42-4e65-a908-7a60f1b25c1e/history?filters[workorder_id]=db766f95-1d55-40b6-bd55-47d743226422) and when [inspecting](https://app.openfn.org/projects/2fedca61-bb42-4e65-a908-7a60f1b25c1e/w/3350e498-75dd-4d9b-8ca7-a83c00ae21e7?v=655&a=a1ed7bf9-3830-4113-8e59-69ddf5dd9222&m=expand&s=879f3456-a196-44b3-9b48-59a8cc1d0f8d#log), a run is showing as `failed` while the step is showing as `running`. 

Meanwhile the step has already failed with `RuntimeError: TypeError: Cannot read properties of undefined (reading '0')`

This is a workflow that was triggered by another workflow.

v2.7.19

I have reproduced this locally on main:

- [ ] Yes
- [ x] No

![Screenshot 2024-08-22 150850](https://github.com/user-attachments/assets/cc765681-56eb-4e87-9bf2-14977bff4ea3)
![Screenshot 2024-08-22 150812](https://github.com/user-attachments/assets/75a0130b-01f2-402b-bccc-8d50defb5328)

**Comment by taylordowns2000** [comment]
Could add some sort of trigger that sets steps to `failed|lost|crashed|skipped` (whatever the right decision is here!) when the run has finished and the channel is closed

**Comment by stuartc** [comment]
@taylordowns2000 yeah we've been thinking the same; but we need to be really careful about how we do it - we're essentially changing data to something we don't know for certain. So some considerations about what the worker _might_ have been doing or how it might have failed and only apply this policy after a period of time where it would be theoretically impossible for it to change.

**Comment by taylordowns2000** [comment]
Yeah I think we're on the same page. The ideal is "100% honest and as helpful as possible" - where honesty is more important than helpfulness. So "lost" would be just fine for all these as that's our shorthand for "I don't know what happened."

As in: "that step is `:lost` because I never got information about whether it succeeded or failed."

**Comment by taylordowns2000** [comment]
@christad92 , why is this something we wont fix?

**Comment by christad92** [comment]
I added the tag based on the chat with the Stu when we were reviewing bugs. We had placed in the "Later" Section while dropping the initial [comment](https://github.com/OpenFn/lightning/issues/2416#issuecomment-2337941139). 

Removing the  tag now and adding
