### ISSUE TITLE
Allow the worker to send timestamps for Runs and Steps

### ISSUE THREAD

**Issue by stuartc** [OpenFn/lightning#2434]
Currently, whenever a Run/Step is started or completed - the timestamp is set by Lightning.

While this isn't 'incorrect' it isn't very precise. 

You can see in the logs that a step took say 500ms but the duration according to lightning is anywhere between 300-800ms longer. (Edit from @taylordowns2000 ... sometimes this is more than **_15 seconds_** longer!)

**Suggested changes**

Starting at the Run channel, follow the calls to functions that create and update Runs and Steps. Any date times that get added should be replaced by params from the worker.

It's likely we will have to have it default to a DateTime from Elixir if the data isn't provided.

**Comment by stuartc** [comment]
Worker events that send timestamps as strings: https://github.com/OpenFn/kit/commit/eaa3859505675419d83aaeccc0a51f8875172db5#diff-36714ceebf4b223bd4408842ea195394e7e271542af93b47e06a4bba68e8e12eR151

**Comment by taylordowns2000** [comment]
@stuartc and @midigofrank , as you approach this one is it possible to keep some sort of measure of when it was finished in the DB—and is that measure the `updated_at`?

I'd like to be able to know: "this run took 5s from start to finish on the worker, but it took 25s to process that run information and store it in lightning"

**Comment by midigofrank** [comment]
@taylordowns2000 yes, we can use `updated_at` to measure that. Only problem is that the `Run` schema doesn't track it. `Step` on the other has the `updated_at` field

**Comment by taylordowns2000** [comment]
Understood. Thanks @midigofrank . So what do you (and @stuartc ) think? Should we calculate it when we need it? (Do a "find last step for run and" type of thing? Or should we add a column to run?)

My gut says to add a column to run. I think Stu even mentioned that he wanted (at some point) to more closely follow Oban's model where we have not only `finished_at` and `updated_at`, but also `lost_at` on the run.
