### ISSUE TITLE
Search run logs or input body

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#244]
### User story
As a user that's looking for the workflow run of a request with a specific value, I would like to search for a string in workflow logs and input/output data. 

### Details
MVP is to only show workflow runs which contain the searched string, but this would mean they might still have to click in and out of workflow runs and steps to find what they are looking for. How would this look for the user down the line?
@taylordowns2000 to add code from platform app which can be used for inspiration + thoughts on where we can improve.

![Screenshot 2022-08-22 at 23 57 28](https://user-images.githubusercontent.com/36554605/186033067-e62a7265-b4d1-4dab-9723-9e837b282d28.png)

### Implementation notes
This is a search console, not jsonb or tsvector search 
Out of scope: incrementally loading the search results. We will optimise on this further down the line.

### Release notes 
- Filter workflow runs by text/value in run logs or input body

### Tests 
On the runs history page, there is a text input with the label 'Search' and placeholder 'Search run inputs and logs'. 
There is a workflow run a on the page that does not contain 'searchtext' in the body. There is a workflow run b which does. 
When the user types in 'searchtext' and clicks the search icon, the workflow run a is filtered out, but workflow b is still there. 
The search bar (grey box) takes up the full window (now white space above or below)

### QA
- [ ] This has been QA’d by Amber, branch can be merged after review

**Comment by stuartc** [comment]
@taylordowns2000 any advice on this:

> This is a search console, not jsonb or tsvector search

I get we don't want to add a tsvector column right now, are we thinking to cast both the dataclip body and log strings (which are in an array) into varchars and then doing an `ilike` on them?

**Comment by taylordowns2000** [comment]
Yes exactly. Simple query with casting yo string and `ilike($blah$)`. At this point it's essentially a working prototype that we know doesn't scale _at all_, but we can get some feedback on the UX for the demo site and buy ourselves time to implement more elegant and performant searching.
