### ISSUE TITLE
Webhook Auth: Add authentication rules to webhooks

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/lightning#245]
**Figma:** https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=262-4097&mode=design

## Overview:

As a user, I want to be able to add either Basic or API Key based authentication to my Webhooks to have a layer of security.
- When creating or editing a Webhook trigger, I should be able to add a "Authentication" Credential.
- Within OpenFn, we should allow the user to select to setup Basic HTTP Authentication or API Key Authentication
- The user can opt to have no form of authentication

As a user, I may need to rotate keys, therefore:
- I may want to have multiple authentications that can exist for a single Webhook
- These multiple authentications can be of different types (Basic or API key)

Issues created for the implementation all linked to this Epic

**Comment by NickOpenFn** [comment]
Not ready: Requires UI

**Comment by taylordowns2000** [comment]
@elias-ba , @midigofrank , @NickOpenFn - noting this here so I don't forget.... the create/update/delete actions on `webhook_auth_methods` themselves and the add/remove actions (create/delete on `trigger_webhook_auth_methods`- the many-to-many table) need audit trail actions that are very similar to those defined for credentials. Nick and I will sync up on this tomorrow to get you the full list!
