### ISSUE TITLE
Increase in runs getting lost

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2465]
Recently, it seems as though runs are getting lost a lot more.

https://app.openfn.org/projects/2fedca61-bb42-4e65-a908-7a60f1b25c1e/runs/95da66d2-f70f-4d28-b8bf-bd7b12da212a

**Comment by christad92** [comment]
This seems to be related to the GitHub sync issues and we have not reported any new lost runs since refreshing workflows to create new snapshots. 

Seems related to #2460 and #2461

**Comment by christad92** [comment]
We have seen some lost runs since #2460 went to prod. We have seen a number of lost [runs](https://analytics.openfn.org/question/596-lost-runs-since-9th-september) as well. 

![Image](https://github.com/user-attachments/assets/91ef7f71-48f7-4456-8782-07bbd0644c8b)

**Comment by christad92** [comment]
We have also noted that runs get lost when data clips are too large and are not returned to lightning from the worker.

**Comment by taylordowns2000** [comment]
@stuartc , the september 10th one was because the worker restarted, likely taking 2 jobs down with it: https://console.cloud.google.com/kubernetes/deployment/europe-west6/swiss-ap-1/default/global-worker/observability?authuser=0&organizationId=189089165982&project=platform-test-267207
