### ISSUE TITLE
A user can change their own email

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#247]
## Story
As a normal user,
I want to change my own email address and validate the new one,
So I don't have to ask the admin.

## Details

This builds on #218 , and we should follow the pattern laid down in the (soon to be removed) `lib/lightning_web/controllers/user_settings_controller.ex:17`.

Note the router.ex: `get "/profile/confirm_email/:token", UserSettingsController, :confirm_email`

- [x] Via the profile_live form the user should submit this change request
- [x] The user should receive an email with the confirmation token
- [x] When the user clicks the link (or enters the confirmation token somewhere) the change should be effected.

@elias-ba , this initial functionality was part of your users and auth PR - can you put a link here to the documentation that you followed for that functionality? There's a _lot_ in there and I'd like a clearer picture of what it's doing and why it's doing it before we decide what to keep/remove/update. Thank you!

(CC @NickGowdy , who's been working on #218 .)

## Implementation Notes:

```ex
    test "a user can edit their email address", %{conn: conn, user: user} do
      {:ok, profile_live, _html} =
        live(conn, Routes.profile_edit_path(conn, :edit))

      assert profile_live
             |> form("#email_form", user: @invalid_email_update_attrs)
             |> render_change() =~ "can&#39;t be blank"

      {:ok, conn} =
        profile_live
        |> form("#email_form", user: @update_email_attrs)
        |> render_submit()
        |> follow_redirect(conn)

      assert "/" = redirected_path = redirected_to(conn, 302)

      html =
        get(recycle(conn), redirected_path)
        |> html_response(200)

      assert html =~ "Email changed successfully."
      assert html =~ "Projects"
    end
 ```

**Comment by taylordowns2000** [comment]
@mtuchi , see the PR above before starting: #612

**Comment by amberrignell** [comment]
@elias-ba to describe the live view approach
