### ISSUE TITLE
AI Assistant: Handle apollo errors

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/lightning#2474]
The AI assistant needs to show good feedback to users when apollo is offline.

Right now, if the deployment isn't set up (ie, no env vars), there's a nice error page saying "hey, apollo isn't set up, call your sysadmin"

If apollo is not found (if the server does not return 200), the chatbox is greyed out with no feedback.

## Error Cases

Here are some errors I can think of:
* Errors form the apollo server for new chat messages (wrong api key, a bug on apollo, anthropic offline)
* apollo server isn't responding (should we maintain a heartbeat rather than just asking when the server starts?
* apollo messages timing out

## Expected behaviour

Even if apollo is unavailable, the user should be able to see and scroll the chat history

I think basically we need to:
a) anticipate that we can't send a message and disable the chat box with an error
b) handle requests which return errors (do we save the unsent message in history? When do we re-send?)

**Comment by christad92** [comment]
When connection to Apollo fails, we should show the users a message saying: `Oops! Couldn't connect to the AI Assistant, please contact your instance administrator`. 

We should also block the user of the feature until the server sends a message back

**Comment by josephjclark** [comment]
@christad92 We should still show chat history though! Don't block the user from the assistant completely - just stop them sending messages

**Comment by josephjclark** [comment]
Maybe rleated to #2704
