### ISSUE TITLE
AI Assistant: Allow disclaimer/help to be shown at any time

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/lightning#2476]
The AI "disclaimer" text, which explains the tool and how it works, is unavailable after the splash screen has been dismissed.

There should be a `?` icon somewhere in the top of the  component which opens this screen at any time. There's  really important information in there.

**Comment by christad92** [comment]
This will be done in user preferences but can be overridden by project settings.

**Comment by christad92** [comment]
> [@christad92](https://github.com/christad92) how can user preferences affect this?
> 
> Is your comment on the right issue?

Hey @josephjclark.... 

Sorry, just read your description of the issue... Retracting my comment. 

I was thinking this was a way for us to always show the disclaimer to users every time they try to use the assistant.. but I see your point here.

**Comment by josephjclark** [comment]
This is still an important issue though @christad92 . The help text we show on the disclaimer, which is REALLY important to responsible AI, is currently totally unavailable to users. This is really poor practice and does need addressing.

We need to talk about your original comment because it also sounds a problem, but lets do that on the appropriate thread please.
