### ISSUE TITLE
Export projects as `.yaml` via UI

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#249]
### User story

As a user that's starting to version control an EXISTING project, or a user that wants to deploy an EXISTING project to a new lightning instance, I would like to export a project as yaml and save it to my local machine.

### Details

**Note that while this function will be called _either_ by a button on the UI or by the devtools/CLI, using an api token, the issue here is only for the button on the UI which triggers a download.**

See Zacck's work on [this branch](https://github.com/OpenFn/Lightning/tree/projects-as-code-exporter) and copy/paste the code you need from it

1. Create a function which generates a zip file which has a series of workflow folders with jobs files and and a project.yaml according to the outlined example. 
2. See portability specification [here](https://github.com/OpenFn/kit/blob/main/packages/cli/README.md#deploying-workflows)
3. Add an 'export' button to project settings>project. When the user clicks the button, download the project as code for them. 

![Screenshot 2023-06-26 at 08.45.54.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/08354cb8-5134-4d84-8ba0-6b0cc90c842b)

### Implementation notes

**⚠️ BRANCH OFF `nodes-and-edges-release` BEFORE BEGINNING ⚠️**

- [ ] Review the [current export function](https://github.com/OpenFn/Lightning/blob/nodes-and-edges-release/lib/lightning/projects.ex#L436-L441)
- [ ] Update the tests to make sure it matches the new pattern specified
- [ ] Update the current export function to pass the tests
- [ ] Review the "export as" button from v1 (see image) to familiarize yourself with the functionality (and how that file download is initiative)
  - [ ] [ExportProjectConfigModal.js](https://github.com/OpenFn/platform-app/blob/main/assets/js/components/ProjectSettings/ExportProjectConfigModal.js#L43)
  - [ ] [ExportController.ex](https://github.com/OpenFn/platform-app/blob/main/lib/open_fn_web/controllers/export_controller.ex#L377-L411)
- [ ] Add the button to the project settings page
- [ ] Write tests for the project settings button

![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/ce74430d-496a-4306-b827-e71729ecea54)

### Release notes 

- [x] Export a project as `.yaml`

### User acceptance criteria

- [x] project editors, viewers and admins can export a project 
- [x] Credentials secrets do not get exported
- [x] Given a project with 2 workflows, 2 credentials and 2 jobs, when I export that project, my yaml file contains 2 workflows and 2 jobs
- [x] When I export a project as code, I can use the same file to deploy

**Comment by taylordowns2000** [comment]
@amberrignell , @elias-ba , this looks good to go

**Comment by taylordowns2000** [comment]
thanks @zacck . @elias-ba , Amber has updated the issue with a link to the spec docs here: https://github.com/OpenFn/kit/blob/main/packages/cli/README.md#deploying-workflows

(I think it's exactly the same as Zacck's above.)

**Comment by taylordowns2000** [comment]
@zacck , this from Elias:

I have made great progress on #249 Export Project Yaml. I have layed out an export button that is capable of generating a project.yaml file in the project settings page. See draft PR here
Even tho this is super close it's not ready yet and there are basically two more things left to do (I wish I had more time to handle them before ending my day - but I have a lot of family stuff with Eid :pensive:)
Things that are left to do:
Hook the handle_event behind the export project button to a Phoenix controller that will serve the generated file. Currently I am generating the file and saving it in the priv folder. Even tho that was a good option to test the flow of this feature it's not good for production and we should use this example from platform to implement a ProjectExportController in Lightning.
Fix some of the helper functions in the Lightning.ExportUtils module. To see those functions failing please run mix test.watch test/lightning/projects_test.exs:365. Those functions might just require preloading edges or nodes.
I hope this will be a soft pass of this issue. Please ping me if there is anything that I could do to make this more clear.
