### ISSUE TITLE
AI Assistant: Wrap content in chat  interface.

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2493]
We should be wrapping the content of the chat interface based on the width of the panel. We don't users be scrolling left and right to see the content.

<img width="482" alt="image" src="https://github.com/user-attachments/assets/b57ed97e-b58a-44f4-95c7-c1056f59c5b9">

**Comment by midigofrank** [comment]
I'm unable to reproduce this. Might have already been fixed

**Comment by midigofrank** [comment]
Never mind, I've been able to reproduce it. This happens when there is a long single text.
This mostly comes from code blocks. The fix for this would be to have a horizontal scroll bar on the code block
