### ISSUE TITLE
Github action to deploy changes to Lightning

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#250]
### User story

As a user running business critical workflows
I’d like for git commits to a branch in a GitHub repo to update my Lightning project
So that I don’t loose my work, can review changes before deploying and can roll back to previous versions

### Background

Some pre-requisite reading

- [Creating an action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action)
- [Publishing an action](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) - ~this should probably be defined as a new "package" in https://github.com/OpenFn/kit~

### Details

In the root folder of the repo, there's the configuration (which defined the path to the other files), the project.yaml, and state file. See [here](https://github.com/OpenFn/dummy-deploy-test/tree/main) for an example.

- [x] (1) Write a GitHub action that will use the CLI to deploy/update a project in Lightning
- [ ] (2) A user should be able to find this action on the github marketplace and use it in their own repo, maybe deciding to have it run `on: commit to main` or `on: commit to custom-branch-a`
- [x] (3) It will pull in the API token from a github secrets file - don't keep API_TOKEN in the config.json

This is good because it decouples any "github sugar" from the [devtools CLI](https://github.com/OpenFn/Lightning/issues/249), which blocks this issue.

### 
To do
- [ ] Pipe state response to state path
- [x] Commit to repository
- [ ] Update Portability docs (on how to use deploy)

### Business items
- When you deploy for the first time OR any other time, the CLI returns your new or updated state.json. please modify the github action to commit that state.json to the repo.
- Publish the github action
- Delete "dummy-deploy-test" and any other public reference to a project.yaml.
- Update docs.openfn.org with full documentation on CLI deployment, including the https://docs.openfn.org/documentation/portability#proposal-v4-next
- 

-----

- Need to ship pull command
- Need to publish deploy action
- Need to publish pull action
- Dependency on Joe to fix typings: https://github.com/OpenFn/kit/issues/355
- Deploy sync from lightning
- deployment.md needs to be updated

**Comment by taylordowns2000** [comment]
ooooh also @zacck , how about this one? i feel like it might have gotten lost in the handover with @amberrignell ?

is this done? i'd like to set this up for a couple of projects - if it's ready to use maybe we can sync up tomorrow and you can show me how to add it for a couple of app.openfn.org projects

**Comment by zacck** [comment]
@taylordowns2000  this is here we can  test it https://github.com/OpenFn/deploy_action

**Comment by taylordowns2000** [comment]
todo:
1. when you deploy for the first time OR any other time, the CLI returns your new or updated state.json. please modify the github action to commit that state.json to the repo.
2. publish the github action
3. delete "dummy-deploy-test" and any other public reference to a project.yaml.
4. update docs.openfn.org with full documentation on CLI deployment, including the https://docs.openfn.org/documentation/portability#proposal-v4-next

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/250?planning-poker) with Zenhub @zacck @elias-ba @stuartc

**Comment by zacck** [comment]
- Add markdown docs to docs repo to satisfy 4 above

**Comment by NickOpenFn** [comment]
Portability page:
- Deleting references to old documentation
- Include documentation for new Portability
- Include highlighted section that explains how to get the CLI with the `--help`

**Comment by NickOpenFn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/250?planning-poker) with Zenhub @josephjclark

**Comment by taylordowns2000** [comment]
@zacck , i see a mix of documentation notes here and on the docs issue https://github.com/OpenFn/docs/issues/360. Have done my best to pull them all over there.

For _this one_ (the Github actions) what's left before this is done?

- [ ] **Commit message?**
- [ ] Anything else?

**Comment by taylordowns2000** [comment]
nothing that this seems hard, and that we're putting it back in the backlog for @zacck to pick up after the docs issue is done.

confirmed by @zacck  that the only remaining item is the commit message

**Comment by taylordowns2000** [comment]
the release of `OpenFn/cli-pull-action@v0.7.0` and [this change](https://github.com/OpenFn/demo-openhie/commit/be7f9b6f54f984cc1fc1834c34f148df02383061) to the recommended workflow closes this issue
