### ISSUE TITLE
Can't inspect runs sometimes  - It shows the lost connection icon and loads endlessly

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2520]
I tried to inspect a run from the history page but it keeps loading endlessly and shows the lost connection icon. This was noticed in this [project](https://app.openfn.org/projects/88ebc9c6-03e0-4f0b-884c-24dae1da668a/history) and has been reported by the implementations team as well. 

See loom video below: 
https://www.loom.com/share/2aade943d0df44b38698f1768995c15e?sid=1332aa89-5dc4-4381-9b6c-e8ca5da56a54

Affected Work orders: 
1. https://app.openfn.org/projects/88ebc9c6-03e0-4f0b-884c-24dae1da668a/runs/e454563a-af96-4e2d-a3a3-52906f24946b
2. https://app.openfn.org/projects/88ebc9c6-03e0-4f0b-884c-24dae1da668a/runs/366568f8-27be-47d8-beb9-1b3f01fe487a

**Comment by stuartc** [comment]
https://openfn.sentry.io/issues/5873022342/?environment=prod&project=6446500&query=&referrer=issue-stream&statsPeriod=7d&stream_index=0

This looks like we are checking if the Job is saved, however a `Snapshot.Job` is being sent..
Why we're looking at a Snapshot.Job, I'm not sure but it appears that embedded schemas don't have a `__meta__` property.

**Comment by stuartc** [comment]
May be fixed by: https://github.com/OpenFn/lightning/pull/2516

**Comment by christad92** [comment]
To validate this, inspect a run attached to a snapshot that is not the latest.
