### ISSUE TITLE
Saving a workflow with empty job body says "Workflow saved" but does not save the empty job

### ISSUE THREAD

**Issue by elias-ba** [OpenFn/lightning#2544]
See video here: https://www.loom.com/share/158848d1c3f84a8a826177947d4ef9bf?sid=67673bd5-b6ee-4cfa-99f0-a4ec2be6df3b

**Comment by christad92** [comment]
This is by design. We need to have a placeholder text to help users get started. The provisioner will also not allow a job to have an empty body.
