### ISSUE TITLE
Implement a Welcome Section for the Projects Page

### ISSUE THREAD

**Issue by elias-ba** [OpenFn/lightning#2563]
### **User Story**
As a user visiting the projects page, I want to see a collapsible "Welcome" section with tutorial videos so that I can quickly understand how to use the platform through Arkade videos. This section should allow users to effortlessly show or hide its content based on their preferences.

### **Details**
- **Header Title**: The section should have a warm and friendly title, like **_Good morning, Frank!_**
  
- **Tutorial Links**: 
   - Include 4 items (links to Arkade videos) styled as cards. We think the components from [this Tailwind UI blog page](https://tailwindui.com/components/marketing/sections/blog-sections#component-7c4bcd0e50e14e855d55d20b6cd445d1) would work well, and we’d like them to be rectangular in shape.
   - Each card title should clearly reflect the purpose of the corresponding Arkade tutorial.
  
- **Card Interaction**: 
   - Each card should be clickable, opening a modal with the Arkade video tutorial set to autoplay.
   - The modal must include a title and a close button.
   - Ensure that videos do not continue playing in the background once the modal is closed.

- **Collapsible Section**: 
   - The section should be collapsible, featuring an icon or arrow to indicate the ability to show/hide the content. By default, the section should be expanded.
   - When collapsed, only the section title and the expand/collapse icon should be visible. 
   - Implement functionality to save the user's preference for collapsing or expanding the section, ensuring it remains in the chosen state during future visits (integrate with issue #2564).

- **Tutorial Completion**: 
   - After a user finishes watching an Arkade tutorial, the associated card should display a visual cue (like a shade) indicating its completion. 
   - This preference should also be saved to remember the user's progress during their next visit.

**Comment by christad92** [comment]
@elias-ba @stuartc @midigofrank 

Here is the first pass of the UI design for the projects list with the cards. Stu wants us to explore some design in the card and that will not stop the progress. 

I am taking a leap off Elias' for storing user's preferences and adding a check box here for us ti know if a user does not want to see the panel in the future. Closing the panel shouldn't automatically imply " I never want to see this again" unless the user says so by checking the box.

![Image](https://github.com/user-attachments/assets/c5381ca8-ecb9-4d62-a4b9-87f23ce2a69c)

![Image](https://github.com/user-attachments/assets/cf266553-c1c6-45f2-b8f5-f98cde6e85c7)

 ![Image](https://github.com/user-attachments/assets/b5c2d508-f3f3-489b-8e42-d99b61929498)

**Comment by christad92** [comment]
Following the chat from this morning, please see the updated design here: 

Default (Expanded)
![Image](https://github.com/user-attachments/assets/cc839884-be58-4ce1-af34-1da7403eba93)

Collapsed
![Image](https://github.com/user-attachments/assets/d060e869-677d-4b80-b031-772b91dfde96)

cc: @elias-ba @midigofrank @stuartc
