### ISSUE TITLE
Expose collections via an HTTP endpoint

### ISSUE THREAD

**Issue by stuartc** [OpenFn/lightning#2566]
Re: https://github.com/OpenFn/lightning/issues/2190

Provide an HTTP endpoint that exposes methods that calls functions inside the Collection context.

Streaming is a requirement of this feature, we should be using features like `send_chunked` and `chunk` (from Plug).

## Auth

Access to this API must be authenticated using either a Users access token, or a RunToken, in the Authentication Header

### GET KEY /collections/:key

Fetches a single item from a collection, by key,
```
GET /collections/{collection_name}/{key}
```
* Returns 404 if the collection does not exist
* Returns 200  and `{ key, value }` if the item was found
* Returns 204 and `{}` if the item does not exist

### GET COLLECTION /collections

Fetches all values in a collection, with a filter/query
```
GET /collections/{collection_name}?<query>
```

* Query params:
  * `key` - return keys matching this pattern. Can include multiple wildcards `*` for pattern matching
  * ~updated_after~ / `created_after` only returns records GTE this the start of (last second? of) this date
  * ~updated_before~ /` created_before` only returns records LTE the end of (last second? of) this date
  * `limit` only return N records (default: 1000)
  * `cursor` base64-encoded cursor.  Searches start from this index (inclusive?)
  * `meta` flag to include metadata (timestamps) in as a `_meta` key on each value
* Timestamps in queries are expected to be parsable as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) strings.
* Returns 404 if the collection does not exist
* Return an empty `{ items: [] }` array if no results with 204

**Returns:**

```
{
  items: [{ key, value, created, updated }],
  cursor: "string-to-be-abstracted-and-used-on-next-request-for-more-records"
}
```
Each item is a `{ key , value, created, updated }` object (I'd like a name for this wrapper - Record?)

### POST /collections

Upsert values into a collection
```
POST /collections/{collection_name}
```
* Values are uploaded as a JSON object in the body in the form of `{ items: [{ key, value, ...meta }] }` (where meta is not used now but would be a collection of metadata properties)
* Returns 404 if the collection does not exist
* Returns 201 if any new values were created
* Returns 200 otherwise
* New values will be assigned a created_at and updated_at timestamp. Existing values will have their updated_at changed.

**Returns**

For any 20x payload, return a JSON summary in the form:

```
{ upserted: 101, errors: [{ ... }] }
```

### DELETE /collections

Remove values from a collection
```
DELETE /collections/{collection_name}/{key}
```
* Key can include multiple wildcards `*` for pattern matching
* Query params:
  * ~updated_after~ / `created_after` only returns records GTE this the start of (last second? of) this date
  * ~updated_before~ / `created_before` only returns records LTE the end of (last second? of) this date

**Returns**

A JSON summary in the form:

```
{ deleted: 101 }
```

It is difficult to return the list of deleted keys, so we will not do this in v1.

**Comment by josephjclark** [comment]
Updated the main issue body  for GET/POST/DELETE requests, as per the Canvas conversation

**Comment by jyeshe** [comment]
Updated the GET reponse to:
```
{
  items: [{ key, value, created, updated }],
  cursor: "string-to-be-abstracted-and-used-on-next-request-for-more-records"
}
```

**Comment by josephjclark** [comment]
Updated the issue with changes to the spec:

- POST uses ` { items: [] }` object instead of flat array
- POST returns `{ upserts, errors }` instead of `{ upserted, errors }`
- GET returns is `{ items, cursor }` instead of `{ results, offset }`
- `cursor` (base64 encoded) instead of `offset` across the spec
- `limit` defaults to `1000`

**Comment by josephjclark** [comment]
New changes (I haven't updated the spec yet)

* collections/stuff/:id always returns ONE item. 200 if the item found, 204 and empty object if no item
* collections/stuff is always a list (return all or return match) which accepts query parameters `key`, `updated_before` etc

**Comment by josephjclark** [comment]
Discussion: should we support `created_` AND `updated_` updated? This means maintaining TWO more large indexes at the backend.

We don't know what users want yet. Inserted or updated.

For now, we're ONLY going to support `created_` (inserted) to keep our costs down. We can work out  a solution later if users wanted updated filters.

**Comment by josephjclark** [comment]
Another change: it's a bit hard to get the list of deleted keys. So for now on delete, we'll return the count (the number of deleted items) but not the list of keys
