### ISSUE TITLE
Align gaps/margin between panel icons and menu/title when panel is collapsed

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2571]
The gaps between the panel menu/tabs and the expand/collapse icon are not uniform across the 3 panels in the IDE. We want the margins to be the same across the panels so it doesn't look off. 

See the images below with the markings.

![Image](https://github.com/user-attachments/assets/6dfc1e88-7bfa-42d1-b028-64138be1b753)
![Image](https://github.com/user-attachments/assets/9ed7d9da-62c1-4f49-a10e-c63b900df5f4)

**Comment by luciastefankova** [comment]
Hi, I would like to work on this. Could you please assign it to me?

**Comment by christad92** [comment]
Hi @luciastefankova thanks for your interest in taking this issue. 

I have assigned the issue to you. Please let me know if you need any help.

**Comment by christad92** [comment]
@luciastefankova how is this going?

**Comment by christad92** [comment]
@luciastefankova please can you provide an update on this? This is a crucial bug and we would like to get a fix in ASAP.
