### ISSUE TITLE
Delete a project

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#258]
### User story
Delete a project from the admin settings page 
As a superuser that has noticed a project is no longer being used (no enabled workflows, no users building any either), I would like to delete a project, so that I can declutter my projects page. 

Delete a project from the project settings page 

### Details
Delete a project from the admin settings page
There is already a button for deleting a project in /settings/projects. The functionality needs to be added to it. 

Delete a project from the project settings page 
![Project Details.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/caf3a912-7f51-44ba-98ad-f86cc2ae2a86)

### Implementation notes
Consider how cascade works, if there is a timer before we actually delete a project and which users are allowed to do this. 
audit trail ? 

### Release notes
- Delete a project

**Comment by taylordowns2000** [comment]
closed in favor of #746
