### ISSUE TITLE
Rename 'schema' to 'type' in create credential

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#260]
On the create credential page, the credential 'schema' should be renamed to 'type' so that it is less confusing to non-technical users. The 'Choose a credential schema' should say 'Choose a credential type'. 

![Group 1](https://user-images.githubusercontent.com/36554605/184351046-cb87ccb2-85c7-41a4-82f0-ec088279a05e.png)

**Comment by taylordowns2000** [comment]
closed by #266
