### ISSUE TITLE
Losing connection when navigating back from IDE to Canvas

### ISSUE THREAD

**Issue by Prymtym4eva** [OpenFn/lightning#2622]
**Describe the bug**

When I hit the "Esc" key to navigate back from the IDE to the Canvas I always see the red "disconnected" icon in the top right corner and it takes a long time, then eventually it reconnects and the Canvas works.

```
[error] GenServer #PID<0.1232.0> terminating
** (FunctionClauseError) no function clause matching in LightningWeb.WorkflowLive.Edit.handle_event/3
    (lightning 2.10.0-rc.1) lib/lightning_web/live/workflow_live/edit.ex:1246: LightningWeb.WorkflowLive.Edit.handle_event("modal_closed", %{"id" => "new-credential-modal", "key" => "Escape"},
```

**Version number**

v2.9.13 (1.3.26)

I have reproduced this locally on main:

- [ ] Yes
- [x] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to Canvas
2. Create a new job.
3. Go to Inspector.
4. Edit job.
5. Press "Command+S" to save.
6. Press "Esc" to navigate back to Canvas.
7. See Bug! 🐞 

**Expected behavior** 

I'd expect not to lose connection. I'm running on fairly stable 4G and none of the other interactions with the canvas produce this disconnection.  (Btw I'm reporting this here alongside @taylordowns2000 in Accra, Ghana! Hello OpenFn team!)

**Comment by taylordowns2000** [comment]
Found a super quick way to repro this: https://www.loom.com/share/055ad9b02c06471f9e9034b5b1ff4e80

**Comment by taylordowns2000** [comment]
@elias-ba , heads up that i think i've tracked this down to https://github.com/OpenFn/lightning/commit/3fa40f9cc2afad955efd91337dd3617d5ca32b87 and may need your help on Monday AM. (i've notified @stuartc about this too.)
