### ISSUE TITLE
Usage tracker can cause OOM restarts

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2636]
This is a placeholder issue until we have more data. For now, it seems that we can run into memory problems when the Lightning.UsageTracker.ReportWorker runs.

In Oban, the jobs appear to be "executing" when in reality they are all orphaned after they (most likely) are the cause of an OOM restart.

**Comment by rorymckinley** [comment]
@taylordowns2000 I think we saw a once-off issue similar to this earlier this year - happy for me to take a look once I am done with the work around auditing?
