### ISSUE TITLE
Implement Git Hooks to improve the engineer experience

### ISSUE THREAD

**Issue by NickGowdy** [OpenFn/Lightning#269]
**Problem description**

When working on a feature, the engineer has to do several checks (via commands run locally) to confirm that the application will build in Circle CI. With the use of Git Hooks (or something similar) we can make these steps automated. 

**Solution**

Git Hooks works by defining actions for different git steps (pre-commit, pre-push etc). To implement this as a feature, we would have to identify which tasks should run for different git steps that make sense for the dev workflow.  For example, running `mix format` before git push so the build doesn't break if the formatting of an elixir file is incorrect.

This is the Git Hooks repo: [https://github.com/qgadrian/elixir_git_hooks](https://github.com/qgadrian/elixir_git_hooks)

**Additional context**

I had to do additional commits for: [https://github.com/OpenFn/Lightning/pull/218](https://github.com/OpenFn/Lightning/pull/218) as my formatter in vs code doesn't work properly for HEEX files.

**Comment by stuartc** [comment]
@NickGowdy have you tried the `mix verify` alias task? It's set up to do all the same checks CI does in one command.

```
...
      verify: [
        "coveralls.html",
        "format --check-formatted",
        "dialyzer",
        "credo --all",
        "sobelow"
      ]
```      

Also the `coveralls.html` task creates an html version of the coverage report in `cover/excoveralls.html`.

**Comment by taylordowns2000** [comment]
Going to close this for now. @NickGowdy , if `mix verify` doesn't solve the problem you're hoping to solve, feel free to re-open this and propose a way forward! Thanks again for contributing :-)
