### ISSUE TITLE
Don't lose unsaved changes in the job editor

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/Lightning#280]
## The Problem

When making changes to a job, a user's changes aren't saved until the "save" button is pressed (this itself is arguably a little bit anachronistic).

If the user refreshes the page, navigates away or goes "back" (easily done with a misplaced gesture), all changes will be lost _without warning_.

This is particularly painful when writing job code.

## Solutions

Here are some approaches to helping this problem.

* Warn before navigating away with unsaved changes (this is what I would expect)
* Save every keystroke as changes come in (this is common, but I do want to be able to hit Cancel to revert changes)

**Comment by taylordowns2000** [comment]
closing this in favor of #780
