### ISSUE TITLE
Configure project from code (api/PUT)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#288]
### User story
As a developer configuring a Lightning project and writing my jobs in my code editor, I want to configure and deploy my changes to my Lightning instance through the command line, so that I don't have to make the changes manually through the UI. 

### Details
Create an API endpoint which, given a project.yaml and/or some files, can configure a project on lightning.

### User acceptance criteria
- [x] When I deploy a project which already exists in Lightning, it doesn't create a new one but rather updates the existing one. 
- [x] If my lightning instance and my project as code have a job expression with the same id but different values, the lightning instance's job expression gets update with the new job expression.  
- [ ] ~When I deploy a project which is scheduled for deletion, I get an error.~ (moved to #876 )

**Comment by taylordowns2000** [comment]
@amberrignell , user acceptance testing

1. update in place, yes
<img width="735" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/92304c99-1a04-4871-a192-10a43a0cffc5">

2. rewriting job code, yes
<img width="917" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/d94efca9-3cc3-460e-bb57-3d17bf984b56">

3. error when trying to deploy to project marked for deletion, no
<img width="506" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/d2e3ceb5-d812-428d-93e3-729be69e50de">
