### ISSUE TITLE
Automated GitHub commits via "sync" from Lightning button

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#289]
### User story

As a user that does not know how to use Github and wants to make changes via the Lightning UI, I'd like a way to "sync" my changes to Github so that I can benefit from version control.

As an implementation consultant that's working on a project with customers, I want my customers to be able to sync to github, so that I can keep track of what they've changed.

As a user that is conscious about version control and auditability,
I would like users to be able to commit changes they have made via the UI to github
- so that I know who has changed what and when
- (so that I can revert back to an old version if needed <- this would be manual, not a feature for now)
- so that I can understand what changes were made if a workflow breaks to more easily debug it

### Details

**1. Install github app on user's account**
 (a) A user can connect their github account in "profile settings: 
![Screenshot 2023-07-03 at 15.17.48.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/4e10cb81-c52a-4064-99da-5b0066d8f478)

 (b) When they click connect, they're taken through a flow which installs the openfn lightning github app on their account, and has permissions to read their repository names. 

 (c) Once connected, they can see which account is linked and disconnect it if they so wish. 
![Screenshot 2023-07-03 at 15.19.35.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/2226d79f-5918-4b36-b465-39b4e9f0a4bb)

**2. Configure github app for a repository**
(a) If a user **hasn't** installed the openfn github app on their account, they can see the feature is available but are prompted to connect their account to access it. The "Connect to github" takes them through the same flow at n.1
![Screenshot 2023-07-03 at 15.26.51.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/d3fc76e0-423a-4c07-bb52-c6abb83f1d3b)

(b) If a user **has** set up their github, they can select a repository and configure the app on it. 
In project settings, there is a Button "Connect to a github repository". 
This allows the user to select a repository, then click "connect". 

Note: this image is a mockup, the proportions don't have to be identical
![Screenshot 2023-07-05 at 12.07.37.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/82fc9dc8-8d13-408e-8794-22dcaaa55103)

When they click "connect", the user is taken to the github repo>github apps>lightning app>configure page to configure the lightning app for their repository. 

(c) Once a project has been connected to a github repository, the repository name is displayed and that same user can disconnect it 
![Screenshot 2023-07-05 at 12.22.23.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/4f96ec08-4a3e-4cfd-b48a-d773cece159b) 

3. On the workflow canvas, there is a "commit to github"  button which triggers the github app and 
(a) sends the information for the commit (ie user that just clicked "commit to github"
(b) calls `openfn deploy --describe` to get the current project.yaml and state.yaml for the project
(c) makes a commit to github with these changes and the user information in the commit message

4. If the user has not connected a github repository, the "commit to github" button on the workflow canvas is disabled, and it has a message saying "Connect to github in project settings to use this feature" on hover. 

### Implementation notes

- The _agent_ that triggers the github action via a **repository dispatch** message should be an OpenFn "github app", _not_ an individual user: https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps.
- This github app must have the [repository dispatch event](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event) permission
- Learn more about GitHub apps that act on their own: https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps#github-apps-that-act-on-their-own-behalf

**Comment by zacck** [comment]
@amberrignell @taylordowns2000  just to be clear the scope of this ticket is to build the github app and the associated github action ?

**Comment by zacck** [comment]
Hey @taylordowns2000  so the solution requires both, the APP will be used for authorization and to receive the github commit message and the action will do the bulk of the syncing, i.e pull the changes from the instance and commit them to the repo

**Comment by zacck** [comment]
Updated implementation flow![image (1).png](https://images.zenhubusercontent.com/64802dc6c3619a5e992b4706/f3b9e6f0-d1a5-4f81-8aba-3cfb5eba37b2)

**Comment by taylordowns2000** [comment]
closing this because we are now implementing #970 instead. i will bring over review checklists to the new issue
