### ISSUE TITLE
A function that generates a string for project.state.yaml

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#313]
Alongside #310 , we need a function which, when called with a project, returns a representation of that project's entities with their names and uuids.

The resulting string should follow this convention: https://github.com/OpenFn/projects-as-code/blob/main/examples/canonical-1/myProject.state.yaml

**Comment by amberrignell** [comment]
Closing as covered by https://app.zenhub.com/workspaces/product-engineering-6305f22ada44914905485ab1/issues/gh/openfn/lightning/633
