### ISSUE TITLE
Change 'new job' button to 'new workflow'

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#335]
### User story
As a user that is new to Lightning, I would like an obvious way to create a new workflow in a project, so that I don't waste time figuring out how to do it. 

### Details
1. Change the 'New job' button to 'New workflow'. 
![Screenshot 2022-09-23 at 14 28 16](https://user-images.githubusercontent.com/36554605/192205622-ee5df463-623d-41ab-9050-cd1551608e4e.png)

When a user clicks 'New workflow', create a new job for them with trigger type set to webhook (and therefore create a new workflow). 
@taylordowns2000 this is where I find it weird that creating a workflow is the side-effect of creating a job, but that's an engineering decision to if you're happy with it I'm happy with it. 

2. Add a new input to the 'edit worklow name' box to include 'workflow trigger'. 
![Screenshot 2022-09-26 at 09 17 57](https://user-images.githubusercontent.com/36554605/192206231-d1415303-a027-4304-b739-8f7a4ef42835.png)

3. Direct the user to that panel (https://..../w/123abc) when they create a new workflow

### Implementation notes

@elias-ba , Stu and I will weigh in on this tomorrow!

### QA
There is a 'new workflow' button on the workflows page. 
When I click that button, it should display the workflow panel. There should be a 'workflow trigger' input with a dropdown that has webhook or cron. 
When a user selects webhook or cron, it should update the trigger for the first job in the workflow.

**Comment by elias-ba** [comment]
@taylordowns2000 @amberrignell there are some things I do not find very clear on this issue. The new `workflow_trigger` we add to the edit workflow name form, what is it's purpose ? Should it be a select box for changing a workflow from webhook to cron ?
