### ISSUE TITLE
Remove success alert after set timeout

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#340]
Notifications that the user _probably will take for granted_ such as "Job saved successfully" should auto-clear.

**Describe the bug** A clear and concise description of what the bug is.
When a success alert appears, it does not go away until I leave the page or click elsewhere. 

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'workflows'
2. Click on 'New job'
3. Create new job and click 'save'
4. See 'Job created successfully' which never disappears

**Expected behavior** A clear and concise description of what you expected to
happen.
The alert should disappear after 5000ms

**Screenshots** If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/36554605/191465113-ca5d2ab3-8a27-460e-a79e-dabc6a50aa25.mov

**Additional context** Add any other context about the problem here.

**Comment by amberrignell** [comment]
@taylordowns2000 could you confirm this is a good first issue and if so add the tag ?

**Comment by taylordowns2000** [comment]
@elias-ba , check this out: https://elixirforum.com/t/flash-message-to-disappear-after-5-seconds/32285/2

You can achieve that with something like this:

Send a message to self when you use put_flash
```ex
Process.send_after(self(), :clear_flash, 5000)
```
Then, in handle_info:

```ex
def handle_info(:clear_flash, socket) do
  {:noreply, clear_flash(socket)}
end
```
