### ISSUE TITLE
Loading adaptor operations takes too long

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#343]
**Describe the bug** A clear and concise description of what the bug is.
Loading the dropdown of available operations for an adaptor takes too long. It's frustrating and slows down the building experience ...

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'Workflows'
2. Click on 'New job'
3. Select the language-common adaptor 
4. See the loading bar appears for a very long time before the operations dropdown shows up

**Expected behavior** A clear and concise description of what you expected to
happen.
Loading time should be minimal. 

**Screenshots** If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/36554605/191520021-d43e3df3-89ca-449d-8926-927f4a0a68fd.mov

**Additional context** Add any other context about the problem here.

**Comment by taylordowns2000** [comment]
@amberrignell , @stuartc , how about we:

1. create a function which, when called, loads the language package requested for a given running node (instance  of lightning) - this probably already exists in `Lightning.AdaptorRegistry`
2. call a number of these at startup for known/recommended adaptors so it's not so slow.
3. fix the bugginess around changing between adaptors/adaptor versions.

**Comment by stuartc** [comment]
Moving back from ready, we don't have a solution planned out for this just yet.

**Comment by amberrignell** [comment]
Addressed by #444 and #524
