### ISSUE TITLE
Runs history queries (1/2) - runs history collapsed view

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#346]
### User story
As a user monitoring my workflows, I would like to determine the final status of a WorkOrder run, so that I know if every step has completed successfully. 

### Details
Given a project ID and a WorkOrder, return the final status of a workflow run. 

### Implementation notes
See this document for notes: https://docs.google.com/spreadsheets/d/1YvvskT8pJckTVbc18JW0qo38pNAjlgLp2OM7ZRx2QCk/edit#gid=0

### Tests
Given a workflow with Job A, B and C. 
When run A,B and C are successful, I expect to see a wokflow run status of 'Success'. 
When run A and B are successful but C fails, I expect to see a wokflow run status of 'Failure'. 
When run A times out, I expect to see a wokflow run status of 'Timeout'. 
When run B crashed, I expect to see a wokflow run status of 'Crashed'. 

@taylordowns2000 should this implementation be returning status codes that then get changed in the UI or the actual words 'Success', 'Failure' etc ?

**Comment by amberrignell** [comment]
@wanecode if there is no workflow name, please write 'Untitled'.

**Comment by wanecode** [comment]
@amberrignell. you can check the Untitled in case of no workflow name

**Comment by wanecode** [comment]
@amberrignell. I added also the sticky header for work_order list. Had to replace the table layout. Stickyness of header (thead) is too hacky for tables and i may imply some changes to the root layout. cc @stuartc
