### ISSUE TITLE
Add Invocation Reasons

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#354]
Currently we record every 'Invocation' on the `Invocation.Event` model. This model connects a Run to a Job, but also contains all the associated data that the run must be processed with.

The reason for an Invocation Event is assumed to be 1-1 with the Jobs trigger.
This design does not accommodate several new reasons we need to track.

The InvocationReason is a place to persist _how_ a workflow was started or interacted with.

Create a new model called `InvocationReason` (`Lightning.InvocationReason` - _not inside a context_) with a table containing the following foreign keys and columns:

- trigger_id -> triggers
- user_id -> users
- run_id -> runs
- dataclip_id -> dataclips
- type (`varchar(20)`)

The model must validate the following:

- `type` cannot be blank.
- with `webhook` type:  
  - `trigger_id` can't be blank
- with `cron` type:  
  - `trigger_id` can't be blank

> See existing `Invocation.Event` module for reference.

Create a module (name pending) that will contain functions to create and validate the following kinds of InvocationReasons.

- `webhook`
- `cron`

There will be others as we migrate our database schema.

**Comment by taylordowns2000** [comment]
Looks good, @stuartc ! Can you add an estimate?
