### ISSUE TITLE
Redundant user feedback message

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#368]
### User story
As a user that is not logged into Lightning, I would like to not see the message 'you must log in to access this page', so that I do not have to read redundant text 

### Details
It is already obvious to a user that they have to log in because they are on the login page. 

![Screenshot 2022-10-18 at 19 40 13](https://user-images.githubusercontent.com/36554605/196491765-0a4fe9d7-0c23-4dc7-882e-67513463524b.png)

**Comment by NickOpenFn** [comment]
Resolved with recent release
