### ISSUE TITLE
`credentials` are not saved after job edit

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/Lightning#388]
**Describe the bug** A clear and concise description of what the bug is.
When your editing an existing job, the credentials that you selected from the dropdown are not saved after you click `save`
**To Reproduce** Steps to reproduce the behavior:

1. Click any existing job that is available on your workflow to edit
2. Click on the 'Credential select box'
3. Select the credential for that job 
4. Save the job
5. Open the job again 

**Expected behavior** A clear and concise description of what you expected to
You suppose to see the credential that was selected 

**Screenshots** If applicable, add screenshots to help explain your problem.
https://user-images.githubusercontent.com/6592749/198078794-d31b397b-5373-4231-b45b-b0c573add633.mp4

**Additional context** 
The screen record had a bug that doesn't show the select dropdown, So don't be alerted the credential dropdown will appear once you click the credential  select box

**Comment by mtuchi** [comment]
This is a screenshot of a job that already has credentials that were added to the job during creation and tried to select the credential again after editing the job  but the credential input is not showing the selected credential for this job 
![Screenshot from 2022-10-26 19-20-27](https://user-images.githubusercontent.com/6592749/198080628-f27f1d06-db14-4cf9-bc8f-c8ce829f78c7.png)

**Comment by wanecode** [comment]
I reproduced the bug. It's a regression from a refactoring job changeset and multi (new JobForm concept) cc @stuartc
