### ISSUE TITLE
Retry an attempt run

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#395]
**User story**
As a user that can see a workflow has failed in the runs history, I would like to retry it through the click of a button, so that I don't have to trigger another run with the same input manually. 

As a user that has retried a run, I would like to see it grouped alongside the first attempt, so that I can visually understand that it was a retry.

As a user that has retried a run, I would like its status to update the status of the workflow in the collapsed view, so that if it is successful I know the request has been processed correctly and I no longer have to 'deal with it'. 

**Details**
Add a 'retry' button to the UI in the runs history. On click, it should trigger another run with the 

Out of scope: retrying from a later job in a workflow and copying over the previous steps. 

**Implementation notes**
Do this the quick way for now - ie reload the data to show updates. Chat to Stu about considerations for long term implementation with live updates.

**Release notes**
Retry a workflow run 

**User acceptance criteria**
There is a retry button on the expanded view of the runs history page. 
When I click it, a new row appears **above** the last run.
When I reload manually, I would like to see the current 'workflow' status.

**Comment by taylordowns2000** [comment]
@amberrignell , this one is tricky — it feels unnecessary once the inspector works properly when accessed from the Runs History page. Let's discuss briefly during standup tomorrow.

**Comment by stuartc** [comment]
You should not be able to retry a run/attempt while it is in progress.

**Comment by stuartc** [comment]
Things still to do:

- [ ] Don't allow an attempt to be rerun if it's still in progress.
- [ ] Update the run when it finishes (i.e. proper reactive changes)

Bonus:

- [ ] Animate only new attempts, while showing existing ones as static.

Important going forward:

- [ ] Plan out and represent the different kinds of events and changes that a LiveView would subscribe to.  
  For now the subscribe and broadcasts are written directly in the LiveView.
