### ISSUE TITLE
Unable to save new job

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#399]
**Describe the bug** A clear and concise description of what the bug is.
When I create a new job in a project, the save button is disabled and I am unable to save it. 

**To Reproduce** Steps to reproduce the behavior:

1. Create a new project.
2. Click on 'new job'
3. Fill out requested fields
4. See 'save' button is still disabled. 

**Expected behavior** A clear and concise description of what you expected to
happen.
Save button should be enabled. 

**Screenshots** If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/36554605/199419176-e92db12e-7434-4c4e-99f4-2dd3eefa63b8.mov

**Additional context** Add any other context about the problem here.

**Comment by stuartc** [comment]
Should be fixed in #341
