### ISSUE TITLE
Load adaptor documentation

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#407]
### User story
As a user that's writing a new job, I would like to see the adaptor documentation when I'm writing a job, so that I know which operations I can use and how. 

As a non-technical user, I would like to see which actions/operations are possible in different systems, so that I can start planning my workflow. 

### Details
Currently, the adaptor documentation isn't loading in the adaptor docs component. 

### Release notes
Show available operations for any adaptor. 

### User acceptance criteria 
Given a user selecting any adaptor and set the version to latest, when I go to the editor, then I can see a dropdown with the available operations for that adaptor.

**Comment by josephjclark** [comment]
This is tracked over in Adaptors https://github.com/OpenFn/adaptors/issues/126

I thought it was a problem in how we were bundling type definitions, but if the issue is still there since the latest release last Friday, I guess not :(
