### ISSUE TITLE
Show user when loading new adaptor documentation 

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#444]
**Describe the bug** A clear and concise description of what the bug is.
@josephjclark not sure if this is on your radar but currently when a user selects a different adaptor for a job, they are not shown that new documentation is loading - and since it takes a while it looks like it is just not updating. 

**To Reproduce** Steps to reproduce the behaviour:

1. Go to workflows and click on a job
2. Select a different adaptor
3. Go to the editor, and see it is displaying the previous adaptor docs [if you wait a while, the docs do update - it's just that it takes so long that it initially looks like nothing is happening]

**Expected behavior** A clear and concise description of what you expected to
happen.
Ideally load the documentation faster, but for now at least show the user that the docs for the newly selected adaptor are being loaded. (like when documentation is loaded for the first time)

**Screenshots** If applicable, add screenshots to help explain your problem.

https://images.zenhubusercontent.com/454419290/d3e5133e-5d63-4b20-a283-48753a8ce523/screen_recording_2022_11_22_at_11_13_58.mov
**Additional context** Add any other context about the problem here.

**Comment by josephjclark** [comment]
This should be sigificantly improved (if not "fixed" ) by https://github.com/OpenFn/kit/pull/92

The loading message is more responsive, but the load is still slow and doesn't give good feedback about what's happening.

I have a cunning plan to push the logic server-side which will really speed things up - that's dependent on https://github.com/OpenFn/kit/issues/91 which I intend to do very soon.

**Comment by amberrignell** [comment]
Fixed
