### ISSUE TITLE
Long job names are ugly and confusing on the canvas

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#447]
When a job name has too many characters, it overflows past the job node.

We could:

1. Set a character limit to prevent this from happening
2. Truncate the job name and show an elipsis, then display the full name on hover
3. Something else?

**To Reproduce** Steps to reproduce the behavior:

Create a long name for a job then view it from the canvas.

**Screenshots** If applicable, add screenshots to help explain your problem.
![Screenshot 2022-11-22 at 12.24.07.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/6aa7b510-648d-40ac-8424-8a8aaae127d3)

**Comment by amberrignell** [comment]
Truncate the job name - when user hovers over it, display full name. (from discussion @mtuchi )

**Comment by taylordowns2000** [comment]
re-opening:

- [ ] only truncate after 2 lines (maybe set a char limit rather than using the truncate property to make this work)
- [ ] keep middle vertical alignment for text
