### ISSUE TITLE
Scrub secrets from run_results

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#454]
Even if it's replaced with a more sophisticated system later, we need to prevent secrets from being written/shown in the clear while storing or viewing run_results.

This concept implementation does that, albeit in a pretty simple/clunky way and _only_ for `state.configuration`. Secrets stored in other parts of the run_result are not scrubbed because they may be used by subsequent jobs in a workflow. We need to decide how to handle this _later_.

We should create tests which:

- [ ] Show that secrets are not stored in `run_results` when left in `state.configuration`.

```ex
  @doc """
  Scrubs values from all keys in configuration, will be replaced by extensions
  to scrubber.ex, which is currently only used for logs.
  """
  @spec scrub_result(body :: map()) :: map()
  def scrub_result(%{} = body) do
    case Map.get(body, :configuration) do
      nil ->
        body

      map ->
        safe_body = body

        Map.keys(map)
        |> Enum.each(fn k -> Map.put(safe_body, k, "***") end)

        safe_body
    end
  end
```

**Comment by amberrignell** [comment]
@elias-ba I've set this as a 1 pointer because Taylor has completed the implementation and this issue is for the test described above. Don't hesitate to reach out if you have any questions

**Comment by taylordowns2000** [comment]
@elias-ba , two other tests need updating to reflect the scrubbing

**Comment by elias-ba** [comment]
I saw them failing in CI. Lemme fix them before moving to that next thing you wanna plug me in. @taylordowns2000
