### ISSUE TITLE
Run a job from any tab of the job inspector

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#466]
### User story
As a user that is building on the workflow canvas, I would like to be able to run a job from any tab in the job inspector, so that it is quicker.

Button should be greyed out if no input selected

### Details
Move the 'run' button to the top right of the job inspector (next to the different tab headings), so that it is available from all tabs.

### Implementation notes
Take the same approach as the save button that's available outside of the form component.

**Comment by taylordowns2000** [comment]
@stuartc , how close is this "move the button" story to achieving the blue button location and functionality on the diagram below? (And how much of the diagram below are you envisioning for December? That second one likely an offline conversation!)
![image](https://user-images.githubusercontent.com/8732845/204775108-3ee9f044-cb50-44ad-b65a-d4e4333fab05.png)

**Comment by taylordowns2000** [comment]
done!
