### ISSUE TITLE
cache credential schemas from npm 

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#471]
### User story
As a user that would like to build a workflow, I would like to be able to create my credentials through a form, so that I know what is required and I don't have to look at the adaptor documentation.

### Details
- This list of schemas can _not_ include any schemas that rely on Oauth. They won't work. (Dynamics, GoogleSheets, others?)

### Implementation notes
Write a mix task to pull down a predefined list of credential schemas from unpackage / js deliver and show those credentials schema options in the credential form

### Release notes
- Create any credential through a form except for OAuth

### User acceptance criteria
- Given a user has just selected "new credential", when they select the type dropdown, there is the same number of credential options as adaptors. 
- When a user selects a credential for an Oauth, they can see an alert that says 'This credential requires OAuth authentication, we do not currently support it.'

**Comment by taylordowns2000** [comment]
@stuartc , does this envisioned script write/update files here https://github.com/OpenFn/Lightning/tree/main/priv/schemas and is the result committed to github?

**Comment by stuartc** [comment]
> @stuartc , does this envisioned script write/update files here https://github.com/OpenFn/Lightning/tree/main/priv/schemas and is the result committed to github?

I imagine they would be stored somewhere like that, however I don't think the results should be committed to github... more of a cache artefact of a build (ala docker/local).

Eventually it should only download the schemas for adaptors the system is aware of.

**Comment by taylordowns2000** [comment]
See https://github.com/OpenFn/Lightning/pull/542 if you're building this locally @wanecode

**Comment by wanecode** [comment]
I added an  "--exclude" argument so we can prevent downloading specific packages.
Ex:  --exclude language-biqquery language-googlesheet

**Comment by wanecode** [comment]
language-common and language-devtools are excluded by default.
