### ISSUE TITLE
Trigger downstream job when upstream job run failed

### ISSUE THREAD

**Issue by elias-ba** [OpenFn/Lightning#508]
### User story
Oban manager marks a run as finished when it's failed. This is the current implementation / solution we took to solve #474. It's not perfect and the main side effect is that if the job associated to that run has downstream jobs, they won't be executed as the run is marked as finished. We should find a better way of solving that problem.

**Comment by taylordowns2000** [comment]
@elias-ba , the solution is part of the sample code I provided for your migration of the "oban manager" from platform-app to lightning in #474 - i was not expecting that you'd cut out the "downstream jobs" part of that migration. you may have a good reason for dropping it but i can't see it in these notes. let's discuss when you're back online?

**Comment by amberrignell** [comment]
Still an issue. To reproduce, create a job which times out with a downstream on failure job
```
fn(state => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log('wait, and then resolve');
      resolve(state);
    }, 65 * 1000);
  });
});
```
See downstream 'on failure'  job doesn't get executed

**Comment by taylordowns2000** [comment]
OK, thank you @amberrignell . We may be nearing a solution to this via the new runtime manager, so I'd propose that we keep it on the backlog but make it lower priority than RTM and the Lightning APIs that will interact with the RTM.

Once the "responsibility" to execute an attempt for a workorder is pushed down to the RTM, an Oban error (in the Elixir app) will not be responsible for starting downstream jobs... as _nothing_ in Elixir will be responsible for starting downstream jobs.

**Comment by taylordowns2000** [comment]
Confirming that this is now handled by the worker
