### ISSUE TITLE
output message does not update if job is run and no output to show

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#532]
**Describe the bug** A clear and concise description of what the bug is.

When 
- case 1: a job which does not return anything is run, 
- case 2: a job which fails is run,
the following message remains on the output tab "Nothing here yet.The resulting dataclip will appear here when the run finishes successfully.". 

**To Reproduce** Steps to reproduce the behavior:

1. Create a job which does not return any output
Case 1: nothing returned
```
fn(state=> {
    console.log(state)
})
```

Case 2: failing job 
```
fn(state=> {
    throw "error"
})
```

2. Run it 
3. See output tab displays the following: "Nothing here yet.The resulting dataclip will appear here when the run finishes successfully."

**Expected behavior**

Case 1 (nothing returned) should display: "There is no output for this run. Check your job expression to ensure that the final operation returns something."
Case 2 (job fails) should display: "This run failed; there is no output. See the logs for more information."

**Comment by taylordowns2000** [comment]
@amberrignell , please describe what you expect for both example 1 and example 2 above. and format them nicely using bold and line breaks so it's easier to see.
