### ISSUE TITLE
Retry button not showing

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#538]
**Describe the bug** A clear and concise description of what the bug is.
On the runs history page, the retry button does not show up even though it is clickable. 

**To Reproduce** Steps to reproduce the behavior:

1. Go to runs history
2. Move the mouse to the right of a run and click
3. See run is retried, BUT user cannot see the button. 

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

![Screenshot 2023-01-06 at 12.22.12.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/a79a7195-70b4-4f51-bb09-ec228d33cb09)

**Additional context** Add any other context about the problem here.

**Comment by taylordowns2000** [comment]
@amberrignell , screenshot please! and open up the chrome inspector so we can see the element (if it's there but hidden.... wasn't this some sort of font/display issue?)
