### ISSUE TITLE
Dataclips displaying incorrect type?

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#539]
**Describe the bug** A clear and concise description of what the bug is.

When I click on an input from the runs history, that input shows up as "global". 
Instead, this should be displayed as "http request" 

**To Reproduce** Steps to reproduce the behavior.

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by taylordowns2000** [comment]
I'm 90% sure that this will "go away" after the dataclips show page is made read only. The type was only set to global because when you edit an http_request, it _becomes_ a global.
