### ISSUE TITLE
Code-assist not working for many old adaptor versions

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/Lightning#549]
Turns out there's an issue in some of the new type definitions for adaptors. This means that hovering over an operation name in the editor will just say something useless like `export fn`.

This is mostly tracked over in `adaptors`, see https://github.com/OpenFn/adaptors/issues/190

But as it affects Lightning most severely I wanted to track it here with this companion issue.

**Comment by josephjclark** [comment]
@mtuchi has fixed a big chunk of this from the adaptor's end.

Some adaptor versions will remain problematic I'm afraid - those with published and incorrect definitions. Honestly that means most non-latest adaptor versions are broken.

There is still an outstanding problem which I've spun out into its own issue: #596

**Comment by taylordowns2000** [comment]
not fixing this. support is there for all new versions and the old ones will probably never be used on lightning
