### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#571]
As a new user of OpenFn Lightning, I would like to know that load testing has been carried out, so that I am aware of the application's performance. 
-> side effects of database sockets closing + app performance limitations

1. Decide _what_ to test - hypothesis about the things that matter / what can go wrong / what can be slow.
2. Implement test harness. 
3. Decide how to measure failures / performance / characteristics of how it behaves- benchmarking.

@taylordowns2000 could you pull out any work on platform-app that would be relevant to this?

**Comment by taylordowns2000** [comment]
Yes! The biggest challenges we've had in v1 relate to:

1. Multiple users doing heavy runs/messages queries at the same time on large activity projects
2. Lots of work order requests to /inbox in a very short period of time
3. Lots of jobs being executed at the same time
4. And #3 but with large memory usage... so picture a large number of NodeJs jobs all with exploding memory consumption at the same time.

**Comment by amberrignell** [comment]
Liveview keeps track of many changes, so we need to know based on the number of users and projects, how much memory will be taken up. -> can test this with something like puppeteer to run remote browser sessions
