### ISSUE TITLE
Github integration

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#575]
As a developer, I would like test and edit my jobs locally, push them up to github for version control and review, and have automatic deployment when I commit to main. 

As a user that is conscious about version control and auditability,
I would like users to be able to commit changes they have made via the UI to github
- so that I know who has changed what and when 
- so that I can revert back to an old version if needed
- so that I can understand what changes were made if a workflow breaks to more easily debug it 

![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/a0e5fc73-6861-4e8d-9c57-35863db41ada)

**Comment by taylordowns2000** [comment]
closing this epic in favor of #297
