### ISSUE TITLE
Apply filter behavior on "History" to `WorkOrders`, not `Runs`

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#592]
**!! Work on the `592_history_filters` branch** as it has cosmetic changes that have already been made and must be retained.

Currently, the filters on the history page (date, workflow, and status) are applied to _runs_, not to `WorkOrders`.

- [ ] Make the "status" filter work on the `WorkOrder` status, not the `Run` status.
- [ ] No change is required to the behaviour of the "workflow" filter — it should always be the same whether on run or attempt or workorder. If a slight change here will protect us against future complications, please make it. If not, leave this as is.
- [ ] Remove the current "date" filter in favor of two different filters:
- [ ] add a "Filter workorder by date received" which returns workorders whose `workorder.inserted_at` is ≥ "after" and ≤ "before".
- [ ] add a "Filter workorder by last activity date" which returns workorders where last run finished at ≥ "after" and ≤ "before".
- [ ] Update the tests so that we can see each of these behaviors in action.

Leave the search component as it is now. This will be handled in another issue.

The guiding principle here is that these filters are all filtering at the WorkOrder level—they control the things that you see in the fully collapsed view. Once a user "expands" a WorkOrder with that dropdown icon, they get way more data than what they filtered. We will handle how that "expansion" becomes intuitive later.

cc @amberrignell , @stuartc , @wanecode 

## desired front-end. (already built; see branch @wanecode !)

note that this PR should be opened with the follow text/disclaimers intact. we'll modify them later.

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/8732845/211791531-69b709cb-10aa-42fb-857d-e46bd7487f71.png">

**Comment by wanecode** [comment]
PR opened for status but we need to set correct status for runs:
https://github.com/OpenFn/Lightning/blob/ddf14567c3dc624cc72c60efea7c83e7b10d70b4/lib/lightning/invocation.ex#L338


![image (5).png](https://images.zenhubusercontent.com/63108656807f915a6a4da2dc/a1d32329-ee4d-424b-abc7-f8946ace7466)
