### ISSUE TITLE
Credential schemas not loading through docker deployment

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#604]
**Describe the bug** A clear and concise description of what the bug is.
When you spin up an instance of lightning using docker, the credential schemas are not loaded. 

**Expected behavior** A clear and concise description of what you expected to
happen.
Schemas should be loaded through the docker image

**Comment by taylordowns2000** [comment]
@amberrignell , @wanecode , @stuartc - I think that this issue should be addressed alongside #626 - both _may_ involve the docker image, and to solve both you'll likely need to build a local docker image.
