### ISSUE TITLE
language-common docs don't load on first try

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#615]
**Overview:**
When I register for a new account and click on the example workflow, the language-common docs don't load unless I unselect then reselect that adaptor type. 

**To Reproduce:**

1. Register for a new account
2. Click on 'sample workflow'
3. Click on the 'Convert to OpenHIE' job, then head to input tab
4. See the docs do not load. 

**Screenshots** 

https://user-images.githubusercontent.com/36554605/214829729-2808cd7f-7372-4bfb-b3cc-969fc7bde608.mov

**Comment by josephjclark** [comment]
I'm having a hard time reproducing this locally but I can reproduce on app.openfn.org.

The problem is that, for some reason, a version number is not passed through to the docs component.

This should be sorted out by `@resolved_job_adaptor` but for whatever reason it is not :(

**Comment by josephjclark** [comment]
I've retested this and it looks fine to me right now.

I'm going to close it out (if it crops up we can reopen)
