### ISSUE TITLE
Credential info not showing on edit

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#623]
**Describe the bug** A clear and concise description of what the bug is.
When I edit a credential, I cannot see the existing values for the credential fields

**To Reproduce** Steps to reproduce the behavior:

1. Create a credential
2. Click edit
3. See the fields values are not displayed

![Screenshot 2023-02-08 at 11.59.10.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/2fc847c4-23af-4349-98fb-fc4ca77e01e0)

**Expected behavior** A clear and concise description of what you expected to
happen.
I would expect the credential fields to show the current values

**Comment by stuartc** [comment]
The docker image appears to have a default pwd of `/app/bin` and the lookup path for the schemas is `./priv/schemas` - the schemas are located at `/app/priv/schemas`. We need to either change the pwd of the container or change the lookup path during runtime/on the application.

**Comment by amberrignell** [comment]
Putting on hold as this may be fixed by the Oauth issue
