### ISSUE TITLE
Fix flaky test failure_alert failing workflow sends failure email to user having failure_alert to true

### ISSUE THREAD

**Issue by wanecode** [OpenFn/Lightning#628]
![image](https://user-images.githubusercontent.com/60378381/217559464-7db2aabe-a249-4871-9b7b-e6f323f060a1.png)
https://app.circleci.com/pipelines/github/OpenFn/Lightning/2248/workflows/61e5cf69-eb3b-4c85-baaa-9b9db5d1d6b1/jobs/10692

**Comment by amberrignell** [comment]
duplicate issue (see [here](https://app.zenhub.com/workspaces/product-engineering-6305f22ada44914905485ab1/issues/gh/openfn/lightning/666)) - already addressed
