### ISSUE TITLE
Create a project in Lightning from the CLI

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#633]
### User story
This is part of the github integration epic. 

@amberrignell , @josephjclark , @wanecode , @stuartc , Mamadou and I have added this diagram:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/8732845/218125828-ae2379b6-29ab-4107-bab0-a84975e64a2a.png">

#574 delivered a function that, given a json object, creates a new project in Lightning. In this next step we want to do this through the CLI. 

**Given a project.yaml file, create a project through the CLI.** 

### Implementation notes
- [ ] Add a new action to the cli @stuartc what should the command be called ?
- [ ] Make a client specifically for Lightning's API in kit that takes an API key and hostname 
- [ ] Write a function that reads the yaml file and turns it into json before sending it for use by import_project in Lightning 

### Release notes
- Import a project through the CLI (this creates a new project, updating a project will come at a later date). 

### User acceptance criteria
- [ ]There's a CLI command I can call which imports a project for me in Lightning 
- [ ] There is an authentication mechanism - if I don't have an account on Lightning, I am unable to deploy anything
- [ ] If I am creating a new project (which in this case I am), I must be a superuser. 

@stuartc are there any specific edge cases we should think about ? What will we need from Joe on this one ? 
@stuartc we'll have to think about permissions on this one. If we're creating a new project, should this person have to be a superuser to do this ?

**Comment by josephjclark** [comment]
This should probably be transferred into kit, although I appreciate you want to track it from the Lightning side :thinking: 

@mtuchi has raised a similar request to generate a local development project. Not for lightning, just for your file system. It may end up being the same thing.

Possibly `generate` and `deploy`  are two different subcommands of `project`, so you can do `openfn project generate project.yaml` and `openfn project deploy ./project-dir`.

An optional enhancement here would be to use an interactive CLI prompt to build a project.yaml if one isn't provided (particularly helpful for the local dev use case)

**Comment by amberrignell** [comment]
Closing as addressed by https://github.com/OpenFn/kit/issues/245
