### ISSUE TITLE
Allow users to edit project digest and alerts settings

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#638]
### User story
As a project user, I would like to edit the frequency of my project digest and alerts, so that I can be notified on failures and get a summary of my project activity at my desired frequency.

### Details
Context: issues [583](https://app.zenhub.com/workspaces/product-engineering-6305f22ada44914905485ab1/issues/gh/openfn/lightning/585) and [581](https://app.zenhub.com/workspaces/product-engineering-6305f22ada44914905485ab1/issues/gh/openfn/lightning/581) added the functionality to send users project digests and alerts on run failures at different frequencies. 

See rough sketch below for guidance:
![IMG_7401.jpg](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/02687ad4-78c2-4422-804a-755ac5d98345)

### Implementation notes
N/A - @stuartc please read through but since this is mostly UI I don't expect many notes, just an estimate.

### Release notes
- A user can enable/disable realtime alerts for a project.
- A user can edit the frequency at which they receive a project digest. (Possible values are never, daily, weekly and monthly)

### User acceptance criteria
- [ ] In project settings > collaboration there is both a "digest" and a "realtime alerts" column 
- [ ] A viewer, editor, admin or owner can edit THEIR OWN digest and alerts frequency: in the row next to their name, digest and realtime alerts are dropdowns that display the current value set for digest and realtime alerts.
- [ ] When an editor clicks the dropdown for digest, they can select from 'never', 'daily', 'weekly' and 'monthly'.
- [ ] When an editor clicks the dropdown for realtime alerts, they can select from "enabled" or "disabled"
- [ ] A viewer, editor, admin, owner can ONLY edit their _own_ digest and realtime alerts settings. The digest and realtime alerts values displayed for other users in the 'collaboration' section are read-only. 

~@taylordowns2000 this is where we need to start thinking about roles ... should a viewer be able to receive notifications and project digests ? And if not then we should set the default values accordingly. Will update the release notes accordingly after we've discussed.~ @amberrignell , everyone on a project should be able to edit their own notifications (seems like a good start) but we should implement these permissions via the permissions module anyway — and later we may add the ability for an admin/owner to edit the notifications settings of _other people_ who belong to their project.

**Comment by taylordowns2000** [comment]
@amberrignell , small changes made to the spec above. Looks great.
