### ISSUE TITLE
Lay down authorization across entire app

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#645]
### User story
As a lightning administrator, I would like authorization to be implemented for every key action carried out in Lightning, so that I can be sure that only those granted explicit access can view or edit important resources.

### Details
The pattern for authorization has already been laid out in [this PR](https://github.com/OpenFn/Lightning/pull/613/files). 

Using the pattern above, add authorization to the actions detailed in [this doc](https://docs.google.com/spreadsheets/d/1mlWjlvVdhupI3Ph0msf9nE2K7Uoe-qklOj81cG0N19c/edit#gid=547880405)

### Release notes
- [ ] Authorization for Lightning superusers and users, and project roles viewer/editor/admin/owner. See [link to test file] for more details. 

### User acceptance criteria
- [ ] The tests clearly communicate which actions different users can and cannot perform in Lightning. 
- [ ] These permissions are in line with the doc provided above.

**Comment by taylordowns2000** [comment]
@amberrignell , @stuartc — just reviewed this with @elias-ba and it looks like there was a misunderstanding around the scope of this issue. So far, "actions" (things like `:edit_credential`) have been _created_ but not _implemented_ in any live_views or controllers.

If this was the intent of the issue, we then need another issue (or issues) in which we actually implement authorization for the various actions in forms, controllers, live_views, etc. If not, then there's still quite a bit of work to do on this issue before it's ready.

Regardless of where we think that work should be tracked, it's got to be done so I've asked @elias-ba to start from the top of that spreadsheet and start _implementing_ the authorization policies he's created one by one. We can touch base on Monday and discuss how this impacts the next sprint/timelines in general.
