### ISSUE TITLE
Check and renew OAuth credentials when running a job

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#646]
Note: see work on branch `646-check-and-renew-oauth`

When an OAuth credential is correctly setup, and is used on a given job; it needs to be periodically refreshed.

Assuming (this is the case with all foreseeable OAuth tokens) the OAuth credential has a refresh token and an expiry.

The responsibility of this feature is to ensure that the job gets a working (and updated) credential.

## Scenarios

1. The expiry time of the `access_token` is greater than 5 minutes, continue with the existing credential.
2. The expiry time is either in the past or within then next 5 minutes, using the refresh token request a new `access_token`; once a new token is received, merge the response into the existing token, persist the changes and return it for use in the run.

**Questions**

1. The time frame proposed for 'near' expiry is 5min, is this long enough? Too short? [^expiry]
2. What do we do for a job when the credential can't be renewed on a run?  
   Do we just let it fail? Do we disable the credential or flag it for attention?  
   Do we disable the job? Knowing that the renewal happens outside of the run, we only have a few (reasonable) avenues to provide feedback.
   
## Additional context

1. This is a follow on from: #536, which is implemented in #620.
2. Read through the platform implementation [here](https://github.com/OpenFn/platform-app/blob/main/lib/open_fn/services/credential_service.ex#L102-L201)
3. Consider adding a `maybe_refresh` function [here](https://github.com/OpenFn/Lightning/blob/main/lib/lightning/pipeline/state_assembler.ex#L70) which checks the expiry date in the current credential body if it is an oauth credential, and refreshes it if it is out of date.

[^Expiry]: In the case of a long running job we want to make sure it is valid for the entirety of the execution time. In the case of _very_ long running jobs we may have to reconsider where we do the refreshing (possibly inside the job/adaptor). 
Another consideration is that token/auth providers have a limit on how many valid tokens are issued in a given timeframe, it's important to reuse a single token for as long as possible.

**Comment by stuartc** [comment]
> **Running a job** will:
> attempt to renew if necessary
>   if renewal fails it will update the credential metadata so that the "re-authorize" button is enabled if a certain error is returned when attempting to `renew`
>   the job will still run (and fail!) even if the `renew` is unsuccessful.

Moving over from #620

**Comment by amberrignell** [comment]
Closing the PR for now as it won't be worked on for a while. When you pick up this issue again please work on branch `646-check-and-renew-oauth` and see the work that has already been started there.
