### ISSUE TITLE
Stress load test 

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#654]
### User story
As a Lightning developer/contributor, I would like an easy way to test how Lightning behaves when it has a heavy workflow (many jobs to execute at the same time), so that I can trust it and be aware of its performance.

### Details

Create a test harness that allows us to programmatically create a set of jobs and push a configurable number of dataclips into the system.

We want to be able to profile variances of both message count and message size (many dataclips of different average sizes).

Things we need to measure at increasing levels of load:

1. Time to persist a dataclip
2. Time from dataclip created to start of job (per workflow).
3. Time to invoke a `fn(x) => x;` job (`run.started_at` to `run.finished_at`)

In order to get metrics out of the test run, we should strongly consider using the
telemetry library as these event/metrics can later be used for monitoring.

**Additional Metrics**

- memory usage
- cpu usage?
- atom count? (if this climbs linearly or significantly it could indicate a problem)

**Important observations**

- What happens when it fails?
- Does the rapid failure of other components (ecto/postgres) cause jobs to fail prematurely?
- How much does it take to make it break?

### Implementation notes

I think a good place to start is to write an exs script that can call a function in the app that is expected to produce a telemetry event. Then see how we can get telemetry events out (be it by filtering a log or writing to a file or another application)

### Release notes

- Stress load test: executing many jobs at the same time. 

### User acceptance criteria

- [ ] The test is NOT in our unit tests
- [ ] The test produces structured (CSV or JSON) data that we can easily chart and keep the results.

**Comment by stuartc** [comment]
@amberrignell I think we can merge #655 into this one... the majority of the work is creating a test harness that allows us to invoke workorders - the only distinction that #655 adds (assuming the prior work is done) is another test with a larger dataclip size.

I mean we can keep them separate if we like, but the second one will be dependent on the first.

**Comment by stuartc** [comment]
Just thinking out loud here: we should be using Telemetry in Lightning - lets give this some thought before we start it.
