### ISSUE TITLE
Bulk rerun work orders (from start)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#659]
### User story
As a user that had a workflow which was running successfully, who then realised the logic isn't what I wanted, I would like to be able to bulk reprocess workflows, so that each workorder can be rerun with my updated logic.

### Details
Allow users to select work orders from the history page
Allow users to reprocess the work orders they have selected

1. Selecting work orders
Using the [following component](https://tailwindui.com/components/application-ui/lists/tables#component-390db22a862687fe88b313692989ffaf), add a checkbox column to the history page. 

- There should be a checkbox in the first column (to the left of 'Workflow'). 
- Every work order should have a checkbox, unselected by default
- When the user selects the top-level checkbox in the column heading, all work orders on the page get selected
- A user can select several individual work orders using the checkboxes within the work order rows
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/8732845/230377675-8adb6a78-eff1-4674-a644-a8a8a290f790.png">

If a user has selected some work orders, then changes the filters, their selection is lost. 

2. Reprocessing work orders
- When a user selects either the top-level checkbox OR work order level checkboxes, a 'rerun from start' button should appear. 
- When the user clicks 'Rerun from start', the user should see a pop up modal which confirms which work orders have been selected (how many work orders will be reprocessed, and the search filters used to select these work orders)

Use [the following](https://tailwindui.com/components/application-ui/overlays/modals#component-f39bfe26a95719b1611d27f969be9a24) modal component

**A.Top-level select**
Message: `You've selected the number_of_workorders_on_page work orders from page age_number of results for workorders matching the following query search_params. There are a total of number_of_workorders_matching_query work orders matching this query.`

_Example: You've selected the 12 work orders from page 1 of results for workorders matching the following query:  received between x and y date, for workflow A, with a status of 'Failed'. There are a total of 32 work orders matching this query._

Buttons: Cancel, Rerun all work orders on this page from start, Rerun all work orders matching the query. 

![Screenshot 2023-04-12 at 10.28.24.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/34719035-177d-48b0-96c3-86346bb6a1b5)

 **B.Individual work orders selected**
Message: ` You've selected number_of_selected_work_orders work orders to rerun from the start (first job). This will create a new attempt for these within the same work order`
_Example: You've selected 12 work orders to reprocess from the start (first job). This will create a new attempt for these within the same work order._
Buttons: Cancel, Rerun from start

![Screenshot 2023-04-12 at 10.31.21.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/33aa0cc1-6fab-4d3b-9be5-a91f387671e8)

- When the user clicks 'Rerun from start', the users gets an alert "xx work orders will be bulk rerun" (so that they have feedback that their action was applied), and the work orders all get reprocessed in the same order in which they were received

### Implementation notes

Please read through the [platform-app implementation](https://github.com/OpenFn/platform-app/pulls?q=is%3Apr+is%3Aclosed+bulk) first
Write a function that can take a list of work order IDs  and create a new attempt for each one, in the order in which they have been passed to the function. 
Write a function that can take a query, and create a new attempt for each work order returned by the query, in the order in which they are returned.

The function rerun_run_from_start parameters would be: 
source: (list of IDs, or parameters) 
user: (used to add to the invocation reason)

### Release notes
- Bulk rerun work orders from start

### User acceptance criteria
- [ ] I can 'select all' work orders on the history page
- [ ] Work orders get reprocessed in the order in which they were received
- [ ] when I click 'Rerun from start', I see a pop-up which confirms how many work orders will be reprocessed, and the search filters used to select these work orders (ex: Reprocess 12 work orders which were received between x and y date, for workflow A, with a status of 'Failed')
- [ ] If a user changes the filters, they lose their selected items. 
- [ ] If I click the top level select, all workorders are selected. If I unselect one, the top-level select is also unselected. If I click unselect from the top level, all of them are unselected.

**Comment by taylordowns2000** [comment]
@amberrignell , tailwind component for this
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/8732845/230377675-8adb6a78-eff1-4674-a644-a8a8a290f790.png">

**Comment by taylordowns2000** [comment]
Useful naming content:
<img width="1086" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/4d1538f1-f719-4fa4-ac58-eefc92d1a4e5">

**Comment by taylordowns2000** [comment]
Possible approach:
1. see how "rerun" works currently in the liveview and/or service.
2. determine how a "batch" or a "query" of workorders could all be "rerun" using the current backend (maybe: is there a function that takes a list or workorder IDs and creates a new attempt for each workorder from the first job in the workflow with the initial state.)
3. write that function
4. then, consider how to pass workorder IDs from the UI (when i've selected 3 workorders) to that function.
5. for the modal, consider how to use the applied query (or "total" count as opposed to the paginated view) to give the user the option to send just those IDs select or ALL IDs regardless of current pagination.
6. send them for execution, display toast notification.

**Comment by amberrignell** [comment]
Hey @sigu , thanks for the questions!

To give a quick answer, 
1. Correct, attempt runs are a join table of attempts and runs (this is because two different attempts could have the same runs (if they get copied over for a “rerun from job 2” for example
2. A job is the adaptor, credential and job expression that a user has defined. A run is when that job has been run with some data (state)
3. A dataclip is the data that is used to run a job with

We'll see you in standup tomorrow so Stu can give you more details then, hope this helps in the meantime!

**Comment by midigofrank** [comment]
Hey @amberrignell @taylordowns2000 , should the `rerun from start` button get disabled / hidden when you don't have permission? Or should we allow the users to click around and get the notification error message

**Comment by taylordowns2000** [comment]
hey @midigofrank , who doesn't have permission? (have you created a policy for this action? sorry, i have not seen anything related to permissions in the issue.)

**Comment by taylordowns2000** [comment]
Cool. For now please allow the error flash to appear as we don't have a design that explains _why_ a user isn't able to run it. We can consider adding this later.

**Comment by midigofrank** [comment]
Alright. Perfect

**Comment by taylordowns2000** [comment]
hi @midigofrank , great q 😄 

No, the scope of this feature ends at `Oban.insert`. In other words, this feature is to "queue up" a bunch of attempts (same thing that clicking "rerun" really fast on a bunch of attempts does) but once they're on the Oban queue they're in a totally different domain.

**Comment by taylordowns2000** [comment]
So.... sorry to be extra clear: if there is an error _before_ you successfully enqueue those attempts with `Oban.insert` (what might this be???) you _could_ display a flash message explaining that something broke and asking the user to try again, but I don't want to do that since this would certainly be an unexpected error and I'd rather see it bubble up on Sentry then be able to debug the code. That make sense?

**Comment by taylordowns2000** [comment]
Sounds like we might need a quick call to nail this down—let's chat tomorrow! In the meantime:

When you say "while still retrying" do you mean "while you're attempting to add them to Oban" or "while they are running"? Assuming the first, I think what you actually want is the Oban.multi.

```ex
      reducer = fn {changesets, index}, multi ->
        Oban.insert_all(multi, "run_batch_#{index}", changesets)
      end

      runs
      |> Enum.chunk_every(5_000)
      |> Enum.with_index()
      |> Enum.reduce(Ecto.Multi.new(), reducer)
      |> Repo.transaction()

      conn
      |> put_status(:ok)
      |> text(Enum.count(runs))
```

What we can chat about tomorrow is that if the user asks to enqueue 43,000 attempts, it would be nice to _either_ have them all get enqueue or have none of them get enqueued. (We don't know and don't care if the new attempts succeed or fail as they are processed over the next several days... our job is _DONE_ and we report back to the end user "All good... 43,000 enqueued!" as soon as they hit the queue.)

**Comment by taylordowns2000** [comment]
@midigofrank , next steps here please:

- [ ] rebase on `main`
- [ ] get all tests passing with current implementation style (then ping me on github please!)
- [ ] once tests are passing, optimize to use the `Oban.insert_all` so we're hitting the DB slightly less for a big bulk re-processing request

**Comment by taylordowns2000** [comment]
I haven't seen that problem pop up for anyone yet. Please push your most recent changes to your branch (assuming you've rebased, also check that box above!) and I'll fire it up.

Tests run OK for me as of this commit:
```
commit 04cdafe004f5aec7b19e7973166235640493f3b5 (HEAD -> 659-bulk-rerun-work-orders, origin/659-bulk-rerun-work-orders)
Author: Frank Midigo <midigofrank@gmail.com>
Date:   Wed Jun 14 12:58:21 2023 +0300
```

**Comment by taylordowns2000** [comment]
Eish, sorry @midigofrank , it looks ok on my machine and on [circleCI](https://app.circleci.com/pipelines/github/OpenFn/Lightning/3296/workflows/0a3fb738-78f5-47f2-b322-7ae0231ef867/jobs/16706/tests). i'm not sure i'll be able to help.

What OS are you using? Have you seen this issue on other Elixir projects? Maybe try `asdf install` again just to make sure? @sigu , any ideas on this one?

<img width="682" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/65741074-8ff6-49b7-b57b-0c376f64659e">

**Comment by taylordowns2000** [comment]
Hrmmm I'm on an M1 also.

**Comment by taylordowns2000** [comment]
Yeah it does. Maybe you've got MIX_ENV set to something else by default in
your path?
