### ISSUE TITLE
Flaky test: project members can edit their own digest frequency

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#665]
![Screenshot 2023-02-26 at 23.18.35.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/66eb7736-43e0-4f52-978f-7036fc116181)
https://app.circleci.com/pipelines/github/OpenFn/Lightning/2226/workflows/b97f2cb3-d5b8-4b31-811b-5a5ea7761859/jobs/10561

**Comment by taylordowns2000** [comment]
no longer flaking as of `v0.10.0`
