### ISSUE TITLE
Make Job Editor read-only for project viewers

### ISSUE THREAD

**Issue by elias-ba** [OpenFn/Lightning#669]
**Is your feature request related to a problem? Please describe.**

Project members have different roles and abilities depending on those roles. Project members with `:viewer` role, can't interact with the job panel components. They can only open the panel and see the job configuration and code. The problem we have currently is that the Editor is editable and we don't want that. We wan't also project members to be able to see the job configuration but not to edit it. This is related to [this PR](https://github.com/OpenFn/Lightning/pull/667).

**Tell us about your idea - describe the solution you'd like.**

I am suggesting that we make the Monaco editor read-only when the user is a project member of viewer access level to that project.

**Additional context**

See screenshots for more context about the UI

![Screenshot from 2023-02-28 14-12-21](https://user-images.githubusercontent.com/86059666/221883127-462896c9-a024-4bb3-8a02-18b922e27279.png)

![Screenshot from 2023-02-28 14-17-54](https://user-images.githubusercontent.com/86059666/221883157-708d0d91-22c8-4640-9dcb-e4d2c2619e9c.png)

**Comment by amberrignell** [comment]
This is already implemented. See screenshot below. cc @elias-ba 
![Screenshot 2023-04-05 at 12.13.15.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/23ae65c5-6cbb-4cf7-96d0-7e2745005d7b)
