### ISSUE TITLE
New credential not saving

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#684]
When creating a new credential on `v0.4.4` it's not persisting. All migrations have been run. Is this an ENV issue?

**To Reproduce** Steps to reproduce the behavior:

https://www.loom.com/share/bb4c3444fe274255802b12ff20b2bcb1

1. Go to the canvas
2. Click on a job
3. Click new credential
4. Click save
5. Modal closes but nothing happens

**Comment by stuartc** [comment]
@taylordowns2000 can you try and recreate this locally and on demo? I have tried locally and on demo (v0.4.5) and both scenarios worked first time.

**Comment by stuartc** [comment]
@taylordowns2000 I can confirm that the broken encryption key on staging was changed yesterday - I've made a PR to better alert on keys that are the wrong length; so the app will crash on startup rather than quietly be broken.
