### ISSUE TITLE
Configuration schemas get reordered in form interface

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#685]
When adaptor configuration schemas are displayed as credential forms in Lightning `0.4.4`, the fields show up out of order.

**To Reproduce** Steps to reproduce the behavior:

1. Create a new OpenMRS credential.
2. Note that password comes _above_ username

**Expected behavior**

- The fields in the form should be in the same order as the key in the JSON schema.

**Screenshots** If applicable, add screenshots to help explain your problem.

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/8732845/224385499-6fe41f2d-fe4e-44c2-96a3-85d47880fa45.png">

**Comment by stuartc** [comment]
This is a difficult one, it seems that ExJsonSchema, and perhaps the way elixir does maps that the ordering is alphabetical - I tried parsing with Jason's `Jason.decode!(objects: :ordered_objects)` and it _is_ ordered then when it goes into ExJsonSchema, but it still comes out in alphabetical order in the schema root.

Will dig a bit deeper before coming up with a proposed solution.

**Comment by stuartc** [comment]
@taylordowns2000 this is a hard one, Elixirs maps are not guaranteed to be ordered. 

We may be able to write something to query the JSON Schema (as in the actual JSON) directly to determine the ordering of the original fields - so I guess two questions.

1. This _technically_ feels like it isn't a bug now. Happy to slice it either way.
2. How much of an appetite do we have for fixing this now. It's not a one-liner fix, it's not a multi-day fix.

_(assuming my proposed fix actually works)_

**Comment by taylordowns2000** [comment]
Eish. This is tricky. I do consider having password appear above username a mild security vulnerability, but it's more just very bad UX.

Whether this is a uncaught bug with the initial implementation or a feature request, I think we've got to do this before adding _new_ things to the application. Thoughts?
