### ISSUE TITLE
Registration Submission on app.openfn.org shows `internal server error` in browser

### ISSUE THREAD

**Issue by jayesse** [OpenFn/Lightning#686]
**Describe the bug**
I attempted to register on [app.openfn.org](https://app.openfn.org/users/register) and upon filling and submitting the registration form, the browser displayed a blank page with an "internal server error" message. (See screenshot below). 
Note: The registration was however successful, as I duly received an email titled "Confirmation Instructions". I clicked the link in the email, confirmed my account and then logged into Lightning successfully. 

UPDATE:
When a user registers with two first names (ie there's a space), the app throws a format error for the project creation
` errors: [name: {"has invalid format", [validation: :format]}], data: #Lightning.Projects.Project<>, valid?: false>}`

**To Reproduce** Steps to reproduce the behavior:

1. Go to  [app.openfn.org](https://app.openfn.org/users/register) 
2. Click on the `Register` button on the bottom right of the page
3. Fill in _your First name **and include a space in it**, Last name, Email and Password_
4. Click on the big `Register` button to submit your details
5. Observe the error on your screen.

I used google chrome version 110.0.5481.178 (Official Build) (64-bit) (cohort: Stable) on a Windows PC

**Expected behavior** 
Following the steps above should not generate an "internal server error" message.

**Screenshots** If applicable, add screenshots to help explain your problem.
**Error Message**:
![image](https://user-images.githubusercontent.com/97878823/224385093-0198e0a9-8dfd-462e-961b-5ecb2dc99644.png)

**Confirmatory email received afterwards**:
![image](https://user-images.githubusercontent.com/97878823/224385362-cf028485-81f9-43d0-ba46-1b233d317304.png)

**Additional context** Add any other context about the problem here.

See stack trace below

```
no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{name: "elias waly-demo", project_users: [#Ecto.Changeset<action: :insert, changes: %{role: :admin, user_id: "3acf4379-8df4-4c65-8264-1bc13a2489c8"}, errors: [], data: #Lightning.Projects.ProjectUser<>, valid?: true>]}, errors: [name: {"has invalid format", [validation: :format]}], data: #Lightning.Projects.Project<>, valid?: false>}
```

**Comment by amberrignell** [comment]
@jayesse I wasn't able to reproduce (see recording below). Could you give it another go and close the issue if this is no longer a problem?

https://images.zenhubusercontent.com/454419290/4b1f4916-29ec-457b-9c77-8383a7d1ef6e/screen_recording_2023_03_22_at_14_28_36.mov

**Comment by taylordowns2000** [comment]
@amberrignell confirmed that this is no longer an issue. closing
