### ISSUE TITLE
Auto-generate adaptors via chatGPT-4

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#705]
**Is your feature request related to a problem? Please describe.**

Sometimes I want to connect to a system that doesn't yet have an adaptor. Reading API documentation and either using `language-http` or writing a new adaptor for this system is tedious.

**Tell us about your idea - describe the solution you'd like.**

- [ ] I'd like for there to be a button at the bottom of the "adaptors" dropdown list that says "create new adaptor".
- [ ] I'd like it to open up a modal or dialog, and prompt me to enter the URL of the api documentation for this application
- [ ] I'd then like it to prompt me to describe the helper functions I'd like to have — maybe auto suggesting a few based on the API documentation.
- [ ] I'd then like to click "create" and have a new adaptor created by Chat GPT 4.0, published to my account on npmjs, and available for selection in the dropdown list.

**Comment by josephjclark** [comment]
We've just had a bit of a conversation about this over email and I just want to add this point (made by Taylor and echoed by Aleksa).

The idea of generating an adaptor straight from Lightning feels a bit impractical. There's just no way for a user to verify the robustness and suitability of the solution. Even if the tech could generate perfect code, the user is highly unlikely to capture the exact right requirements, even after several iterations (although perhaps with enough iteration and testing through jobs, they could reach a reasonable solution).

More interesting to me is that idea of generating an adaptor template with the CLI. This would require more human intervention and have a slower release cycle - but I think that's only a good thing.

**Comment by taylordowns2000** [comment]
@josephjclark - there's another issue here that speaks to the templating stuff but for expression code itself. see https://github.com/OpenFn/Lightning/issues/706 .

that one (706) is interesting to me because, _like the (coming soon) form-based interface for magic functions_, it might help a less-technical user get 80% of the way there in almost no time, then focus their energy on editing/tweaking/modifying.
