### ISSUE TITLE
Remove empty options project user role dropdown

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#717]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Go to admin settings>projects> click on a project
2. Click on the role next to a user that has access to a project
3. See there is a blank option

**Expected behavior** A clear and concise description of what you expected to
happen.
There should be no blank option in the dropdown list - all users that have access to a project should have ONE of the roles. 

**Screenshots** If applicable, add screenshots to help explain your problem.
![Screenshot 2023-03-22 at 11 38 27](https://user-images.githubusercontent.com/36554605/226846609-aae3c40f-ed8d-46ca-8eb7-cf78679be121.png)

**Additional context** Add any other context about the problem here.

**Comment by zacck** [comment]
@amberrignell  I did a quick fix for this I hope this is ok, just trying to get familiar with the code base
