### ISSUE TITLE
Clarification on the licence

### ISSUE THREAD

**Issue by jeremi** [OpenFn/Lightning#728]
Depending on where I look, there are different licences for this project. Could someone confirm the license of this project?
I see GPL, LGPL and ISC.

**Comment by stuartc** [comment]
Hi @jeremi! The licence is LGPLv3, which as I understand it is an addendum to GPL, so there are two `LICENSE` files (`LICENSE` and `LICENSE.LESSER`).

For the ISC license you mentioned, is that from `package.json` - in which case thanks for pointing that out (it's the default NPM uses with init'ing); it _should_ inherit the license declared in the base of the repository.

Does that sound right to you?

**Comment by jeremi** [comment]
Thanks @stuartc . Actually they are different Licenses. 
https://www.tldrlegal.com/license/gnu-general-public-license-v3-gpl-3
https://www.tldrlegal.com/license/gnu-lesser-general-public-license-v3-lgpl-3

While they have some similarities, they are two separate licences. This is why GitHub is a little confused:
![image](https://user-images.githubusercontent.com/9537/227480900-e1870f80-0aa7-4c50-8606-5400f60e5233.png)

If you compare to my project ([OpenSPP](https://github.com/openspp/openspp-registry)):
![image](https://user-images.githubusercontent.com/9537/227481055-410145d3-ca36-4978-ae00-9a7f61ed80f7.png)

I'd recommend keeping the LGPL file and removing the GPL one.

**Comment by stuartc** [comment]
@jeremi We used Github to generate these licenses from a preset, and that seems to follow the GNU guidelines I've seen:

> If you are releasing your program under the Lesser GPL, you should also include [the text version of the LGPL](https://www.gnu.org/licenses/lgpl.txt), usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's crucial to include both licenses so users have all the materials they need to understand their rights.
> - [gnu.org/licenses/gpl-howto.html](https://www.gnu.org/licenses/gpl-howto.html#license-files)

and

> This license is a set of additional permissions added to [version 3 of the GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html). For more information about how to release your own software under this license, please see our [page of instructions](https://www.gnu.org/licenses/gpl-howto.html).
> - [gnu.org/licenses/lgpl-3.0.en.html](https://www.gnu.org/licenses/lgpl-3.0.en.html)

**Comment by jeremi** [comment]
Interesting, though this is weird that Github is confused. The issue is the GPL is quite restrictive compared to the LGPL.

**Comment by jeremi** [comment]
It seems you are right. I'm not sure the best way for it not to be confusing. I'll try to ask a friend at GitHub to see if he has an idea of how to do it.

**Comment by jeremi** [comment]
It seems there is a solution; you might need to rename the file LICENSE.LESSER to COPYING.LESSER:
https://github.com/orgs/community/discussions/22258
https://github.com/licensee/licensee/issues/287
