### ISSUE TITLE
blank input dataclip?

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#734]
**Describe the bug** 
We got an error about a blank input dataclip, but this should never be happening. 

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to
happen.
There should never be any scenario where an input dataclip is blank. 

**Additional context** Add any other context about the problem here.
Stack trace below

```
{
  "at": "2023-03-26T12:00:19.853497Z",
  "error": "** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{attempt_id: \"034a074c-ee02-45b3-b241-6e065328d43c\", id: \"74b56c93-36ea-4b61-aef3-8956ddeeb76d\", run: #Ecto.Changeset<action: :insert, changes: %{job_id: \"2147354a-58ea-44f4-9f0e-3931fb310e50\", previous_id: \"c1488bce-5cd3-4b01-ae19-891d0e1f1739\"}, errors: [input_dataclip_id: {\"can't be blank\", [validation: :required]}], data: #Lightning.Invocation.Run<>, valid?: false>}, errors: [], data: #Lightning.AttemptRun<>, valid?: false>}\n    (lightning 0.4.6) lib/lightning/pipeline.ex:39: anonymous fn/3 in Lightning.Pipeline.process/1\n    (elixir 1.14.1) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (lightning 0.4.6) lib/lightning/pipeline.ex:37: Lightning.Pipeline.process/1\n    (oban 2.14.2) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1\n    (oban 2.14.2) lib/oban/queue/executor.ex:74: Oban.Queue.Executor.call/1\n    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.1) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3\n",
  "attempt": 1
}
```

**Comment by elias-ba** [comment]
Needs more clarity. I spent a good time on it trying to figure where in the app could we have blank input dataclip but I couldn't find out something relevant. What does it even mean to have a blank input dataclip ?

**Comment by stuartc** [comment]
This is an edge case I haven't been able to replicate recently, for now unless it happens again with more frequency we can leave this - as the Pipeline is going to be replaced with workers.

**Comment by NickOpenFn** [comment]
Going to close this for now (no point in having Zombie issues in Blocked) - if it recurs we can reopen or recreate the card.
