### ISSUE TITLE
Block simultaneous editors working in same workflow

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#754]
All sorts of problems can still be caused by having two users make changes to the same workflow. (We've made this low priority now since we don't allow multiple users per project except on special request before public release.)

- Notify/warn when another user is viewing or editing?
- Use Phoenix Presence?

## MVP implementation

Warning that this might not be a good MVP, as it could limit us fairly significantly if we _later_ want "pointer tracking" or "cursor tracking" using cool stuff like CRDTs.

1. Use Phoenix Presence to display a warning when there is another editor.
2. On "Save" display a warning that you _may_ overwrite a new change, ask user if they want to continue.

- [x] #1949

Design here: https://www.figma.com/file/4hGWdO4sajnjcOwE81j8BK/App-(new)?type=design&node-id=2477-4493&mode=design&t=Ha7Ifoa1WICUVpmp-0

**Comment by christad92** [comment]
I am proposing a temporary fix that tells the user that someone is actively editing on the canvas. We can go further to allow the user but they will only be able to proceed in view/read only mode. 

![Image](https://github.com/OpenFn/lightning/assets/5230530/630f00d1-dc40-41cf-a3d6-5de3198ebf7a)

**Comment by taylordowns2000** [comment]
This is great. I'd upvote **strong** here as we now allow users to add collaborators via the UI.
