### ISSUE TITLE
Delete a project (as superuser)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#757]
### User story

As a Lightning superuser...

1. I would like to be able to delete a project from the admin settings > projects page, so that I can remove projects that are no longer in use.
2. I would like to be able to cancel a project deletion, so that I can prevent a project from being deleted if I change my mind.
3. I would like to purge a project instantly, once it's been scheduled for deletion.

### Details

- The "delete" button (1) appears only for projects that have not been scheduled for deletion
- The "cancel deletion" (2) and "delete now" (3) buttons  appears only for projects that _HAVE_ been scheduled for deletion.

Change the projects page to use the same table component as the users page. Add the columns project name, scheduled for deletion and action  (delete) 
 
- When the user clicks delete, schedule the project for deletion `{PURGE_DELETED_RECORDS_AFTER_DAYS}` days from the current date and disable all of its jobs. 

The email functionality will be added in the owner issue

### Implementation notes

![image](https://user-images.githubusercontent.com/8732845/229478176-22003e1c-20e9-4545-9b40-28d0813fff18.png)

### User acceptance criteria
- [ ] on the projects page, there is a delete button
- [ ]  when the superuser clicks delete AND delete now, they get a confirmation modal before they can delete it
- [ ] when a user deletes a project (not delete_now), it is only scheduled for deletion. ie, the project is still there for PURGE_DELETED_RECORDS_AFTER_DAYS days
- [ ] when a user clicks 'delete_now', the project IS deleted and no longer present in the database. 
 - [ ] if a user inputs the wrong project name into the confirmation modal, they are unable to delete the project

**Comment by mtuchi** [comment]
@amberrignell do we have a Github issue for when a project is scheduled for deletion it should not appear on dashboard or credentials select  box ?
