### ISSUE TITLE
Search run logs doesn't work

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#771]
It's not possible to search for runs by log text.

**Version number**

`v0.5.0`

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Create a job with an expression `console.log("funkyString")`; run it.; verify that "funkyString" appears in the logs.
2. Go to the history page and search for "funkySting"
3. See no results

**Expected behavior**

We should see that run

**Additional context** Add any other context about the problem here.

It looks like this functionality should be covered here: https://github.com/OpenFn/Lightning/blob/main/test/lightning_web/live/work_order_live_test.exs#L1067-L1071

**Comment by amberrignell** [comment]
Not an issue, this feature works as expected
