### ISSUE TITLE
Update history URL params to include expanded work order

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/lightning#775]
### User story
As a user that is looking at a specific work order (expanded view), I would like that to be in the url, so that I can share it with someone else.

### Implementation notes
@taylordowns2000 I'm open to other suggestions here depending on what's easier to implement. 
At the core we just need to be able to share a link to a specific work order. 

### User acceptance criteria
- [ ] when I expand a work order, the url is updated. When I click on the run then go back I can still see the expanded view.
- [ ] when I have use the search and filters and then expand a workflow, all of these are added to the url

**Comment by taylordowns2000** [comment]
@amberrignell , the easiest way to get this done would be via a workorder detail page. i've pasted a screengrab from that low-fi figma mockup:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/8732845/230040091-00baa081-3174-4077-a0e2-38da51aa21b8.png">

**Comment by taylordowns2000** [comment]
done with WO params on history page
