### ISSUE TITLE
Update project permissions to new pattern 

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/Lightning#809]
### Details
The two files below are using an old pattern for authorization 👇🏽 , Update them to use the pattern laid down in https://github.com/OpenFn/Lightning/pull/613
- `lib/lightning_web/hooks.ex`
- `test/lightning/projects/policy_test.exs`

**Comment by amberrignell** [comment]
Closed by https://github.com/OpenFn/Lightning/pull/820
