### ISSUE TITLE
delete job

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#830]
Add a delete button to the Job setup form. 

![Screenshot 2023-06-13 at 12.20.08.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/f06c37ad-b4f0-4104-b987-80232c1e6bd5)

If a job is referenced as a source (NOT a leaf node), the delete should be disabled and the user should get an explanation of why they cannot delete the job. 
When the user clicks delete, the job AND it's associated edges should be deleted. 

### Implementation notes

We need to decide/work out, where the best place to deal with this is.
Do we do all the logic on the frontend (we will need to handle the missing records before Ecto gets the params).
Or do we do a mixture of the frontend and backend (i.e. `delete: true`)
@stuartc your input is needed here

**Comment by taylordowns2000** [comment]
- When I try to delete a middle job in a flow, the delete button is greyed out properly.
- When I try to delete a final job in a flow, I get an error message.
- In the image below, I am trying to delete the "Notify CHW Upload Failed" job.

![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/fcca8025-033a-43b6-9c5d-febb94bf73e9)

**Comment by stuartc** [comment]
Derp, that's what I get for not writing tests for that 🤦‍♂️
