### ISSUE TITLE
Bulk rerun workorders (from a specific job)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#833]
### User story

As a user that has a multi-job workflow where a data is

1. fetched from system A
2. transformed to structure B
3. and _then_ loaded to system C

when I realize that the _second job_ is not working properly, I would like to bulk reprocess work orders _from that specific job_, so that I don't need to fetch all the data again in step 1.

Building on #865 , rather than initiating a new attempt from the first `attempt_run` in the last attempt for each selected workorder, this feature will allow the user to initiate a new attempt from from the the "job X" attempt_run (if it exists) in the last attempt for each selected workorder.

### Details

When a user has selected work orders that all belong to the SAME WORKFLOW, add a "Rerun from..." button next to the rerun button (rename to rerun instead of rerun from start).

<img width="347" alt="Screenshot 2023-06-21 at 15 11 56" src="https://github.com/OpenFn/Lightning/assets/36554605/a0f4facf-afe7-4591-8957-a9a13d714192">

![Screenshot 2023-06-29 at 10.32.04.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/ec775b58-e7f2-4916-a9b6-230df78c33fd)

The options in the list are all of the jobs that are currently in the workflow. 

### Implementation notes

1. The "rerun from job X" interface should only appear when workorders for a SINGLE workflow are selected.
2. If "all" workflows matching the query are selected, the query must include a single workflow condition.
3. If you rerun 10 workorders "from job 7" but the final attempt for each of those workorders does not contain an attempt_run for "job 7", then only those containing an attempt_run for job 7 will be rerun.
4. This might be done by filtering out runs where `job_id != 7` [here](https://github.com/OpenFn/Lightning/pull/865/files#diff-3ec2daa312c9b31faa10f1083f49db9def6a22db73999a3dcfb9430ab8295f64R276-R277) - the important thing is that the filtering happens AFTER we have already selected the most recent attempt for each workorder.

Filtering sequence:
1. for these 4 selected workorders (4 rows)
2. find last attempt for each (4 rows)
3. find the run where `job_id = 7` in the last attempt (3 rows if one attempt does not include a job 7 attempt run)
4. create 3 new attempts from those 3 `attempt_runs`

### User acceptance criteria

- [x] The "rerun from..." button appears when I select multiple workorders that belong to the same workflow
- [x] The "rerun from..." button disappears (but the "rerun" button remains) when I select multiple workorders that belong to _different_ workflows.
- [x] When I "rerun from job X" and the final attempt for a selected workorder does not include job X, no new attempt will be made for that workorder

**Comment by taylordowns2000** [comment]
Notes/assumptions for double-checking with @amberrignell :
1. The "rerun from job X" interface should only appear when workorders for a SINGLE workflow are selected.
2. If "all" workflows matching the query are selected, the query must include a single workflow condition.
3. If you rerun 10 workorders "from job 7" but the final attempt for each of those workorders does not contain an attempt_run for "job 7", then only those containing an attempt_run for job 7 will be rerun.
4. This might be done by filtering out runs where `job_id != 7` [here](https://github.com/OpenFn/Lightning/pull/865/files#diff-3ec2daa312c9b31faa10f1083f49db9def6a22db73999a3dcfb9430ab8295f64R276-R277) - the important thing is that the filtering happens AFTER we have already selected the most recent attempt for each workorder.

Filtering sequence:
1. for these 4 selected workorders (4 rows)
2. find last attempt for each (4 rows)
3. find the run where `job_id = 7` in the last attempt (3 rows if one attempt does not include a job 7 attempt run)
4. create 3 new attempts from those 3 `attempt_runs`

**Comment by taylordowns2000** [comment]
Yes!

**Comment by taylordowns2000** [comment]
hey @midigofrank ! are you ready to pick this up? if so, please open that draft PR and post EOD updates. thank you!

**Comment by taylordowns2000** [comment]
@midigofrank , sorry, I don't think that's part of the spec—did you get my Slack invites? would like to talk to you quickly if possible.

cc @amberrignell
