### ISSUE TITLE
Example runs for demo incorrect

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#856]
**Describe the bug** 
The example runs generated on user registration and on demo setup aren't in the correct order

**Version number** 
 v0.6.0

**To Reproduce**

1. Go to demo
2. Click on history page
3. See job runs don't show up in the correct order, and 2 of them fail or timeout
<img width="796" alt="Screenshot 2023-06-06 at 14 33 46" src="https://github.com/OpenFn/Lightning/assets/36554605/7c7511ae-5b8a-4a92-b93a-a1c4417f155e">

**Expected behavior** A clear and concise description of what you expected to
happen.

The runs should be in the below order: 
- Transform data to FHIR ... (success)
- Send to OpenHIM ... (failure)
- Notify CHW upload failed ... (success)

**Comment by taylordowns2000** [comment]
@elias-ba , @mtuchi , I'm re-opening this as I don't think that https://github.com/OpenFn/Lightning/issues/821 was actually completed — see Slack. I can't see any tests and don't think the exit codes are being set on the first job in each workflow. Maybe that's why everything is appearing (for both workflows) as a timeout.

cc @amberrignell , please check out the other workflow also. i'm not sure either is working the way we want

**Comment by taylordowns2000** [comment]
OK so the escript is working again, but neither workflow has proper runs, and this makes me think that the demo project doesn't work as expected either. See slack for deets

<img width="839" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/3ab4f222-c5e7-45b1-9ea3-d20bbbd98396">

<img width="840" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/fb859c16-35ea-49fe-9e54-6a506aa55750">

**Comment by amberrignell** [comment]
@elias-ba cc @taylordowns2000 
Expected: 

All runs should be in the correct order. 

••demo runs••
<img width="787" alt="Screenshot 2023-06-08 at 16 00 09" src="https://github.com/OpenFn/Lightning/assets/36554605/354c9f21-44d9-4384-a2f8-2c185c544230">
-> for this, change the job code in "Send to OpenHIM to route to SHR" to return state rather than x


<img width="793" alt="Screenshot 2023-06-08 at 16 04 24" src="https://github.com/OpenFn/Lightning/assets/36554605/0fcd1778-a923-44e0-9ac5-75316538ee33">
-> for this, add the DHIS2 credentials to the "Get DHIS2 data" job

••registration runs••
<img width="746" alt="Screenshot 2023-06-08 at 15 56 25" src="https://github.com/OpenFn/Lightning/assets/36554605/45a2133c-5553-460e-9b72-12edb23d4158">

**Comment by amberrignell** [comment]
@elias-ba for the DHIS2 to sheets workflow, please also add _another_ workorder (so there should be 2)

<img width="809" alt="Screenshot 2023-06-08 at 16 55 55" src="https://github.com/OpenFn/Lightning/assets/36554605/e999f052-fdcc-4252-93f8-48b1ae5656c4">

(we want a failing work order, so that when we are demoing the app we can "rerun" and show how the status gets updated)

AND all of the runs should have inputs, outputs and logs
[will add specifics here in a sec]
