### ISSUE TITLE
Allow users to enable/disable triggers

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#860]
- As a user that wants to temporarily stop a webhook trigger from creating workorders,
- Or as a user that wants to temporarily prevent a cron trigger from creating workorders,
- I would like to be able to enable or disable my `trigger` (represented as a circle on my canvas) with a simple checkbox on the trigger form panel.
- So that I don't have to DELETE a trigger entirely, forcing me to lose my webhook URL or my cron schedule.

## Implementation
1. Migration to add `enabled` to triggers
2. Modification of the liveview form for triggers
3. Modification of the `webhooks_controller.ex` to return 403 on `!trigger.enabled` rather than `!trigger.job.enabled`
4. Modification of the [enabled_cron_jobs query](https://github.com/OpenFn/Lightning/blob/659-bulk-rerun-work-orders/lib/lightning/jobs/query.ex#L34) to filter on `trigger.enabled` rather than `trigger.job.enabled`

## Design:

**Figma:** https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=280-3048&mode=design

- [ ] Disabled wording displayed on trigger panel
- [ ] If disabled, the trigger node will display with an opacity and label will display indicating it's disabled
- [ ] On the Workflow overview screen, we will also indicate that the workflow is disabled with a small label and dropping the opacity of the text and container (not of the label)

## Acceptance criteria

- [ ] `Enabled?` checkbox appears on trigger form for both `cron` and `webhook` triggers
- [ ] When `enabled == false` a webhook request to that URL will return a 403 and no workorder will be created.
- [ ] When `enabled == false` no workorder will be created for a workflow with a cron trigger matching the current cron schedule

## Historical Context

1. **Triggers** make it possible for the _system_ (not a user) to automatically start a workflow (via `cron` or `webhook` request) with some input at a specific step.
2. It should be possible to turn on and off these "automatic starters" (i.e., prevent a cron trigger from running or return a `:403` when a webhook request is received)
3. It should also be possible to turn on and off certain **_branches_** in a workflow. (e.g., "The jobs for handling `patients > 18yrs` haven't yet been implemented, please switch off that whole branch until further notice.") _(Note: This is handled in #860)_

### Details

In the past, this was done with `job.enabled`, but the new runtime has no support for "enabled" or "disabled" jobs. It only knows nodes and edges. If you wanted to disable a job, you'd want to provide an edge with a condition of `false` or maybe _remove_ that whole branch before sending it to the runtime!

1. The RTM will not support "enabled" or "disabled" jobs. If an edge flows to a job and the condition is met, that job will be run.
2. If a user wants to _not_ run a section of a workflow, they could disconnect the `source_job_id` or the `target_job_id` and have a "dangling" section. This will be supported by the RTM. And you could still run a dangling section by sending the `:start` key to the RTM from that job itself. Do we want this? (No, for now enabled/disabled on triggers AND edges is best.)

**Comment by NickOpenFn** [comment]
@taylordowns2000 
From my experience the more common practice here would be `Pause` the workflow in it's entirety which (I believe) effectively does the same thing. 

From a UX perspective I believe that to be the better solution and being clearer to the users (especially since there is only one starting Trigger for a workflow atm).

Is there a different reason to have a enabled option instead? If the idea is in future to have multiple Triggers, then this makes sense (though I'd still suggest we add a Pause function for the workflow).

LMK!

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/860?planning-poker) with Zenhub @elias-ba @midigofrank
