### ISSUE TITLE
Create component for job edit/view run

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#862]
### Details
Create a new component for a modal <— @stuartc what should we call this? 
Make sure the component can take 2 states: “viewrun” or “editjob” <- @stuartc same here, please suggest names which make sense

**Common**
The modal should be almost full screen
It should have a cross at the top right which closes the modal

The top of the modal should display: 
- Adaptor type
- Credential name
- Job name
- Cross to close
![Screenshot 2023-06-08 at 15.27.46.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/0b1c0235-d7b5-4c1a-b93c-1d314e2750fd)

**View run state**
![Screenshot 2023-06-08 at 15.22.28.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/7aebe5a1-7816-4db8-8b90-ac526db99105)

The top of the modal should ALSO display: 
- finished
- ran for
- exit code

The bottom of the modal should have: 
- Rerun 

**Edit job state**

![Screenshot 2023-06-08 at 15.14.57.png](https://images.zenhubusercontent.com/6213beb680f894633e82cffc/ead9c178-dc30-4fa8-97c9-9c5bf88bccd2)

The bottom of the modal should display: 
- Run job 
- Save
- Job setup

### Implementation notes
Consider using same approach as PODI where modal is hovering at the bottom and use js functions to show and hide. 
Note: the modal will have react components, monaco ... fairly heavy things -> so we _may_ not want to render it all the time.
maybe some lazy loading

### User acceptance criteria
- [ ] users should be able to share a url to the expanded modal

**Comment by zacck** [comment]
@amberrignell question when you close this Modal should you go back to a selected job?

**Comment by taylordowns2000** [comment]
moving back to backlog for re-checking the finer points before we close @amberrignell
