### ISSUE TITLE
BUG: Multiple ids on same page creatig a job

### ISSUE THREAD

**Issue by sigu** [OpenFn/Lightning#871]
### User story
As a developer
When I go to add a new job in a workflow
I initiate duplicate dom ids
### Details
<img width="1538" alt="Screenshot 2023-06-12 at 19 52 52" src="https://github.com/OpenFn/Lightning/assets/584211/1407d614-50e7-4e85-8e4f-9d91b78f0442">

### User acceptance criteria
Page should contain unique ids

**Comment by NickOpenFn** [comment]
Moving to backlog to have more capacity for RTM

**Comment by elias-ba** [comment]
Couldn't reproduce this. It seems to be already solved during the nodes and edges refactor / new job editor UI.
