### ISSUE TITLE
Write/run sql script to convert triggers

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#875]
To keep projects built on app.openfn.org, we must execute a set of small SQL scripts before running the `drop_x` migrations from the `nodes-and-eges-release` branch.

This issue is to create a SQL script that does the following:

fetch a list of triggers from the database
check what each trigger is doing, and make a new edge for it based on the criteria below: 
- [ ] for each trigger where type = `cron`, create an edge from that trigger to its associated job with condition `'always'`
- [ ] for each trigger where type = `on_job_success`, create an edge from the upstream job to the downstream job with condition `'on_job_success'`
- [ ] for each trigger where type = `on_job_failure`, create an edge from the upstream job to the downstream job with condition `'on_job_failure'`

**Comment by zacck** [comment]
The way this works will need it to be merged in and ran before we merge in nodes and edges refactor,  it depends on a database structure that is on main and will cause a database structure that needs the refactor
