### ISSUE TITLE
Disable webhook urls when their triggers are changed to cron jobs

### ISSUE THREAD

**Issue by zacck** [OpenFn/Lightning#881]
**Is your feature request related to a problem? Please describe.**

When triggers are updated from webhooks to cron jobs we should disable there old webhook urls so that submitting to those urls does not get a job going

**Tell us about your idea - describe the solution you'd like.**

**Additional context**

N/A @amberrignell ... ?

**Comment by taylordowns2000** [comment]
Closing in favor of deleting triggers entirely. (Cannot change from webhook to cron: #863 )
