### ISSUE TITLE
Move enabled/disabled property from jobs to edges

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#895]
Figma: https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=385-7635&mode=design&t=GE0qZkJNsdMrtFey-4

Currently an edge comprises the following elements:
- A condition, which can take on values such as `:always`, `state.data.form.entries[0] == 'test application'`, or `state.data.form.user.submitted_by.crazy_long_path.email` == `'test@msf.org'`, depending on specific requirements.
- A label.
- An icon.

We need to extend this to now include an 'enabled' boolean to provide users with the ability to deactivate an edge. This deactivation prevents the edge from being considered when generating a 'plan' without entirely deleting it or setting it to 'false'.

This design pattern effectively separates the execution of 'jobs' from the decision of whether they should run. In the case of a condition, this responsibility lies with the 'edge,' and for 'enabled/disabled' status, it's determined by the component responsible for building the workflow 'plan.'"

~Noting that if an edge is disabled, all following edges will be disabled (and therefore, the jobs won't run).~ @benedictus-dev , @NickOpenFn , this isn't right. let's chat this morning.

- [x] Add checkbox for enabling/disabling the edge on the edge panel 
- [x] Remove checkbox for enabling/disabling the edge on the job panel 
- [x] Add a migration that will add a enabled column in the edge table `workflow edges` and remove the enabled column from the jobs table
- [x] Refactor all code areas that reference of `job.enabled` to `edge.enabled`
- [x] Update the project import via API feature in Lightning if necessary
- [x] ~If the trigger of the workflow is disabled, all edges are disabled~ (TD says this is not correct)
- [x] Fix up all tests

## Legacy app todo's:

- [ ] OpenFn/platform-app#1820

----

## Original spec: 

An edge has:
1. A condition (`:always`, `state.data.form.entries[0] == 'test application' || state.data.form.user.submitted_by.crazy_long_path.email == 'test@msf.org'`, `:on_success`, etc.)
2. A label
3. An icon

And now,

4. An `enabled` boolean which allows the user to turn off an edge (preventing it from being used when generating a `plan`) without deleting it entirely or setting it to `false`.

With this pattern, `jobs` are stupid. They're told to run, given state, etc. But they don't "decide" whether or not they run. That's the responsibility of the `edge` in the case of a condition or whatever builds a workflow `plan` in the case of `enabled/disabled`.

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/895?planning-poker) with Zenhub @elias-ba @midigofrank
