### ISSUE TITLE
enable configuration to URI root/path

### ISSUE THREAD

**Issue by delcroip** [OpenFn/Lightning#904]
I want to have lightning behind a reverse proxy like coremis.s1.openimis.org/etl

I tried to do a rewrite with nginx:
```
	location /etl/ {
		rewrite /etl/(.*) /$1  break;
		proxy_redirect   off;
                proxy_pass http://${dockerlightning}/;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
                proxy_set_header   X-Forwarded-Proto https;
        }

```
 but I am still getting a redirect to `/users/log_in` instead of `/etl/users/log_in`

will it be possible to add a parameter on lightning like uri_path or uri_root  that would be define to `etl` in my case.

br

**Comment by taylordowns2000** [comment]
hey @delcroip ! does [URL_HOST](https://openfn.github.io/Lightning/deployment.html#environment-variables) do it?

**Comment by delcroip** [comment]
I don't think so (I don't remember if I tested it) because I need an address like URL_HOST:URL_PORT/ROOT_PATH/

**Comment by delcroip** [comment]
I made it work by following this 

https://geoffreylessel.com/2016/hosting-a-phoenix-app-in-a-subdirectory-with-nginx/


I also add to addapt first_setup

**Comment by taylordowns2000** [comment]
That's great @delcroip ! I'll mark this issue as closed but I'm sure it will be helpful for others to see. I will also add a note in our docs site under the deployment section that references this thread.
