### ISSUE TITLE
Trigger webhook URL and cronExpression no longer passed to Trigger.txs

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#910]
The trigger object passed to `getTriggerLabels` no longer contains `webhookUrl` and `cronExpression` so it always looks like the trigger on the canvas is a new and unsaved trigger. (no human readable label.)

![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/3c65545a-63a5-4662-858a-dc1bdb45cca0)

![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/f5a6459f-11b0-41d5-a541-e61be75a9c27)

**Comment by josephjclark** [comment]
This seems to be working properly in #942
