### ISSUE TITLE
Export button hanging in limbo after download?

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#921]
This is a _maybe_ bug:

When I use the new export feature my button stays grey and the loading bar at the top of the screen goes _forever_. Is the same thing happening for you? I know you'd seen this earlier.

## The loading bar at the top of the screen keeps going
<img width="405" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/04599613-e6be-412f-b287-ecbc31537ac5">

----

- Change from button to anchor tag

**Comment by taylordowns2000** [comment]
hey @zacck , i've noticed that the loading bar is still sticking around here. do you have any ideas on how to fix?

**Comment by zacck** [comment]
I am aware of this in the back of my mind but I haven't found a fix yet

**Comment by taylordowns2000** [comment]
@stuartc , do you have any ideas? https://www.loom.com/share/a6d28d61cacc4bfe917322031ff0a877

**Comment by zacck** [comment]
@taylordowns2000  @stuartc  bit of spelunking and I know why this is happening, its because we are not firing this event to signal the finish https://github.com/OpenFn/Lightning/blob/8919dc3c7801f9af3a8736c9f58186ebd06b6ece/assets/js/app.js#L92 finding out how to do it now

**Comment by stuartc** [comment]
```
phx-F3gjDzscnLqtBydx destroyed: the child has been removed from the parent -  undefined
app-abbee6c249160b5ea1f64b563648cd9f.js?vsn=d:2 phx-F3gjDzscnLqtBydx error: unauthorized live_redirect. Falling back to page request -  {reason: 'unauthorized'}
app-abbee6c249160b5ea1f64b563648cd9f.js?vsn=d:2 phx-F3gjDzscnLqtBydx socket: disconnect for page nav -  undefined
app-abbee6c249160b5ea1f64b563648cd9f.js?vsn=d:2 phx-F3gjDzscnLqtBydx destroyed: the child has been removed from the parent -  undefined
app-abbee6c249160b5ea1f64b563648cd9f.js?vsn=d:2  destroyed: the child has been removed from the parent -  undefined
```

Perhaps change it from a `phx-click` to a regular anchor tag.

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/921?planning-poker) with Zenhub @josephjclark @zacck @stuartc @elias-ba

**Comment by stuartc** [comment]
```
 <a href="" download="my_painting.png">Download my painting</a>
```

or https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes
