### ISSUE TITLE
Show that a node is invalid

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#956]
Provide some UX/UI feedback on the diagram that a job/trigger is in an invalid state.

We need some designs and input on what this should look like.

## Technical Notes

This is likely entirely in the WorkflowEditor/Diagram space, the workflow params/store objects contain an error key that when is an array (and longer than 0) signifies there are validation errors on the changeset.

**Comment by osinga** [comment]
### Behavior

- Only show a node's invalid state after the node settings modal has been closed for the first time to prevent giving duplicate feedback from both inside the modal form and the node.
- Keep the node in its invalid state when subsequently opening the node settings modal, until the issues have been resolved.

### Design

- Make the node border red, and keep it red even when it's selected.
- Make the name of jobs and triggers red.
- Add an error label to the right of the node.
  - For horizontal conditions, show it below the node instead.

![Canvas-3](https://github.com/OpenFn/Lightning/assets/6756723/2ff4951b-e3e5-4e5e-b121-01c4e849a48b)

- **Error color:** `#c00005`
- **Error icon:** [`ExclamationCircle`](https://heroicons.dev/?search=ExclamationCircle)

**Comment by taylordowns2000** [comment]
@elias-ba , @stuartc , this was the issue! (and no, not done yet.)
