### ISSUE TITLE
Chore: Log a warning in the console when the Editor/docs component is given latest

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#958]
Log a warning to the console when Editor/docs are given `@latest`

We currently resolve the version before it's sent to the component, however for future debugging it is useful to know that we're sending a version that jsDelivr can't provide.

What are we logging?:
- `assets/js/job-editor/mount.tsx`

The message should be:

"job-editor hook received an adaptor with @latest as it's version - to load docs a specific version must be provided"

## Technical Notes

By removing the call to resolve the adaptor version, and setting the jobs' adaptor to use `@latest` the editor will call out to jsDelivr and you will be able to see a bunch of 404s in the network inspect.

```
  def update(%{form: form} = assigns, socket) do
    socket =
      socket
      |> assign(
        adaptor:
          form
          |> input_value(:adaptor)
          |> Lightning.AdaptorRegistry.resolve_adaptor(),   # <=== here
        source: form |> input_value(:body),
        credential: form |> input_value(:credential),
```

**Comment by taylordowns2000** [comment]
@stuartc is this related to:
1. https://openfn.sentry.io/issues/4146718563/?project=6446500&query=&referrer=issue-stream&stream_index=1
2. https://openfn.sentry.io/issues/4341447508/?project=6446500&query=&referrer=issue-stream&stream_index=0

**Comment by stuartc** [comment]
@taylordowns2000 I don't think so, that looks like something else a little more problematic.

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/958?planning-poker) with Zenhub @elias-ba @stuartc @zacck
