### ISSUE TITLE
Ctrl/Cmd + Enter keybindings to save and run a job

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#960]
Add Ctrl/Cmd + Enter as a keybinding to call the event dispatched by the "Save + Run" button on the Job editor component.

The binding _must_ only be registered when the component is mounted.

See: [`assets/js/hooks/index.ts`](https://github.com/OpenFn/Lightning/blob/main/assets/js/hooks/index.ts) and `SubmitViaCtrlS` for an example of a hook that achieve this.

When the command is invoked and saving isn't possible, a flash message should be shown explaining as such.

Depends on #959 since we don't want to let people quickly run a job until saving before running is implemented.

--------

- [x] Copy paste existing Ctrl/Cmd+s function/hook
- [x] Bind it to the ManualRun form as a `phx-hook` attr

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/960?planning-poker) with Zenhub @zacck @elias-ba @stuartc

**Comment by NickOpenFn** [comment]
UX review: 
- The button indicator for unsaved changes needs to be removed on the save event with the key actions
- When hitting the ctrl/cmd+enter it would be cool if the save button could change to a pressed state for 0.3 seconds as if it were pressed. this will give a visual indication that the save has happened (especially if unsaved changes indicator is removed on completion of that)

**Comment by elias-ba** [comment]
Hey @NickOpenFn you UI/UX change requests have all been addressed. Could you test again and tell me if everything is fine ?

**Comment by taylordowns2000** [comment]
@elias-ba , tested - loom here: https://www.loom.com/share/f95baef87b1f47dbbb6d40620c46f8e7

can you address these three things?

**Comment by taylordowns2000** [comment]
this has been shipped!
