### ISSUE TITLE
Improve feedback when a Workflow name is invalid

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#961]
It's not obvious that the Workflow name is a required field.

This requires some UX/UI input and design to get this right.

**Comment by osinga** [comment]
There's two parts to the changes here. One is the general approach to form errors, and the other is the handling of invalid workflow names specifically.

### Form Errors

- Move the error message _below_ the input
- Make the error message red (`#c00005`)
- Add an icon in front of the error message ([`ExclamationCircle`](https://heroicons.dev/?search=ExclamationCircle))
- Make the input borders red, and make the background light red (`#fdebeb`)

#### Notes

- The behavior doesn't change; just the styling of the error message
- The colors and design are taken from the design system that's currently being worked on

![Canvas-4](https://github.com/OpenFn/Lightning/assets/6756723/0b1f71ed-0139-494e-86b3-765e2f159dd5)

### Workflow Name Input

- Display the workflow name as regular text (not an input)
- Add a button with icon [`Pencil`](https://heroicons.dev/?search=Pencil) beside the name
  - Clicking the button replaces the workflow name with an input
  - Hitting enter while in the input submits it and returns to the initial state
    - If invalid, show the invalid state (with the error on the side for the sake of space)
  
![Workflow Name](https://github.com/OpenFn/Lightning/assets/6756723/098500a5-8b1e-4314-8ea5-76e471eb7998)

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/961?planning-poker) with Zenhub @elias-ba @stuartc @zacck

**Comment by NickOpenFn** [comment]
UI to be improved slightly, and passed along to Elias with Figma:
- pencil icon to have opacity .
- transitions to 0 when text has hover
- Show input field on select (or underline, depending on what's easiest)
- label for save fail/succeeded to be improved slightly (padding, position)
-
