### ISSUE TITLE
Reimplement skipped CredentialLive tests

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#962]
These are existing tests that are skipped:
- create new credential from job inspector and update the job form
- open credential modal from the job inspector (edit_job)
- create new credential from job inspector and update the job form

_and_ rewritten to use the new elements/behaviour.

These three tests should be moved to the `WorkflowLive.Edit` tests, and arguably written as _one_ test.

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/962?planning-poker) with Zenhub @elias-ba @stuartc @zacck
