### ISSUE TITLE
Implement skipped tests in WorkflowLive.EditorTest

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#966]
These tests are targeting using the expanded job editor view (selecting a job and clicking the 'code' button). The underlying LiveView is `WorkflowLive.Edit`, but we test this interface from here instead.

- [x] Viewers can't run a job
- [x] When using manual runs should be able to see last 3 dataclips
- [x] Create new dataclip
- [ ] Mount job editor with correct attributes - refer to old refer to original workflow_live_test.exs in git history (need to find it)

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/966?planning-poker) with Zenhub @josephjclark @stuartc @zacck

**Comment by stuartc** [comment]
@elias-ba thanks for this, I have taken a lot of what you have done and repeated it with changes from my refactor in #1066
