### ISSUE TITLE
RTM: Integrate new Runtime Manager into Lightning

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#973]
## Outline

This epic represents the first phase of executing attempts and runs using the new RuntimeServer.

Issues under this epic are:

**Queuing**

- #983 
- #984 
- #985 

**Job Processing Endpoints**

- #986 
- #987 
- #988 
- #989 

**LocalRuntime**

- #990 

## Considerations

This epic is a major breaking change, we must endeavour to maintain the existing functionality for as long as possible. On the face of it, the solution does appear mutually exclusive and we _may_ be able to get away with a feature flag.

## Notes

This epic does not include the following:

- Worker authentication
  - The worker using a pre-generated key to authenicate
  - The server refusing requests based on either the key or IP
- Marking attempts with the workers identity
- Attempt authentication
  - A more fine grained key (HMAC?) exchange, preventing other (albeit authenticated) workers from pushing or retrieving logs, state or credentials.

**Comment by josephjclark** [comment]
TODO: an endpoint to return a attempt as JSON (one endpoitn for the whole attempt or one for the attempt, one for the credentials, one for the state?)

**Comment by stuartc** [comment]
Noted regressions:

1. Pipeline is obsolete now, can't merge this until everything works
2. Run Index/History view doesn't reflect Attempts that have no runs

This needs an overhaul, and now is the opportunity to get performance improvements when searching. There have been conversations about marking an attempt as started and finished, this could be extended to have a success/failed state as well.

**Comment by taylordowns2000** [comment]
congrats @stuartc and team!
