### ISSUE TITLE
Dataclip type and state assembly notice for creating new dataclip dropped during refactor

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#975]
Changes to how new dataclips are treated have broken the "type: saved input" label and the explanation of how state will be assembled for a new dataclip.

This is how it looked prior to v0.7.0

<img width="697" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/25f07157-34ed-4195-b3af-4a2eebd97460">

And this is how it looks now - hiding the labels between the code editor and dropdown:
<img width="823" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/77bbdbbe-3884-47e2-9d3c-ea9cc60372bc">

The section which describes the dataclip type (with a pill) and the state assembly is missing.

-----

- [ ] Ensure that this works as expected
- [ ] Add test case for this

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/975?planning-poker) with Zenhub @stuartc @zacck @elias-ba @josephjclark
