### ISSUE TITLE
LocalRuntime process that manages a long running Runtime Server child process

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#990]
In order to ease development and default installations of Lightning, the Lightning application should be able to upkeep a long running (external) process.

## Technical Notes

- Create a Genserver that locates and spawns a Runtime server.
- The process passes in a `lightning-url` 
- If the process exits, restart it - backing off exponentially (possibly exiting eventually, taking down the application?)
- All logs emitted from the process should be visible in the Elixir processes logs.
- Think about how this thing handles SIGTERM or SIGQUIT (when you press control-c to stop elixir app from IEX it should shut this thing down)

**Comment by taylordowns2000** [comment]
noting that right now, the RTM server doesn't exist so this long-running process should run a shell script that does this:

```sh
while true
do 
    echo "Hi Frank!"
    sleep 2
done
```

**Comment by taylordowns2000** [comment]
"@midigofrank , add a flag so that this does _not_ start by default in the supervision tree when we get this into `main`" - @stuartc
